### ISSUE TITLE
policy_current_law.json needs to be updated with 2018 parameters

### ISSUE THREAD

**Issue by MattHJensen** [PSLmodels/Tax-Calculator#1694]
https://www.irs.gov/pub/irs-drop/rp-17-58.pdf 

See last year's update: https://github.com/open-source-economics/Tax-Calculator/pull/1169

**Comment by martinholmer** [comment]
@MattHJensen asked for help in adding to `current_law_policy.json` the values of tax policy parameters for 2018.

I know IRS has published 2018 values, but isn't this request pre-mature given that TCJA may change many 2018 values?

**Comment by MaxGhenis** [comment]
If TCJA goes into effect, will this be irrelevant?

On a related note: if TCJA goes into effect, will there be a way to access current policy? I suspect people will continue to be interested in analyzing TCJA relative to current/previous policy. One option could be adding current policy as a "reform" to the [reforms folder](https://github.com/open-source-economics/Tax-Calculator/tree/master/taxcalc/reforms).

**Comment by martinholmer** [comment]
@MaxGhenis said:
> On a related note: if TCJA goes into effect, will there be a way to access current policy? I suspect people will continue to be interested in analyzing TCJA relative to current/previous policy. One option could be adding current policy as a "reform" to the reforms folder.

We haven't discussed this, but passage of the TCJA bill into law will, of course, change the meaning of "current-law policy" and there will probably be a major revision to the contents of the taxcalc/reforms directory.  One of the first new reforms to be added would probably be `prior_law_policy.json`, which would reform the TCJA current-law policy back to the pre-TCJA policy.

**Comment by MattHJensen** [comment]
Perhaps `2017_law_policy.json` or similar, as there may be many "prior laws" in the lifetime of Tax-Calculator.

**Comment by martinholmer** [comment]
@MattHJensen said in issue #1694 entitled "current_law_policy.json needs to be updated with 2018 parameters":
> https://www.irs.gov/pub/irs-drop/rp-17-58.pdf
>
> See last year's update: #1169

Just to confirm my understanding of this issue, the 2018 values in the cited IRS publication are no longer correct given the passage of TCJA.  Right?

I assume IRS will soon publish a new document that has 2018 values for the now-chained-CPI indexed parameters whose amounts were not explicitly changed by TCJA.  We can do this update when that new document is published.

**Comment by MattHJensen** [comment]
> Just to confirm my understanding of this issue, the 2018 values in the cited IRS publication are no longer correct given the passage of TCJA. Right?

That's correct. 

> I assume IRS will soon publish a new document that has 2018 values for the now chained-CPI indexed parameters whose amounts were not explicitly changed by TCJA. We can do this update when that new document is published.

The IRS just published the new parameters, which are explained and linked to from [this KPMG report. 
](https://home.kpmg.com/us/en/home/insights/2018/03/tnf-rev-proc-2018-18-inflation-adjustments.html)

**Comment by MattHJensen** [comment]
This update will be easier when the 2018 forms are published. Currently a draft 1040 is out, but I believe it is being revised.

**Comment by Peter-Metz** [comment]
@martinholmer, thanks for the clear guidance for what needs to be done.

**Comment by martinholmer** [comment]
Issue #1694 has been resolved by the merge of pull request #2212.
