### ISSUE TITLE
TCJA treatment of PT income from service businesses

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/Tax-Calculator#1817]
In #1803 @codykallen said:
> The TCJA also phases out the deduction for service businesses. So far, we've essentially ignored this limitation because we don't have that kind of data. But now that it's becoming law, we need to figure out a way to split the relevant measures of business income (e00900p, e00900s, e00900, e26270) into income from personal service businesses and other business income. But that may be more than this PR can handle and probably requires work in taxdata.

Then @feenberg asked:
> Don't we also need the entity wage bill and assets. I don't see us ever getting that until SOI releases some data. Perhaps someone at JCT would give us a hint about what they did, perhaps we could copy them.  I don't see how they would have any actual data on this either.

And @codykallen responded:
> Technically, the business income exclusion and the wage limitation apply on a per income source basis, rather than overall per filer. For example, suppose a filer has $100 of partnership income and $80 of wage income from business A, and $50 of sole proprietorship income and $10 of wage income from business B. The filer calculates the exclusion first for income from business A, and then separately for income from business B. The exclusion for income from business A is $20 (0.2 * 100). Since this is less than $40 (0.5 * 80), the wage limitation is not binding. The gross exclusion for income from business B is $10 (0.2 * 50), but the wage limitation is only $5 (0.5 * 10). If the filer's taxable income is below the wage limitation threshold, the exclusion for business B is $10. If the filer's taxable income is high enough that the wage limitation is fully phased in, then the exclusion for business B is $5. The total exclusion is the sum of the exclusions for business A and business B.
>
> However, we don't have data on business income source and wage income source, nor is it likely that we can get it. Therefore, I have decided to apply the wage limitation overall, rather than on a per business income source basis.

**Comment by martinholmer** [comment]
@codykallen,  How important is this provision in the TCJA?  Before asking for work to be done in the taxdata repo, it would make sense to do an benefit-cost analysis of the changes you are thinking about here.  How big a change (correction) in income tax revenue would result from having the data to model this TCJA provision?  How much work is going to be involved in adding the data to both `puf.csv` and `cps.csv`?  And how much work is going to be involved in adding the Tax-Calculator logic to use the new data?

Remember there are plenty of esoteric aspects of the tax law that are not modeled in Tax-Calculator (or in any other tax model, I imagine).  So, just because a provision is in the tax code doesn't automatically mean it will be in the computer code.

**Comment by codykallen** [comment]
@martinholmer asked:

> How big a change (correction) in income tax revenue would result from having the data to model this TCJA provision? 

That's hard to determine. It probably amounts to a few billion dollars. However, if someone attempts to model the shifting of wage income to business income to take advantage of the business income exclusion, this provision will become much more important, as it would eliminate the exclusion for upper middle income and high income filers.

@martinholmer also asked:

> How much work is going to be involved in adding the data to both puf.csv and cps.csv? 

I think the challenge is not the amount of work required to implement this breakdown, but rather the difficulty of doing it accurately. I'm not sure there exists a data source that would allow business income to be effectively separated between income from services businesses and income from other businesses. 

@martinholmer also asked:

> And how much work is going to be involved in adding the Tax-Calculator logic to use the new data?

The logic is relatively straightforward (and simpler than the wage limitation), as long as one has already determined what qualifies as business service income and what does not.

**Comment by martinholmer** [comment]
@codykallen,  Thanks for your benefit-cost analysis of modeling the TCJA provisions regarding pass-through income from service businesses in issue #1817.

Seems from what you say that this is largely a data issue.  So, you might want to raise this as an issue in the taxdata repo.  We will keep this Tax-Calculator issue open to remind us of the need for this enhancement.  You'll have to talk to the taxdata developers and @MattHJensen about where this data enhancement request would fit into the priorities of the taxdata developers.

**Comment by martinholmer** [comment]
Tax-Calculator issue #1817 has been partially resolved by the improvement in the logic of calculating qualified business income deduction amounts in pull request #2345.  The remaining data issue has been highlighted in a new [taxdata issue 319](https://github.com/PSLmodels/taxdata/issues/319).  Given these developments, it seem sensible to close this older issue.
