### ISSUE TITLE
Adding Benefit MTRs  to Tax-Calculator

### ISSUE THREAD

**Issue by andersonfrailey** [PSLmodels/Tax-Calculator#1873]
The next step in adding full benefit functionality in Tax-Calculator is to add the MTRs associated with the benefit programs. MTRs are calculated individually in C-TAM and, except for SNAP, each unit will have a unique MTR.  I'm working on data side of things, but there are a few issues related to Tax-Calculator I'd like to hear some other opinions on.

1. Where should the MTR's be saved in the taxcalc package? I'm inclined to add them to `cps_benefits.csv.gz` and filter them to include only those who receive benefits. We're assuming the MTRs are constant overtime so this would only add one column per benefit to the file. We would then assign an MTR of zero to every unit not in the file, like we do with extrapolated benefits. Or they could be added directly to `cps.csv.gz`.
2. There are some units who will go from positive benefits to no benefits and vice versa. Setting MTR to 0 for those with no benefits is straightforward and can be handled in the `extrapolate_benefits` method, but what about those who go from no benefits (and thus an MTR of zero) to benefits? Should the average MTR for that benefit be given to them?
3. The `mtr` method  currently returns three arrays for MTR's. Should it be modified to return benefit MTRs or should the user access the benefit MTRs some other way (like a new method called `benefit_mtr`)?
4. Where/how should the benefits be factored into `behavior.py`? The private `_mtr12` method of the behavior class seems like the obvious place for adding them. How this is done circles back to point 3. Should the `mtr` method of the calculator class be modified to return additional MTRs or should there be a separate method dealing with benefit MTRs?

cc @martinholmer @MattHJensen @Amy-Xu

**Comment by feenberg** [comment]
On Tue, 13 Feb 2018, andersonfrailey wrote:

> 
> The next step in adding full benefit functionality in Tax-Calculator is to
> add the MTRs associated with the benefit programs. MTRs are calculated
> individually in C-TAM and, except for SNAP, each unit will have a unique
> MTR. I'm working on data side of things, but there are a few issues related
> to Tax-Calculator I'd like to hear some other opinions on.
>
>  1. Where should the MTR's be saved in the taxcalc package? I'm inclined to
>     add them to cps_benefits.csv.gz and filter them to include only those
>     who receive benefits. We're assuming the MTRs are constant overtime so
>     this would only add one column per benefit to the file. We would then
>     assign an MTR of zero to every unit not in the file, like we do with
>     extrapolated benefits. Or they could be added directly to cps.csv.gz.

Do we save the tax MTRs? If not, why treat the benefit MTRs differently? 
Wouldn't it make sense to recalculate them on each run?


>  2. There are some units who will go from positive benefits to no benefits
>     and vice versa. Setting MTR to 0 for those with no benefits is
>     straightforward and can be handled in the extrapolate_benefits method,
>     but what about those who go from no benefits (and thus an MTR of zero)
>     to benefits? Should the average MTR for that benefit be given to them?

I am not sure what this question is about. "go from" means what? If we 
comparing two benefit regimes, then there is a base MTR, and a delta MTR. 
Both are well defined. If a person with no child benefit (mtr=0) is given 
a child benefit and is in the .5 clawback range, then the base is zero and 
the delta is .5.

>  3. The mtr method currently returns three arrays for MTR's. Should it be
>     modified to return benefit MTRs or should the user access the benefit
>     MTRs some other way (like a new method called benefit_mtr)?
>  4. Where/how should the benefits be factored into behavior.py? The private
>     _mtr12 method of the behavior class seems like the obvious place for
>     adding them. How this is done circles back to point 3. Should the mtr
>     method of the calculator class be modified to return additional MTRs or
>     should there be a separate method dealing with benefit MTRs?
>

The total MTR is the arithmetic sum of the tax MTR and the benefit MTR 
unless there is some interaction. Do any of the benefits depend on taxes? 
I don't recall any. Some state taxes (especially credits) will depend on 
benefits though.

dan

**Comment by martinholmer** [comment]
@andersonfrailey said in issue #1873:
> The next step in adding full benefit functionality in Tax-Calculator is to add the MTRs associated with the benefit programs.

For those of us who are not that familiar with the work in the C-TAM repository, could you define exactly what you mean by "benefit MTR"?

**Comment by martinholmer** [comment]
@andersonfrailey,
Can you point us to the benefit reduction rate data file that you want to incorporate in Tax-Calculator?
I assume it has a RECID column and other columns with the estimated program benefit reduction rates, right?

@MattHJensen @Amy-Xu

**Comment by martinholmer** [comment]
The last comment in issue #1873 was made on February 15, nearly six months ago.
Are there any reasons to keep issue #1873 open any longer?

If so, what are the answers to [this Feb-13th question](https://github.com/open-source-economics/Tax-Calculator/issues/1873#issuecomment-365389354) and to [this Feb-15th question](https://github.com/open-source-economics/Tax-Calculator/issues/1873#issuecomment-365988284)?

@MattHJensen @feenberg @Amy-Xu @andersonfrailey

**Comment by MaxGhenis** [comment]
I'd find benefit MTRs really valuable.

On @andersonfrailey's "There are some units who will go from positive benefits to no benefits and vice versa," is the problem welfare cliffs? For example someone right below the Medicaid income limit could lose $10k in benefits for earning a marginal dollar, making for a 1M% MTR. IIUC Medicaid MTRs will be zero elsewhere on the income distribution.

**Comment by feenberg** [comment]
On Mon, 6 Aug 2018, Max Ghenis wrote:

> 
> I'd find benefit MTRs really valuable.
> 
> On @andersonfrailey's "There are some units who will go from positive
> benefits to no benefits and vice versa," is the problem welfare cliffs? For
> example someone right below the Medicaid income limit could lose $10k in
> benefits for earning a marginal dollar, making for a 1M% MTR. IIUC Medicaid
> MTRs will be zero elsewhere on the income distribution.

In taxsim I normally calculate MTRs by adding a penny to the income or 
deduction amount, to minimize the chance of hitting a notch. Actually, I 
add and subtract a penny, then use the lessor of the calculated rates (in 
absolute value). Atempting to amortize the notch over larger ranges has to 
be done separately for each notch. I smooth most of the step functions 
with linear interpolation, but a notch without a statutory upper and lower 
limit is hard to smooth - there is no natural size for the finite 
difference.

dan

**Comment by martinholmer** [comment]
@MaxGhenis said:
> I'd find benefit MTRs really valuable.

Can you explain how you would use them in your analysis?  Why, exactly, would they be valuable?

**Comment by MaxGhenis** [comment]
I'd like to show how replacing benefit programs with various negative income tax schemes affects total (implicit) MTRs. My hypothesis is that a NIT would improve work incentives with more consistent and often lower MTRs.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> I'd like to show how replacing benefit programs with various negative income tax [or UBI] schemes affects total (implicit) MTRs. My hypothesis is that a NIT would improve work incentives with more consistent and often lower MTRs.

Not sure I know what you mean by "implicit".

If I understand you correctly, you want to know for each benefit the benefit reduction rate with respect to a small increase in earnings for each filing unit receiving that benefit.  Is that correct?

@MattHJensen @feenberg @Amy-Xu @andersonfrailey

**Comment by MaxGhenis** [comment]
> If I understand you correctly, you want to know for each benefit the benefit reduction rate with respect to a small increase in earnings for each filing unit receiving that benefit. Is that correct?

Yes. This is sometimes described as the [implicit MTR](https://en.wikipedia.org/wiki/Tax_rate#Implicit_marginal_tax_rate) to distinguish benefit losses from taxes.

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #1873:
>> If I understand you correctly, you want to know for each benefit the benefit reduction rate with respect to a small increase in earnings for each filing unit receiving that benefit. Is that correct?
>
> Yes. This is sometimes described as the implicit MTR to distinguish benefit losses from taxes.

OK.  Thanks for the clarification.

@MattHJensen @feenberg @Amy-Xu @andersonfrailey

**Comment by jdebacker** [comment]
Closing issue as Tax-Calculator will focus on taxes for foreseeable future.  Those interested in this question my look to CTAM or other work. 

cc @MaxGhenis @nikhilwoodruff
