### ISSUE TITLE
Individualizing EITC removes joint filing phaseout bonus w/o notifying user

### ISSUE THREAD

**Issue by MattHJensen** [PSLmodels/Tax-Calculator#2199]
Setting the `_EITC_indiv` parameter to `True` deactivates the `_EITC_ps_MarriedJ_*kids` parameter, significantly reducing the phaseout start for affected taxpayers. The user is not notified by the `_EITC_indiv` documentation, other than the note, "the phaseout of the credit works slightly differently between the two." 

For context, I estimate that deactivating the phaseout start bonus for joint filers reduces the cost of individualizing the EITC by about $3B in the first year. 

See the two reforms below. The first sets `_EITC_indiv` to True and the second sets `_EITC_indiv` to True **and** raises the `_EITC_ps_MarriedJ_*kids` parameters dramatically. Both have the exact same effects. 

https://www.ospc.org/taxbrain/38925/
https://www.ospc.org/taxbrain/38926/

One fix would be to add documentation to `_EITC_indiv` explaining that it turns off the other parameter. Another fix would be to keep the` _EITC_ps_MarriedJ_*kids` parameters active when `_EITC_indiv` is active (with docs). 

I prefer the latter approach, because I think it is counterintuitive for `EITC_indiv` to automatically reduce the phaseout start for affected taxpayers, but it would break backwards compatibility by redefining `EITC_indiv`. 

Based on how I have observed users approach the individualized EITC option, I think it is best to keep the definition for the individualized EITC quite close to the definition for the current law EITC. Users expect to be able to make `EITC_indiv` `True` without it affecting their other parameter choices. 

Based on this observation, I also think we should add back childless EITC age eligibility rules (which are currently turned off by `EITC_indiv`). 

I do not think we should add back the investment income eligibility rules for now because we don't an investment income breakdown between the joint filers. 

I am happy to make these changes if others think they are reasonable. To summarize the changes that I'm proposing: 

- activate `_EITC_ps_MarriedJ_*kids` when `EITC_indiv` is True
- activate `EITC_*EligAge` when `EITC_indiv` is True
- add documentation to `EITC_indiv` to reflect the above two changes.

**Comment by martinholmer** [comment]
@MattHJensen,  The changes in the logic of individualized-EITC reforms that you propose in issue #2199 seem reasonable.  We look forward to you pull request that implements these changes in logic and documentation.

**Comment by MattHJensen** [comment]
> On further reflection I don't see how this makes sense. If you do this then the individualized EITC will not treat people in the same situation in the same way: a major violation of horizontal equity. Why should a married person be eligible for a bigger individualized EITC benefits than a single person with the same other attributes? Isn't that what your proposed change would do? If users want to analyze a reform that fails on horizontal-equity grounds, they can specify such a reform. But for Tax-Calculator to work that way by default is highly undesirable.

I am working off the principle that Tax-Calculator should do what it says it is doing. Currently, Tax-Calculator can say that it is giving married EITC filers a phaseout bonus, while no giving joint filers a marriage phaseout bonus. In my view this is a bug that we need to fix, but there may be other ways to fix it than what I've proposed.

**Comment by MattHJensen** [comment]
Adding more flesh to what I said earlier:

> I am working off the principle that Tax-Calculator should do what it says it is doing. Currently, Tax-Calculator can say that it is giving married EITC filers a phaseout bonus, while not giving joint filers a marriage phaseout bonus. In my view this is a bug that we need to fix, but there may be other ways to fix it than what I've proposed. 

I agree that it is uncomfortable for a user to click "individualize the EITC" and then perhaps not know that there is a separate marriage bonus under current law, but I think that is just an unfortunate aspect of the complexity of tax law and not allowing parameters to silently overwrite other parameters. 

The benefit of not allowing parameters to silently overwrite others is honesty/trustworthiness as described in my quoted comment, and also because it allows the user to estimate the itemized cost of various provisions of the reform. 

Constructing recipe might be a good solution to this scenario. A "neutralize marriage penalty/bonus in the EITC" recipe would show users how to accomplish that aim, without hijacking the individualize EITC parameter to do more than just individualize the EITC.

**Comment by martinholmer** [comment]
@MattHJensen said:
> I am working off the principle that Tax-Calculator should do what it says it is doing. Currently, Tax-Calculator can say that it is giving married EITC filers a phaseout bonus, while not giving joint filers a marriage phaseout bonus [in the individualized EITC]. In my view this is a bug that we need to fix, but there may be other ways to fix it than what I've proposed.

Something needs fixing, but if would say it's the documentation.  In my view, the individualized EITC is a completely different tax provision that the current filing-unit EITC.   I think each tax analyst that comes to this topic has in their head a different concept of what the indiv-EITC is.  (For example, should an indiv-EITC reform force a married couple to split the number of EITC-eligible kids or not?  I can see valid arguments on both sides of that question.)    We've added to the complication by reusing many of the f-unit-EITC policy parameters for the indiv-EITC.  But many of them don't make sense in an individualized EITC.

It seems to me that what is needed here is better documentation and perhaps more policy parameters to allow flexibility in specifying exactly what an indiv-EITC reform would be.

**Comment by MattHJensen** [comment]
> But many of them don't make sense in an individualized EITC.

@martinholmer, could you point out which parameters you mean? I think this is the source of our disconnect. When I look over the EITC parameters, _all_ of them also make sense in the context of an individualized EITC calculation (including the option to add a marriage bonus), so it is simplest to add an "individualize the eitc" option with a narrow definition, making the changes outlined in this issue. Extra individual-eitc specific parameters can be as requested by users, such as providing flexibility for how the kids are split up or how investment income is allocated. 

An alternative approach would be to have a completely different section of EITC parameters as you outline, but then many parameters and associated logic will need to be duplicated. If you feel strongly this approach is better, I am happy to implement it.

Given that we both think something here needs to be fixed, I am adding a bug label.

**Comment by martinholmer** [comment]
@MattHJensen said:
> When I look over the EITC parameters, all of them also make sense in the context of an individualized EITC calculation (including the option to add a marriage bonus), so it is simplest to add an "individualize the eitc" option with a narrow and precise definition, making the changes outlined in this issue. Extra individual-eitc specific parameters can be added as requested by users, such as providing flexibility for how the kids are split up or how investment income is allocated.
>
> An alternative approach would be to have a completely different section of EITC parameters, as you outline, but then many parameters and associated logic will need to be duplicated. If you feel strongly this approach is better, I am happy to implement it. I do see how it is awkward for the marriage bonus to be turned on by default when the user individualizes the EITC, and completely separate parameters would prevent that issue.
>
> Given that we both think something here needs to be fixed, I am adding a bug label.

Yes, I agree there is some kind of bug here.   Having two separate  sets of parameters (one for the current law `EITC` and one for the individualized version of the EITC`iEITC`) seems like too much work even though it would require less documentation.  So, all things considered your approach sounds like the more efficient.  But your approach will require non-trivial code revisions because the the `EITC` logic and the `iEITC` logic are (as best as I can remember) in separate blocks.
