### ISSUE TITLE
Extending beyond 2029

### ISSUE THREAD

**Issue by codykallen** [PSLmodels/Tax-Calculator#2257]
Pull request #2255 updates Tax-Calculator to run through 2029. However, I think it might be useful to extend this even further. The CBO Long-term budget projections from June 2018 includes several applicable forecasts through 2048, including:
 - population growth
 - fertility (children per woman)
 - GDP growth (real and nominal)
 - growth of hours worked
 - earning share of compensation
 - fraction of earnings below the FICA taxable maximum
 - inflation
 - Social Security spending

These are presumably not enough to directly forecast each of the series for the growth factors. In the absence of better long-term forecasts, we could perhaps assume that these series grow at a rate tied to the growth of GDP per capita, and move all of imperfectly specified growth factors in tandem in the long-term forecast.

**Comment by martinholmer** [comment]
@codykallen, I've moved your data request to the taxdata repository where it would have to be implemented.
I've cc'ed several people these in hopes to generate a serious discussion.

**Comment by martinholmer** [comment]
Moved issue #2257 to [taxdata issue 310](https://github.com/PSLmodels/taxdata/issues/310).
