### ISSUE TITLE
Is it possible to install taxcalc versions preceding 0.23.0?

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2258]
I'm looking to recreate a previous analysis (I got different results after updating taxcalc), and don't see a way to install taxcalc pre-0.23.0, the first version in the [pslmodels/taxcalc conda file set](https://anaconda.org/pslmodels/taxcalc/files). The [ospc repo](https://anaconda.org/ospc/repo) has nothing in it, and conda won't install from there. Is there another way?

This worked:
```
conda create -n oldtc -c pslmodels taxcalc=0.23.0
```

These didn't:
```
conda create -n oldtc -c ospc taxcalc=0.19.0
conda create -n oldtc -c pslmodels taxcalc=0.19.0
```

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #2258:
> I'm looking to recreate a previous analysis (I got different results after updating `taxcalc`), and don't see a way to install `taxcalc` pre-0.23.0

Which `taxcalc` version are you interested in?  What OS platform are you on?

**Comment by MaxGhenis** [comment]
0.19.0, Linux

**Comment by martinholmer** [comment]
@MaxGhenis,  Why don't you download from GutHub a zip file containing the source code for T-C 0.19.0?

**Comment by MaxGhenis** [comment]
Installing from GitHub worked - here's an [example Google Colab notebook](https://colab.research.google.com/drive/1gCNghtp20grMKDXf0Lwvkxcib0aEbILV) that runs `recipe00` on taxcalc 0.19.0 via `!pip install git+...`. Here's the [equivalent](https://colab.research.google.com/drive/1f5C36bYaLZe5ErzHdT0vhJShdeB4ExHj) using the latest version.

BTW I had initially tried using taxcalc from Colab back in October 2017, but basic functionality failed. Looking back on my email to @MattHJensen from then, I think it was probably that Colab was using a different version of some underlying library like `numpy` (I knew a lot less about Python back then).

Installing via conda is still ideal, but it's cool that taxcalc is usable from Colab, meaning anyone can get started with it without needing to install anything.

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #2258:
> Installing from GitHub worked.
> Here's an example Google Colab notebook that runs recipe00 on taxcalc 0.19.0 via !pip install git+...

Great!  I'm glad this approach worked for you.  It's going to be difficult to keep packages that are almost a year old available on the Anaconda Cloud PSLmodels channel.
