### ISSUE TITLE
CTC appears to phase in more quickly than it did in taxcalc 0.20.0

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2274]
This is going back a while but I wanted to check if I might be missing anything before debugging more: In April 2018 I analyzed the CTC with taxcalc 0.20.0, and one result of [that analysis](https://github.com/MaxGhenis/taxcalc-notebooks/blob/548d9271d950434ae4d07bf2e491b3b8402a15bf/ctc/ctc_ubi.ipynb) was this chart:
![image](https://user-images.githubusercontent.com/6076111/54973961-7080a300-4f4f-11e9-9986-e1e8822d1576.png)

[Re-running the code](https://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/ctc/ctc_ubi.ipynb)--with adjustments to match the current CTC variable names--I get this chart:
![image](https://user-images.githubusercontent.com/6076111/54973998-9ad26080-4f4f-11e9-9a28-3866353ad81e.png)

Notice the phase-in is much steeper today than it was last year.

The full height (2018 law) is based on the difference in after-tax income between current law and a reform which sets `_CTC_c` and `_ACTC_c` (formerly `_DependentCredit_Child_c`) to zero.

I tried to check out the [CTC outputs](https://colab.research.google.com/drive/1SXOmnPib-79v8OqNO_dxrwUJ1QZwEecY) instead of change to tax liability, but while `(c11070 + c07220) / n24` maxes out at 2000 today, it only maxed out at 1400 using taxcalc 0.20.0. So I'd need to do more digging to get an apples-to-apples comparison.

Before I do that though, does it seem correct that the CTC would have such a rapid phase-in today? [This chart](https://www.taxpolicycenter.org/briefing-book/what-child-tax-credit) looks like it phases in over roughly the first quintile, not first 5%.
![image](https://user-images.githubusercontent.com/6076111/54974450-5051e380-4f51-11e9-890a-7481f42bc533.png)

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #2274:
> This is going back a while but I wanted to check if I might be missing anything before debugging more: In April 2018 I analyzed the CTC with taxcalc 0.20.0, ...

[Tax-Calculator 0.20.0](https://github.com/PSLmodels/Tax-Calculator/blob/master/RELEASES.md#2018-05-18-release-0200) was released on May 19, 2018, so  during April 2018 you must have been using an even older release.

With respect to the 2018 Child Tax Credit results you mention in [your comment](https://github.com/PSLmodels/Tax-Calculator/issues/2274#issue-425240538), there are many reasons why they are now different using the current version of Tax-Calculator.  But the main reason is that before [Tax-Calculator release 1.0.0](https://github.com/PSLmodels/Tax-Calculator/blob/master/RELEASES.md#2019-02-22-release-100) there were bugs in the calculation of the child tax credit in years when TCJA is current-law policy (meaning 2018+).  In addition, the economic projections have changed, which affects the attributes of filing units in 2018.

**Comment by MaxGhenis** [comment]
Thanks @martinholmer. Would you say the pre-1.0.0 CTC bugs could have underestimated the CTC's value for tax units in the ~5th through 20th percentile, as the graphs above suggest?

**Comment by codykallen** [comment]
@MaxGhenis, you reproduce the CTC plots using actual income (preferably AGI) rather than income percentiles? It shouldn't need to go beyond $100,000 or so.

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #2274:
> Would you say the pre-1.0.0 CTC bugs could have underestimated the CTC's value for tax units in the ~5th through 20th percentile, as the graphs above suggest?

Yes, and your original comment in this issue showed that pretty clearly.  You found that when using the earlier release, the maximum CTC in 2018 was only $1400 instead of $2000.  That's what you found using an old release, right?

**Comment by martinholmer** [comment]
@codykallen said in issue #2274:
> [could] you reproduce the CTC plots using actual income (preferably AGI) rather than income percentiles?
> It shouldn't need to go beyond $100,000 or so.

I agree.  If you (@MaxGhenis) want to investigate further, the more sensible approach is to plot/tabulate by AGI.

**Comment by MaxGhenis** [comment]
>You found that when using the earlier release, the maximum CTC in 2018 was only $1400 instead of $2000 per child.

That's the case when calculating as `(c11070 + c07220) / n24` (see [this notebook](https://colab.research.google.com/drive/1SXOmnPib-79v8OqNO_dxrwUJ1QZwEecY)). In the original analysis I compared after-tax income between a baseline and a CTC repeal reform, and that maxed out at $2,000.

I can do the reform again and slice by AGI, but I'm curious if there's a total CTC amount in the outputs today and/or pre-1.0. Using v 1.2.0, over 3,000 tax units have `(c11070 + c07220) / n24` exceeding $2,000 (maximum is $2,624). `c07220/n24` maxes out at $2,000, and `c11070/n24` maxes out at $1,400, but there are records that have both `c11070>c07220` and `c11070<c07220`, so I'm not clear on how these overlap or which one would be considered the full CTC. [This notebook](https://colab.research.google.com/drive/1wzajRCVdbl12GX03jxSsIAz5P1y1vl2f) shows these calculations and example records. Could you help me understand these variables?

The [documentation](http://pslmodels.github.io/Tax-Calculator/) describes them as:
>Output Variable Name: c07220
Description: Child tax credit (adjusted) from Form 8812
Output Variable Name: c11070
Description: Child tax credit (refunded) from Form 8812

**Comment by codykallen** [comment]
@MaxGhenis asked about the CTC and how it is divided between `c11070` and `c07220`. Officially (in tax law), the CTC is a nonrefundable credit. Thus the "official" CTC amount is the nonrefunded credit, meaning the portion used to offset positive tax liability. This shows up as `c11070`.

In reality, the CTC is a partially refundable credit. This refund mechanism works through the Additional CTC (ACTC), which provides a credit based on the difference between the maximum CTC amount and the portion of the CTC used to offset positive tax liability, as well as income in excess of $2500 (pre-TCJA, $3000). This refunded portion is stored as `c07220`. 

When people measure the impact of the CTC, the measure of interest is `c11070 + c07220`. In previous versions of Tax-Calculator, you also had to use a function of the dependent credit, but that's no longer relevant in the current version. 

@MaxGhenis mentioned that over 3000 tax units have `(c11070 + c07220) / n24 > 2000`. That is the correct measure for average CTC per child, and it should never exceed `_CTC_c` ($2000). If this is actually occuring, then it constitutes a serious flaw in the logic in Tax-Calculator.

**Comment by martinholmer** [comment]
@MaxGhenis, given that we are discussing 2018 `(c07220+c11070)/n24` values above $2000 in issue #2277, it would seem as if we can close issue #2274, which originally focused on why CTC values in an old version of Tax-Calculator were different then those generated by the current version.  If you want to continue the discussion of that topic in this issue, I'll be happy to reopen it.

**Comment by MaxGhenis** [comment]
After some more digging, I think this has to do with the income distribution of tax units with CTC-eligible children (`n24>0`). Here are some clues:
* The average CTC per n24 by income group is similar between the [old](https://colab.research.google.com/drive/1SXOmnPib-79v8OqNO_dxrwUJ1QZwEecY#scrollTo=FsLmJEBbPUbe) and [current](https://colab.research.google.com/drive/1wzajRCVdbl12GX03jxSsIAz5P1y1vl2f#scrollTo=DGDPb5XJRn6E) versions of taxcalc, both in slicing by AGI or by aftertax_income, and with or without abolishing the ODC from both baseline and reform.
* The total CTC budgetary impact fell from $118B in the [old version](https://github.com/MaxGhenis/taxcalc-notebooks/blob/548d9271d950434ae4d07bf2e491b3b8402a15bf/ctc/ctc_ubi.ipynb) to $109B in the [new](https://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/ctc/ctc_ubi.ipynb).
* This stems from total n24 falling from 80M to 67M, but in https://github.com/PSLmodels/taxdata/issues/171 I showed that the current value of `n24` is much closer to Census projections than it was previously (Census projects 69-70M 0- to 16-year-olds in 2018).
* The (weighted) median `aftertax_income` among tax units where `n24>0` fell from $93k in the old version to $62k in the current.

Based on all this, I think what happened is that the previous version of taxcalc had a few million more high-income tax units with CTC-eligible children than the current version does, and may have had a generally different income distribution of tax units with CTC-eligible children. Since the chart in question had income percentiles of tax units with CTC-eligible children on its x-axis, the different income distribution skewed these charts.

I'll remake this chart with absolute income on the x-axis rather than percentiles to check this. A good lesson for me to include absolute income versions of charts to cross-reference, even if relative ones can be useful.
