### ISSUE TITLE
Expanding education tax incentive modeling

### ISSUE THREAD

**Issue by andersonfrailey** [PSLmodels/Tax-Calculator#2293]
I received the following question from a TaxBrain user on Friday of last week:

>I am looking to model the impact of increasing education tax incentives such as the student loan interest deduction and education tax credits rather than modeling "haircuts" for these tax items. Is this possible to do with the TaxBrain calculator or can this feature be considered at some point?

My understanding is that this user would be able to effectively increase the education tax credit by increasing the value of `_ETC_pe_Single` and `_ETC_pe_Married`, but otherwise you're limited to haircuts.

I'd imagine that adding a parameter for the cap on student loan interest you're allowed to deduct would be relatively straight forward, but in the data (the PUF, at least. I'll need to double check the CPS) these variables would all be capped at 2011 levels and then extrapolated. So the student loan amounts in the data might not be truly reflective of what individual tax units would be deducting under higher limits.

I'd be curious to hear other's responses to the user's question.

**Comment by MaxGhenis** [comment]
Imputing student loans from [SCF](https://www.federalreserve.gov/apps/scfcb/) could be one (more intensive) option.
![image](https://user-images.githubusercontent.com/6076111/55747299-c8f47d80-59f0-11e9-964a-0e34a58a434f.png)

**Comment by martinholmer** [comment]
@andersonfrailey said in T-C issue #2293:
> I'd imagine that adding a parameter for the cap on student loan interest you're allowed to deduct would be relatively straight forward, but in the data (the PUF, at least. I'll need to double check the CPS) these variables would all be capped at 2011 levels and then extrapolated. So the student loan amounts in the data might not be truly reflective of what individual tax units would be deducting under higher limits.

I'm confused by this statement.  Are you saying that the `e03210` amounts in the PUF and CPS data have somehow been limited or reduced below the true amount of student loan interest paid?  If so, can you explain how the limitation works.

**Comment by andersonfrailey** [comment]
@martinholmer asked:
>Are you saying that the e03210 amounts in the PUF and CPS data have somehow been limited or reduced below the true amount of student loan interest paid? If so, can you explain how the limitation works?

In 2011, the student loan interest deduction was capped at $2,500 (chapter 4 of [this doc](https://www.irs.gov/pub/irs-prior/p970--2011.pdf)). So in the PUF the maximum value for student loan interest deduction (`e03210`) is $2,500, even if an individual actually paid more than that in student loan interest. I'm not sure how often this would be the case, but it's something to keep in mind.

I also don't know if this is the case in the CPS. I still need to check on that.

**Comment by martinholmer** [comment]
@andersonfrailey,  Thanks for the explanation about how `e03210` is capped in the 2011 PUF data.  And the the deducted amount would be zero for those with modified AGI above the threshold.  So, the PUF data cannot support liberalizations in the tax treatment of student loan interest payments.

**Comment by martinholmer** [comment]
@andersonfrailey,  Does the person making the request in issue #2293 understand the data problems that prevent adding a policy parameter for the cap on student loan interest deductions?  I that person willing to submit a taxdata pull request that remedies that data problem?  If not, then do you want to do some kind of imputation of amounts above $2500 (in the 2011 PUF)?   If the answer to all these questions is "no", then is there any purpose served in leaving this issue open?

**Comment by andersonfrailey** [comment]
@martinholmer, I pointed him to this issue to watch the discussion, but I haven't heard from him since then. I'll reach out and explain the data issues. I don't have the bandwidth to work on imputing amounts above $2,500 at the moment. Given that the constraint on this request is in the data, I'll open an issue is TaxData and see if anyone picks up the mantel.

In the meantime, I think this can be closed.

**Comment by martinholmer** [comment]
@andersonfrailey said in issue #2293:
> I pointed him to this issue to watch the discussion, but I haven't heard from him since then. I'll reach out and explain the data issues. I don't have the bandwidth to work on imputing amounts above $2,500 at the moment. Given that the constraint on this request is in the data, I'll open an issue is TaxData and see if anyone picks up the mantel.
>
> In the meantime, I think this can be closed.

Sound very sensible, thanks.  I was surprised and very pleased that we had a high-quality "spontaneous" resolution of Tax-Calculator issue #2237 via pull request #2266.  Maybe something like that will happen with this taxdata issue.
