### ISSUE TITLE
_CTC_c_under5_bonus isn't implemented

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2295]
The parameter `_CTC_c_under5_bonus` is [documented](http://pslmodels.github.io/Tax-Calculator/) as:
>The maximum amount of child tax credit allowed for each child is increased by this amount for qualifying children under 5 years old.

But modifying it in TaxBrain  https://apps.ospc.org/taxbrain/40725 shows no change to any tax units' tax liability.

[Searching for it](https://github.com/PSLmodels/Tax-Calculator/search?q=_CTC_c_under5_bonus&unscoped_q=_CTC_c_under5_bonus) in the Tax-Calculator repo shows no Python results.

I think it has yet to be implemented.

**Comment by martinholmer** [comment]
@MaxGhenis said in issue #2295:
> The parameter `_CTC_c_under5_bonus` is [documented](http://pslmodels.github.io/Tax-Calculator/) as:
>>The maximum amount of child tax credit allowed for each child is increased by this amount for qualifying children under 5 years old.
>
>But modifying it in TaxBrain  https://apps.ospc.org/taxbrain/40725 shows no change to any tax units' tax liability.
>
> [Searching for it](https://github.com/PSLmodels/Tax-Calculator/search?q=_CTC_c_under5_bonus&unscoped_q=_CTC_c_under5_bonus) in the Tax-Calculator repo shows no Python results.
>
> I think it has yet to be implemented.

@MaxGhenis, if you had actually looked at what TaxBrain showed you, you would have seen that you made a mistake in specifying your reform.  As you can see in this screenshot, your reform did not use the `_CTC_c_under5_bonus` policy parameter.

<img width="1089" alt="Screen Shot 2019-04-11 at 6 29 52 AM" src="https://user-images.githubusercontent.com/12170745/55950984-2c1a2600-5c24-11e9-8826-cf1aa49a0151.png">

Also, you need to be using a better search tool.  Here is what I get when I search all the Python files in the Tax-Calculator/taxcalc dirctory:
```
iMac:taxcalc mrh$ grep CTC_c_under5_bonus *py
calcfunctions.py:                      CTC_c_under5_bonus, nu05,
calcfunctions.py:    line1 = CTC_c * n24 + CTC_c_under5_bonus * nu05
iMac:taxcalc mrh$ 
```
So, as you can clearly see, the CTC_c_under5_bonus amount is added to the current-law line 1.

**Comment by MaxGhenis** [comment]
Thanks @martinholmer, I hit two issues here:
1. I searched GitHub for `_CTC_c_under5_bonus` with the leading underscore. Searching instead for [`CTC_c_under5_bonus`](https://github.com/PSLmodels/Tax-Calculator/search?q=CTC_c_under5_bonus&unscoped_q=CTC_c_under5_bonus) yields the correct result in calcfunctions.py.
2. I mistakenly entered 1000 for the "new" CTC rather than the existing one, and since I didn't have a phase-in rate for the new one it was never applied. Entering for the current CTC gives the expected result: https://apps.ospc.org/taxbrain/40738
