### ISSUE TITLE
Add parameter for "filling in" EITC for low-income students and caregivers

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2305]
Cory Booker just released the Rise Act, which is his name for the [Cost of Living Refund](http://costoflivingrefund.org) from Economic Security Project Action. This is more or less a standard EITC reform, but also "fills in" the left side for low-income students and caregivers. Per [these slides](https://static1.squarespace.com/static/5acbc4bd0dbda3fb2fce2ab3/t/5cacc4a8e5a50500011a8720/1554826520871/cost-of-living_refund_fed_policy_details.pdf), these conditions are defined as "Pell Grant (or meet similar criteria [?])" and having "children under 6 or elderly/disabled dependents," respectively.

These groups are represented by the dotted lines here:
![image](https://user-images.githubusercontent.com/6076111/56252482-d357ec80-606c-11e9-90ae-1bff950c9459.png)

[These slides](https://static1.squarespace.com/static/5acbc4bd0dbda3fb2fce2ab3/t/5c82a81e8165f5e7219e8e1b/1552066590862/side-by-side_fed_legis.pdf) also indicated that Brown and Khanna's Cost of Living Refund Act of 2019 also includes students and caregivers, and Harris's LIFT Act includes students.

Modeling this would involve taxdata changes to pull in a Pell Grant flag from CPS, which look like they might be roughly represented by some of these [ASEC fields](https://www2.census.gov/programs-surveys/cps/techdocs/cpsmar18.pdf):
![image](https://user-images.githubusercontent.com/6076111/56252761-40b84d00-606e-11e9-8871-7878026a5a28.png)

Since it varies between LIFT and the others, maybe these could be two separate boolean parameters on whether to fill in students and whether to fill in caregivers.

**Comment by martinholmer** [comment]
@MaxGhenis, It sounds like all these enhancements (even if we thought they were worth the effort) require new data, right?  If so, you should raise this issue in taxdata.  Tax-Calculator can't do anything without the data.

**Comment by MaxGhenis** [comment]
Filed https://github.com/PSLmodels/taxdata/issues/312 for the student piece, though I don't think it's likely to affect these reforms much, and it seems difficult, so I wouldn't consider it a priority.

The caregiver piece intuitively seems like it'd have a bigger impact, and it doesn't require new data.

**Comment by martinholmer** [comment]
@MaxGhenis said in Tax-Calculator issue #2306:
> Filed PSLmodels/taxdata#312 for the student piece, though I don't think it's likely to affect these reforms much, and it seems difficult, so I wouldn't consider it a priority.
>
> The caregiver piece intuitively seems like it'd have a bigger impact, and it doesn't require new data.

So, just for filing units with kids under six years of age, the reform (per the [graph](https://github.com/PSLmodels/Tax-Calculator/issues/2305#issue-434041990) you posted above) is this:
```
{'EITC_basic_frac': {2020: 1.0}}
```
Is that correct?  
Is the reform just having `EITC_basic_frac` be equal to one for those with a kid under six and be equal to zero (as in current-law policy) for all other filing units?  
Can you point us to the text in the reform proposals that say that?

**Comment by Thirdhuman** [comment]
The Rise Credit is unconventionally structured [(Source)](https://static1.squarespace.com/static/5acbc4bd0dbda3fb2fce2ab3/t/5cacc4a8e5a50500011a8720/1554826520871/cost-of-living_refund_fed_policy_details.pdf):
	• Family caregivers (children under 6 or elderly/disabled dependents): 
		- Single people would receive a maximum credit of $4,000. 
		- Married couples would receive a maximum credit of $8,000. 

Unlike the CTC, the credit does not vary with the number of children.  Rather, each parent with at least one child under the age of six effectively receives a fixed credit of $4000 below the phaseout range.

**Comment by martinholmer** [comment]
@Thirdhuman said in issue #2305:
> The Rise Credit is unconventionally structured ([Source](https://static1.squarespace.com/static/5acbc4bd0dbda3fb2fce2ab3/t/5cacc4a8e5a50500011a8720/1554826520871/cost-of-living_refund_fed_policy_details.pdf)):
>• Family caregivers (children under 6 or elderly/disabled dependents):
>- Single people would receive a maximum credit of $4,000.
>- Married couples would receive a maximum credit of $8,000.
>
> Unlike the CTC, the credit does not vary with the number of children. Rather, each parent with at least one child under the age of six effectively receives a fixed credit of $4000 below the phaseout range.

I'm confused about several things:
1. What's the "Rise Credit"?   The source you point to describes a "Cost of Living Refund".
2. "Unlike the CTC"  Don't you mean "Unlike the EITC"?

I don't see how this reform can be characterized using existing Tax-Calculator parameters.
If I'm wrong about that, could somebody who is interested in this reform show how it can be specified using existing policy parameters.

**Comment by Thirdhuman** [comment]
1. The Rise Credit is Booker's EITC reform, which appears to be a rebranded version of ESP's" "Cost of Living Refund".
2. The way the credit treats children is unlike both the EITC and the CTC.

From my understanding, the best way to account for this credit in the existing model would be an ex post adjustment to the model output based on matching to CPS characteristics.

**Comment by martinholmer** [comment]
@Thirdhuman said in issue #2305 about how to implement a refundable credit like the "Cost-of-Living Refund":
> From my understanding, the best way to account for this credit in the existing model would be an ex post adjustment to the model output based on matching to CPS characteristics.

My understanding is that you can take that approach using output from the current version of Tax-Calculator.

**Comment by martinholmer** [comment]
@MaxGhenis said (with emphasis added) when raising issue #2305:
> Cory Booker just released the Rise Act, which is his name for the Cost of Living Refund from Economic Security Project Action. This is **more or less a standard EITC reform**, but also "fills in" the left side for low-income students and caregivers.

@MaxGhenis, you need to guard against making careless comments.  The Cost of Living Refund proposal is nowhere close to a "standard EITC reform" as the subsequent discussion in #2305 made clear.

**Comment by martinholmer** [comment]
@Thirdhuman, can see a way to analyze the Cost of Living Refund proposal using Tax-Calculator output and the #2305 discussion has determined that the Cost of Living Refund is a tax reform proposal that cannot be specified using existing Tax-Calculator policy parameters.

So, people interested in analyzing the Cost of Living Refund (COLR) proposal, and others like it, have two choices:
1.  Analyze it in a custom program that processes Tax-Calculator output, or
2. Prepare a pull request (following the [contributor guide](https://github.com/PSLmodels/Tax-Calculator/blob/master/CONTRIBUTING.md#tax-calculator-contributor-guide)) that does the following:
     a. adds new policy parameters that can characterize the COLR proposal (and others like it)
     b. adds new logic that uses the new parameters to compute the new refundable credit amount
     c. adds a JSON reform file specifying the COLR proposal
