### ISSUE TITLE
Condition-based Credit

### ISSUE THREAD

**Issue by Thirdhuman** [PSLmodels/Tax-Calculator#2308]
Including something like a "condition based tax credit", which assigns credits in a "Yes/No" fashion based on a chosen CPS variables seems like a worthy addition for improving the flexibility of Tax Calc in policy analyses.  

For example, children under 6 (or 5) or caregivers, students, or any other parameter could be marked by the researcher.  The values in the cells of this column could be based on any combination of custom conditions that a researcher wants adds to the survey, and then renames to be read in as a parameter to model. 

Including multiple of these condition-based input parameters (2 or 3) for credits would even further improve the model's flexibility.  This change would enable Tax Calc to be better used for analyzing unconventional policy designs.

**Comment by martinholmer** [comment]
@Thirdhuman,  I don't understand your proposal in issue #2308.  What you describe seems to be a post-Tax-Calculator-simulation of novel policy reforms conducted in a program that you develop.   What role would Tax-Calculator play in this, other that providing you with a detailed output file (like the `tc --dump` output file)?

**Comment by Thirdhuman** [comment]
@martinholmer, if the 27 variables identified in the script below are the only inputs whereby Tax-Calculator's simulations are not simple additions, then I guess nothing.

```
    assert isinstance(ivar, pd.DataFrame)
    invar = pd.DataFrame()
    invar['RECID'] = ivar.loc[:, 1]
    invar['FLPDYR'] = ivar.loc[:, 2]
    # no Tax-Calculator use of TAXSIM variable 3, state code
    mstat = ivar.loc[:, 4]
    assert np.all(np.logical_or(mstat == 1, mstat == 2))
    invar['age_head'] = ivar.loc[:, 5]
    invar['age_spouse'] = ivar.loc[:, 6]
    num_deps = ivar.loc[:, 7]
    mars = np.where(mstat == 1, np.where(num_deps > 0, 4, 1), 2)
    assert np.all(np.logical_or(mars == 1,
                                np.logical_or(mars == 2, mars == 4)))
    invar['MARS'] = mars
    invar['f2441'] = ivar.loc[:, 8]
    invar['n24'] = ivar.loc[:, 9]
    num_eitc_qualified_kids = ivar.loc[:, 10]
    # pylint: disable=assignment-from-no-return
    invar['EIC'] = np.minimum(num_eitc_qualified_kids, 3)
    num_taxpayers = np.where(mars == 2, 2, 1)
    invar['XTOT'] = num_taxpayers + num_deps
    invar['e00200p'] = ivar.loc[:, 11]
    invar['e00200s'] = ivar.loc[:, 12]
    invar['e00200'] = invar['e00200p'] + invar['e00200s']
    invar['e00650'] = ivar.loc[:, 13]
    invar['e00600'] = invar['e00650']
    invar['e00300'] = ivar.loc[:, 14]
    invar['p22250'] = ivar.loc[:, 15]
    invar['p23250'] = ivar.loc[:, 16]
    invar['e02000'] = ivar.loc[:, 17]
    invar['e00800'] = ivar.loc[:, 18]
    invar['e01700'] = ivar.loc[:, 19]
    invar['e01500'] = invar['e01700']
    invar['e02400'] = ivar.loc[:, 20]
    invar['e02300'] = ivar.loc[:, 21]
    # no Tax-Calculator use of TAXSIM variable 22, non-taxable transfers
    # no Tax-Calculator use of TAXSIM variable 23, rent paid
    invar['e18500'] = ivar.loc[:, 24]
    invar['e18400'] = ivar.loc[:, 25]
    invar['e32800'] = ivar.loc[:, 26]
    invar['e19200'] = ivar.loc[:, 27]

```
Am I correct in understanding that the "UBI" and "CTC under 5" parameters are simple transformations conducted after applying the primary simulation?  And are variables such as  "UBI" and "CTC under 5" special exceptions from Tax Calculator's general direction of abstaining from including novel policy reforms?

**Comment by martinholmer** [comment]
@Thirdhuman said in issue #2308:
> if the 27 variables identified in the script below [code from `taxcalc/validation/taxsim/prepare_taxcalc_input.py`] are the only inputs whereby Tax-Calculator's simulations are not simple additions

I have no idea what you mean by "simple additions".  If your starting point is the `taxcalc/validation/taxsim/prepare_taxcalc_input.py` script, then it is as if you opened "War and Peace" in the middle and started reading there; you would be very confused.

Have you started reading at the [beginning](https://github.com/PSLmodels/Tax-Calculator#tax-calculator) of the Tax-Calculator documentation?  If not you should do that.  We're happy to answer questions and consider suggestions for improvements, but we expect those making comments to be reasonable knowledgeable about Tax-Caclualtor.  Have you used the `tc` command-line tool or written your own Python scripts using the `taxcalc` package?

**Comment by Thirdhuman** [comment]
I've messed around with those things, but I'll familiarize myself further before making further suggestions since I'm new to this package and some its functioning remain hazy to me.

**Comment by martinholmer** [comment]
@Thirdhuman said in issue #2308:
> Am I correct in understanding that the "UBI" and "CTC under 5" parameters are simple transformations conducted after applying the primary simulation?

Again, I have no idea what you mean by "simple transformation" .  Those policy parameters are **inputs** to the simulation, as is made perfectly clear in the Tax-Calculator documentation.

**Comment by Thirdhuman** [comment]
Yes, I'm aware of the basic structure.  I need to dig deeper into how the UBI simulation is actually conducted before I can be confident whether my initial suggestion for conditional credits makes sense.  If the UBI simulation is effectively conducted in an ex post manner, then my suggestion does not make sense, since this can be more easily done by the researcher after receiving tax-calc output.
