### ISSUE TITLE
Allow for sizing quantile buckets by population

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2310]
taxcalc currently sizes quantile buckets by the number of tax units; e.g., each decile has an equal number of tax units.

Both [CBO](https://www.cbo.gov/system/files/115th-congress-2017-2018/workingpaper/53345-workingpaper.pdf) and [TPC](https://www.taxpolicycenter.org/resources/tpcs-microsimulation-model-faq) size them by population instead. TPC notes this affects results:
>Quintiles contain equal numbers of people, not equal numbers of tax units. In particular, lower quintiles contain more tax units than higher quintiles because smaller tax units generally have lower income than larger ones and thus are more common in the lower quintiles. For example, our 2018 baseline shows 45.2 million tax units in the lowest quintile, 34.5 million in the middle quintile, and just 24.4 million in the top quintile.

In taxcalc, this would involve creating a variable like `XTOT_s006 = XTOT * s006` and using that for the quantile buckets.

I've noted this difference across tax analysis groups and some others in [this spreadsheet](https://docs.google.com/spreadsheets/d/1I-Qe8uD58bLnPkimc9eaPgs4AE7x5FZYmTZwVX_WyT8/edit#gid=937710743):
![spreadsheet](https://user-images.githubusercontent.com/6076111/56765780-b0a89080-675c-11e9-87dc-4e20934b6711.png)

**Comment by martinholmer** [comment]
Issue #2310 has been resolved by the merge of pull request #2322.
