### ISSUE TITLE
Possible issue in reform modifying AMT exemption in 2013

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/Tax-Calculator#2323]
We (@donboyd5, @feenberg, @MaxGhenis) run several reforms against our synthetic PUF using the tc cli (latest version) to test how the synthetic file does. We run the reforms against 2013 baseline law because 2013 is the Tax-Calculator year that is closest to our data year (2011).

One reform gave surprising results so I ran the same reform against the actual puf. csv and it still gave surprising results. I am not sure there is any problem with Tax-Calculator - we may just not understand the reform properly - but I wanted to raise an alert in case it is a problem.

The reform is a $1,000 reduction in the AMT exemption. The entire reform json looks like this:
{
    "AMT_em": {"2013": [50900.0, 79800.0, 39400.0, 50900.0, 79800.0]}
}

I did not change the phase out start, the phase out rate, the AMT bracket threshold, AMT rate or surcharge, or capital gains/dividends parameters.

The table below shows the number of puf.csv records that had an increase in tax before credits (taxbc), a decrease, or no change:

![image](https://user-images.githubusercontent.com/6538392/57700789-a6293a80-7628-11e9-9282-ecb5c5a77963.png)

We expected many more records to have an increase - we expected many of the records in the phaseout range of the exemption to have a reduction in the exemption, and therefore an increase in AMT, and therefore an increase in taxbc. Thus, the table above is a surprise.

An examination of the details shows:
- AMT taxable income (c62100) actually declined for some records. (As I understand it from looking at tax forms, the AMT exemption is calculated after AMT taxable income, and does not affect AMT taxable income directly.)
- Many records do have an increase in AMT liability (c09600) but do not have an increase in tax before credits. 

I also ran the same reform using TaxBrain (both the OSPC and compmodels versions), which uses an older version of Tax-Calculator, and found that the reform led to a large number of tax increases. This suggests that the tc cli calculation might be incorrect, but certainly doesn't prove it.

I can provide further information, or look more deeply but I wanted to pass this on in case it is a problem.

**Comment by donboyd5** [comment]
Here is some more-informative output from the same run. The rows are Tax-Calculator variable names. The columns are:
- n -- number of records, total
- nup -- number of records that had an increase between base and reform for that variable
- ndown -- number of records with decrease
- nunchanged - number where reform==base for that variable
- next 4 columns are the same, but weighted by s006
- valchange is the weighted change in value -- so:
--- no change in AGI (as expected)
--- c09600 AMT liability increased by $985 million
--- c62100 AMT taxable income decreased by $31.7 million
--- taxbc tax before credits increased by $5.4 million


![image](https://user-images.githubusercontent.com/6538392/57706956-c52dc980-7634-11e9-8a72-04d1b367e3a9.png)

**Comment by donboyd5** [comment]
Oh. If I read documentation correctly, taxbc is before considering AMT. Sorry and embarrassed. Will verify when back at computer.

**Comment by martinholmer** [comment]
In issue #2323, @donboyd5 said:
> Oh. If I read documentation correctly, taxbc is before considering AMT. Sorry and embarrassed. Will verify when back at computer.

No problem and no need to be embarrassed!  
After all, I didn't know that about `taxbc` off the top of my head either.

I can replicate your `taxbc` results and get more reasonable results when looking at `iitax` changes.
```
taxbc counts (>0,<0,=0): 25 1 248565
iitax counts (>0,<0,=0): 13212 346 235033
```

**Comment by martinholmer** [comment]
@donboyd5, if you want to tabulate income tax liability before credits, then this is the variable you want to use:

<img width="1270" alt="Screen Shot 2019-05-14 at 6 43 31 PM" src="https://user-images.githubusercontent.com/12170745/57737094-668a3f00-7678-11e9-8e7c-485f48207893.png">

**Comment by donboyd5** [comment]
Thanks!

Sent by an android
