### ISSUE TITLE
Confirming my understanding on payroll taxes

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2340]
In modeling the elimination of the Social Security payroll tax cap (a component of Andrew Yang's UBI plan), I got some surprising results. I think I understand them at this point but would appreciate confirmation that I'm thinking about this right.

Here's my [notebook](https://nbviewer.jupyter.org/github/MaxGhenis/taxcalc-notebooks/blob/master/exploratory/ss_cap_expanded_income.ipynb), which implements this reform for 2019 CPS data:
```
{'SS_Earnings_c': {2019: 1e+16}}
```
Which yields these changes along some relevant metrics:

|Metric|Change ($B)|
|---|---|
aftertax_income|-88
expanded_income|63
combined|152
iitax|-5
payrolltax|157
ptax_was|127

So my understanding is that payroll taxes increase by $157B, $127B of which comes from wage and salary payroll taxes. Half of that is paid by employers, matching the $63B increase in expanded income, since the employer's share of payroll taxes are counted in expanded income.

Since employees basically bear the employer's share of payroll tax, some analysts might want to count the change in `combined` rather than the change in `aftertax_income`, but in a more static sense and assuming payroll taxes ultimately fund OASDI payments others might want to leave as-is.

Two questions:
1. Am I interpreting this correctly?
2. Do you know the reason for the (small) reduction in `iitax`?

**Comment by martinholmer** [comment]
@MaxGhenis said in T-C issue #2340:
> Here's my notebook, which implements this reform for 2019 CPS data:
>```
>{'SS_Earnings_c': {2019: 1e+16}}
>```
That should work, but there's a T-C convention for eliminating caps: they are raised up to 9e99.
See the reform provision you're implementing in [this documentation file](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/reforms/ptaxes2.json).

After showing some results, @MaxGhenis asked two questions:
> 1. Am I interpreting [these results] correctly?

Yes, what you're saying seems sensible.

> 2. Do you know the reason for the (small) reduction in `iitax`?

There are several ways that your "pop the cap" reform can affect income tax liability.
Your best bet is to use a good text editor that allows you to search for keywords in the `calcfunctions.py` file.
Start by looking at the `EI_PayrollTax` function to see which calculated variables change under your "pop the cap" reform provision, then search below the `EI_PayrollTax` function in the `calcfunctions.py` file for occurrences of each variable that changes.   Doing this will quickly show you elements of total income tax liability that are logically linked to your reform.  If you want to see the size of each component, then simply tabulate each component that changes and you should get a list of changed components that sums up to about $5 billion.
