### ISSUE TITLE
Is there a simple way to remove all deductions and credits?

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2342]
I'm looking to create a reform that eliminates all deductions and credits. Is there a way to do this other than setting all the `*_hc` parameters to 1 and `*_c` parameters to 0?

**Comment by donboyd5** [comment]
Here's how @Anderson Frailey <Anderson.Frailey@aei.org> eliminated all
standard and itemized deductions in "reform4" that we used in synthetic
data analysis:

        "STD": {"2013": [0, 0, 0, 0, 0]},
        "ID_c": {"2013": [0, 0, 0, 0, 0]},

I don't know if there is something similar for credits.

Don

**Comment by martinholmer** [comment]
@donboyd5 said in Tax-Calculator issue #2342:
> Here's how @andersonfrailey  eliminated all standard and itemized deductions in "reform4" that we used in synthetic data analysis:
>```
>        "STD": {"2013": [0, 0, 0, 0, 0]},
>        "ID_c": {"2013": [0, 0, 0, 0, 0]},
>```
> I don't know if there is something similar for credits.

in response to this question by @MaxGhenis:
> I'm looking to create a reform that eliminates all deductions and credits. Is there a way to do this other than setting all the *_hc parameters to 1 and *_c parameters to 0?

There are a host of "above the line" deductions (often prefaced by `ALD_`) that are not turned off by the JSON fragment above.  There is no way to turn off all credits (EITC, child and dependent tax credit, Schedule R credit, etc.) with just one policy parameter.

**Comment by MaxGhenis** [comment]
Thanks @donboyd5 and @martinholmer.
