### ISSUE TITLE
Why is ACTC_c capped at CTC_c value?

### ISSUE THREAD

**Issue by andersonfrailey** [PSLmodels/Tax-Calculator#2344]
Currently, the maximum value for `ACTC_c` is set to be equal to `CTC_c`. What is the reason for this? I tried searching through the PR's and issues as well as the history of `policy_current_law.json` but wasn't able to track down an answer. Thanks in advance for the help.

**Comment by martinholmer** [comment]
@andersonfrailey asked in T-C issue #2344:
> [T]he maximum value for `ACTC_c` is set to be equal to `CTC_c`. What is the reason for this? 

Because the additional CTC (that is, the ACTC) is the part of the CTC that is refundable.  
So, the part cannot be larger than the whole.  Does that make sense?

**Comment by andersonfrailey** [comment]
Thanks for the response @martinholmer. This answers my question. Closing.
