### ISSUE TITLE
Modeling the Neal Economic Mobility Act

### ISSUE THREAD

**Issue by derrickchoe** [PSLmodels/Tax-Calculator#2361]
Hi all,

@erinmelly and I are working on a tax-calculator project that involves modeling the recent [Economic Mobility Act](https://waysandmeans.house.gov/media-center/press-releases/neal-introduces-pro-worker-pro-family-tax-relief-legislation) introduced by Chairman Neal. For those who aren't familiar, the details of the bill can be found [here](https://waysandmeans.house.gov/sites/democrats.waysandmeans.house.gov/files/documents/Economic%20Mobility%20Act%20of%202019%20Section-By-Section.pdf). I understand that @evtedeschi3 and others have done analysis on this legislation and I'd like to confirm that I'm setting up the relevant parameters correctly. I'm structuring my reform as follows (currently focusing only on years 2019 and 2020):

```
reform4= {
#     EITC expansion
    'EITC_MaxEligAge': {2019: 66},
    'EITC_MinEligAge': {2019: 19},
    'EITC_prt': {2019: [0.1530, 0.1598, 0.2106, 0.2106]},
    'EITC_rt': {2019: [0.1530, 0.3400, 0.4000, 0.4500]},
    'EITC_ps': {2019: [11310.0, 19077.98, 19077.98, 19077.98]},
    'EITC_c': {2019: [1464, 3538.53, 5844.04, 6575.05]}, 
    'EITC_sep_filers_elig': {2019: True},
    'EITC_InvestIncome_c': {2018: 9e99},
#     CTC and dependent care expansion
    'ACTC_c': {2019: 2000, 2026: 1000},
    'CDCC_ps': {2019: 120000},
    'CDCC_crt': {2019: 50}
}
```

When looking at the resulting difference table (in 2020, compared with current law), I'm having trouble matching results like by @evtedeschi3 (relevant [twitter post](https://twitter.com/ernietedeschi/status/1141429348207144962)):
![image](https://user-images.githubusercontent.com/32269181/60616868-754fc100-9da0-11e9-935e-736b7a60a88e.png)

As a result, I'm inclined to think that I am missing something. Maybe I should be making additional changes to my local repository (making the CDCC refundable comes to mind)? Any input is much appreciated-- thanks everyone!

@martinholmer @MattHJensen @andersonfrailey @Peter-Metz @hdoupe

**Comment by evtedeschi3** [comment]
The Economic Mobility Act makes the CDCC fully refundable as well as changing some of the underlying parameters. See page 15 of the JCT description here:

https://www.jct.gov/publications.html?func=startdown&id=5197

Since I did not see a way to shift to full CDCC refundability with existing Tax-Calculator parameters, here was my strategy:

1. Eliminate the CDCC entirely within Tax-Calculator using the following code in the policy JSON file:

```
    "CDCC_c": {"2019": 0}
```

2. Run the Economic Mobility Act policy file through the CLI with the `-- dump` option.

3. Calculate the proper impact of CDCC refundability directly in the dumped CSV file and add the effect into after-tax income. Here's my Stata code:

```
ren aftertax_income ati1

* newdepc captures the value of the refundable CDCC under the Neal bill
gen newdepc = 0
replace newdepc = .5*min(e32800, 6000) if f2441 == 1 & c00100 <= 120000
replace newdepc = .5*min(e32800, 12000) if f2441 > 1 & c00100 <= 120000
replace newdepc = max(.2, .5 - (.01*((c00100 - 120000)/2000)))*min(e32800, 6000) if f2441 == 1 & c00100 > 120000
replace newdepc = max(.2, .5 - (.01*((c00100 - 120000)/2000)))*min(e32800, 12000) if f2441 > 1 & c00100 > 120000

replace ati1 = ati1 + newdepc
```

**Comment by derrickchoe** [comment]
@evtedeschi3 

Thanks so much for the quick response-- your strategy makes a lot of sense to me. I'd be interested in seeing if I can replicate the results through making the CDCC refundable through my local taxcalc package. I'll probably have time to do so on Friday. 

One note, and maybe the others can also weigh in on this. If you are using the IRS public use file: is it the case that the variable e32800 is capped at $3,000 (or whatever the previous ceiling was)? I wonder if any analyses using the IRS file understate the effects of the CDCC expansion because filers simply can't report child care expenses higher than the previous topcoded value. I just haven't done my due diligence in checking this-- will do this too once I revisit the code in a few days.

Many thanks for your input! Hope you have a good one.

**Comment by evtedeschi3** [comment]
@derrickchoe asked
> If you are using the IRS public use file: is it the case that the variable e32800 is capped at $3,000

Here's what I see in my CLI dump file for 2020 using the PUF:

![image](https://user-images.githubusercontent.com/3980178/60640114-6d147780-9dda-11e9-9d03-46c8c9d0fe95.png)

**Comment by martinholmer** [comment]
In [this issue 2361 comment](https://github.com/PSLmodels/Tax-Calculator/issues/2361#issuecomment-508295679), @evtedeschi3 explains how he simulated a fully refundable CDCC, which is a reform that cannot by simulated using existing Tax-Calculator policy parameters.  His approach involves using the `tc` command-line tool and post-processing its `--dump` output in Stata.

If you are writing a Python script that imports the `taxcalc` package, you have another option: modify recipe 6 in the [Python Cookbook](https://pslmodels.github.io/Tax-Calculator/cookbook.html) so that the customized Calculator class has the ability to simulate a fully refundable CDCC.  This approach allows you to handle inflation-indexed policy parameters if required.

@derrickchoe @erinmelly @evtedeschi3 @MattHJensen @andersonfrailey @Peter-Metz

**Comment by martinholmer** [comment]
In [this issue 2361 comment](https://github.com/PSLmodels/Tax-Calculator/issues/2361#issuecomment-508504514) @martinholmer outlined a second option for modeling a refundable CDCC.

Just to be clear, if all you want is the aggregate revenue and after-tax income impact of the refundable CDCC, then @evtedeschi3's approach is the easier of the two approaches.  But if you want, for example, accurate marginal tax rates (that could support behavioral-response analysis), then the customized-Calculator approach might be worth the extra effort.

You have choices about how to analyze reforms that cannot be fully characterized by existing Tax-Calculator policy parameters.

@derrickchoe @erinmelly @MattHJensen @andersonfrailey @Peter-Metz

**Comment by derrickchoe** [comment]
@martinholmer 
Thank you for pointing me to recipe 6 in the cookbook; I haven't kept up to date with tax calculator's methods over the past months, and it looks like creating a custom calculator object would achieve my intended goal of creating a modified refundable CDCC. If you don't mind, I'd also really appreciate getting your thoughts on the following.

In response to @evtedeschi3's analysis of the dependent care variable:
![image](https://user-images.githubusercontent.com/32269181/60736550-60506a80-9f25-11e9-8c93-e7f67f6d5859.png)

I see here that the maximum credit amount is ~$8,000. Could this simply be the inflation-adjusted maximum of $6,000 in the 2011 PUF (for cases with multiple dependents)? In any case, it seems that taxcalc would fail to fully capture the effects of expanding the child and dependent care credit to a level such as $12,000 as in the Neal Act. I may be missing something though.

Thank you all for your valuable input!

**Comment by martinholmer** [comment]
@derrickchoe asked in T-C issue #2361:
> I see ... that the maximum credit amount is ~$8,000 [in @evtedeschi3's Stata tabulation of 2020 `tc --dump` output]. Could this simply be the inflation-adjusted maximum of $6,000 in the 2011 PUF (for cases with multiple dependents)? In any case, it seems that taxcalc would fail to fully capture the effects of expanding the child and dependent care credit to a level such as $12,000 as in the Neal Act. I may be missing something though.

No, I don't think you are missing anything.   A simple tabulation of the raw `puf.csv` file would confirm your hunch that the maximum `e32800` value in 2011 is $6,000.   Here is an example of such a tabulation:
```
iMac:Tax-Calculator mrh$ cat tab.py
import pandas as pd
pufdf = pd.read_csv('puf.csv')
print(pufdf.e32800.describe())

iMac:Tax-Calculator mrh$ python tab.py 
count    248591.000000
mean        118.575580
std         672.426197
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max        6000.000000
Name: e32800, dtype: float64
```

@erinmelly @MattHJensen @andersonfrailey @Peter-Metz

**Comment by martinholmer** [comment]
@derrickchoe,  On Monday I leave on a vacation that will last through July.
So, if you have any Tax-Calculator questions, please direct them to @MattHJensen.

**Comment by derrickchoe** [comment]
@martinholmer 

In response to:

> On Monday I leave on a vacation that will last through July.
So, if you have any Tax-Calculator questions, please direct them to @MattHJensen.

Understood-- hope you have a great trip! I'll be working on this sporadically and will make sure to contact Matt with questions.

In response to:

> No, I don't think you are missing anything. A simple tabulation of the raw puf.csv file would confirm your hunch that the maximum e32800 value in 2011 is $6,000.

Thanks-- I wasn't sure if the PUF was topcoded as per the f2441 form. Much appreciated!

**Comment by erinmelly** [comment]
Hi all, Sorry I'm late to the game in responding to this thread. I want to confirm my understanding of this discussion-- we can make the CDCC refundable for its present value, but raising the maximum amount manually, such as it seems to be done in the following lines of code, seems problematic:
`replace newdepc = .5*min(e32800, 6000) if f2441 == 1 & c00100 <= 120000`
`replace newdepc = .5*min(e32800, 12000) if f2441 > 1 & c00100 <= 120000` 

Based on the observation of @derrickchoe  and confirmation by @martinholmer on the matter of the capped value of `e32800`, increasing the maximum credit amount is not capturing the intended effect of this reform. Filers are instructed not to write more than 3,000 of childcare expenses as per the instructions of [Form 2441 line 3](https://www.irs.gov/pub/irs-pdf/f2441.pdf), limiting the PUF data by creating a ceiling for this value. For filers that record expenses below this maximum, there is no issue (they are unaffected by a cap increase). However, it is probable that some filers that recorded 3,000 of expenses in 2011 (6,000 for two or more children) had higher expenses in reality, and given the opportunity to do so, they would have recorded a higher value for `e32800`.

Therefore, when we increase the maximum to 6,000 per child, it is really only accounting for the allowance of indexing `CDCC_c` for inflation- we are not actually capturing the effect of individuals recording  higher childcare expenses. We have no way of knowing the counterfactual of what people would have written for their childcare expenses had they not been limited to a 3,000/child cap on their 2011 returns.

Please correct me if this logic is incorrect!

**Comment by MattHJensen** [comment]
@erinmelly, that confirms my understanding. @derrickchoe, everything seem right to you? 

Note that you can see the $3000 limit documented [here](https://pslmodels.github.io/Tax-Calculator/uguide.html#Nonrefundable%20Credits%20%E2%80%94%20Child%20And%20Dependent%20Care) and in the code base, [here](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/policy_current_law.json#L4728).

**Comment by ernietedeschi** [comment]
Thanks @erinmelly, that makes perfect sense.

So essentially, the only way forward would be to explicitly impute dependent care expenses for tax units above the top code?

**Comment by MattHJensen** [comment]
> So essentially, the only way forward would be to explicitly impute dependent care expenses for tax units above the top codes?

That's my understanding. 

----

Child Aware of America produces a report that offers state averages that could be used to do something very rough. 

@andersonfrailey worked on something like this in #976, but I don't remember why the PR was closed and not merged.

**Comment by martinholmer** [comment]
@ernietedeschi said in Tax-Calculator issue #2361:
> So essentially, the only way forward would be to explicitly impute dependent care expenses for tax units above the top codes?

Yes that is correct.  I've opened [taxdata issue 325](https://github.com/PSLmodels/taxdata/issues/325) that requests this imputation work.

**Comment by jdebacker** [comment]
Closing this issue now as Tax-Calculator now parameterizes refundable CDCC and issues of data imputations are noted in [taxdata Issue #325](https://github.com/PSLmodels/taxdata/issues/325).
