### ISSUE TITLE
Request for tc dump flexibility

### ISSUE THREAD

**Issue by MattHJensen** [PSLmodels/Tax-Calculator#2375]
From an email: 

> As far as I can tell, when Tax-Calculator produces an output (dump) file, the only input variable it will return that is not needed in Tax-Calculator is a variable called RECID.
> 
> I think the rationale for this is explained in the user guide: "Since Tax-Calculator ignores variables in the input file that are not in the Input Variables section, the dump output file in example (2) can be used as an input file and it will produce exactly the same tax liabilities (apart from rounding errors of one or two cents) as in the original dump output." In other words, you cannot specify variables to include in the dump if they are not in the input variables needed by Tax-Calculator.
> 
> My stacked files have an ftype (file type) identifier that identifies what a record is (original PUF record, CART synthetic record, RF synthetic record) and also a RECID variable that is unique within the file segment but not unique within the file. I can merge any two files that have ftype and RECID but cannot necessarily merge a file that only has RECID. 
> 
> Tax-Calculator will not return ftype - it will only return RECID. Thus, I have to overwrite my RECID variable with something else that is unique within the file so that I can merge the dump results with other data. And I have to overwrite the RECID on the other data two. But of coruse I don't want to lose the original PUF RECID because sometimes we want to go back and look a the PUF to debut mysteries. So I have to make a backup true RECID variable on the other data so I can always recover the actual PUF RECID. (True, I could avoid this rigamarole if i trust Tax-Calculator to return records in the same order as they were input, eliminating the need for a merge variable. But I don't want to trust in that.)
> 
> It's not a problem per se, just some extra work for me and the possibility of using the wrong variable at some point.
> 
> The issue could be avoided by either (a) having Tax-Calculator allow you to specific non-tc variables that you want included in the dump file, or (b) allowing an ID variable that is not necessarily named "RECID". I realize you don't want to lose the benefit in the user guide quote given above, but if the user is allowed to specify this, you'd be allowing them to give up that benefit (or you could say you can only specify character variables, or something else that could not mess with tax caculations).
> 
> Not a big deal, just a small nice-to-have thing.

**Comment by MattHJensen** [comment]
My inclination is to guarantee that we don't modify the order of the records. So check to see if we have a test, add one if we don't, and then document that we have it.

This is a minimalist's response, but I think that is appropriate for a project like Tax-Calculator where bugs are so costly. 

I'm interested in other views, though.

**Comment by hdoupe** [comment]
@MattHJensen Ensuring the order of the records remains constant seems like the right approach. 

Another approach would be to add a flag where users could specify whether extra variables should be dropped or not. But this would add some complexity to the code base and the api.

**Comment by MattHJensen** [comment]
> But this would add some complexity to the code base and the api.

Yea, I'm worried about unintended consequences -- particularly relating to the quality of error messages, but also more generally -- if we carry the extra variables around.

**Comment by jdebacker** [comment]
I do not think  it's worth ensuring that the order of the records remains the same in the output file.  It's really bad practice to merge data in this way, as the emailer notes:

> True, I could avoid this rigamarole if i trust Tax-Calculator to return records in the same order as they were input, eliminating the need for a merge variable. But I don't want to trust in that.

I think the emailer suggests the most reasonable solution: the user makes a variable called RECID that uniquely identifies the record in the user's datafile (in user's case this would be the PUF RECID + ftype).  This variable can then be used to merge between the TC output and other datasets.  There is some cost to renaming variable (e.g., RECID to PUF_RECID) to keep track of the original RECID variable in the PUF, but this cost seems very small (there is no increase in the size of the dataset, just the cost of remembering what the PUF_RECID refers to).

Another suggestion, if the cost to users of renaming a variable is worth avoiding, is to give the record id used in the Tax-Calculator records object a name that is unlikely to appear in other datasets (e.g., TC_RECID).  This way the the user can create a TC_RECID (in this case RECID + ftype) and still keep the original RECID (and avoid any confusion of renaming that variable to something like PUF_RECID).

**Comment by MattHJensen** [comment]
I received permission from @donboyd5 to tag him here and credit him as the original email's author.

**Comment by MaxGhenis** [comment]
A hybrid option along the lines of @jdebacker's suggestion is to output a field like `original_rownum` which is assigned to the data upon ingestion as a sequence, and then is dumped in the output. This provides a straightforward way to link back to the original data without forcing users to provide a specific column or forcing taxcalc to preserve the row order (and users to assume taxcalc has done so, as I agree is nonideal practice).

**Comment by hdoupe** [comment]
One thing to consider is that Tax-Calculator doesn't keep the data that is loaded by the user as a dataframe--it keeps it as a collection of numpy arrays.  Given this approach, it seems like we already operate under the assumption that the rows are not shuffled once they've been saved on the `Records` object as arrays.

**Comment by jdebacker** [comment]
Given the length of time this issue has been open and the last comment in the conversation (that given the use of the `numba` `jit` decorators records do not rename in a DataFrame format) I am inclined to close this issue.

If more work is done on PR #2585, which potentially would allow one to keep the records in a DataFrame object while the calculations are performed,  perhaps we can revisit this issue.
