### ISSUE TITLE
Running synthetic data through Tax-Calculator -- seeking some advice/confirmation

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/Tax-Calculator#2383]
Hi All. Of likely interest to @martinholmer, @MattHJensen, @andersonfrailey, @MaxGhenis, @feenberg, @yimengyin16, @gchen3, possibly others.

**Goal:**
- Compare Tax-Calculator results under various tax policies calculated with a synthetic puf-based data file as enhanced by TaxData to results for a similarly enhanced actual puf-based data file
- For a single data year and tax year (2019)
- Using the tc CLI
- Do this in (to the greatest extent possible) an apples-to-apples way, which means that I want any workarounds that we had to impose on the beta synthetic file to also be imposed on the puf (I'll explain below)
- Immediate objective is to prepare data file properly for Tax-Calculator tc CLI input

**Advice sought:**
- Am I approaching this the right way?
- Is there a better way?

**Status and issue:**
- After some speed bumps, we (thanks to @yimengyin16) have a synthetic file that has been run through TaxData in a pretty good way (subject to further testing) - I would call it a slightly bruised apple, rather than a perfect one (e.g., we inadvertently didn't have variables needed to do proper prime-spouse splits of self-employment income on married records so I used wage splits when available or else a 50-50 rule; in future syntheses we'll make sure we synthesize needed split variables)
- I bruised the TaxData-enhanced puf in a similar way so that we can compare slightly-bruised apples to similarly slightly-bruised apples
- We have extrapolated weights for these files (quite quickly, thanks to speedups developed by @yimengyin16), which are necessarily different from those in the PUF and of course non-existent 
within TaxData for the synthetic file.
- To run these two files through Tax-Calculator, we need to apply growfactors and POSSIBLY (see note below) apply puf_ratios, as those adjustments are not embedded in TaxData-produced files but rather are done within Tax-Calculator.
- I want to be in control of this process and do not want to try to arrange things so that Tax-Calculator does it automatically (e.g., I will not name the input file for tc CLI "puf.csv").

**My plan:**
I plan to preprocess the files before running them through Tax-Calculator via tc CLI:
1. apply the growth factors
a. as found in Tax-Calculator/taxcalc/growfactors.csv
b. using the method in Tax-Calculator/taxcalc/records.py function _extrapolate
2. POSSIBLY apply the puf ratios
a. as found in Tax-Calculator/taxcalc/puf_ratios.csv
b. using the method in Tax-Calculator/in taxcalc/records.py function _adjust
c. A CAUTION ON THIS STEP: we do not have an AGI bin on the synthetic file and it would not be appropriate to synthesize one. To do this step, I would have to somehow construct/estimate an AGI bin under 2011 law. While I can think of ways to do this, it would not be easy. I am thinking I may drop this adjustment for both the synthetic file and the slightly bruised puf. (When we synthesize next, we can deal with this in advance.) Any thoughts on how much difference leaving this step out would cause?

I will run the resulting file (which will NOT be named "puf.csv") through tc CLI with different reforms, as desired and dump the output to a file.

I do not need to do anything special in advance with the weights. I will merge the dump results with my custom weights to do my own tabulations of results for the slightly bruised TaxData-enhanced puf and the TaxData-enhanced synthetic data file.

**REPRISE: My questions:**
- Does this seem right?
- Is there a better way (while still meeting my goals, such as using the tc CLI, and maintaining full control over the growfactors and puf_ratios processes rather than delegating them to Tax-Calculator)?

Many thanks.

Don

**Comment by MattHJensen** [comment]
@donboyd5, these procedures and goals generally make sense to me. I am happy to help if you run into any trouble putting the plan into action. 

Regarding the puf ratios, I think you would be ok doing without them. You can read more about their introduction, [here](https://github.com/PSLmodels/taxdata/blob/master/puf_stage3/doc/puf_stage3.md), and you can see  exactly how they influenced Tax-Calculator results when they were first introduced, [here](https://github.com/PSLmodels/Tax-Calculator/pull/1193/files). 

(Please let me know if you need any help interpreting these diffs. The way I found them, btw, was to open the `puf_ratios.csv` file in GitHub and then click on "history" and then go back to the first commit where they were introduced). 

All that said, is there a reason that you can't just construct bins from the AGI calculation that Dan provided?

**Comment by donboyd5** [comment]
Am running out so just a quick response.

I suppose I could. I am way short on time. Doing that requires binning both
the puf and the syn file with Dan's agi which means asking Dan to calc his
agi on the puf with the variables we have, or else trusting that Dan's agi
is very close to the puf agi without checking (the probably are, but
trusting and data don't go well together). It's a lot of extra steps and
there are already several - according to my intuition - larger differences
between the syn file as we can run it through TaxData and the syn file as
we'd like it to go through puf. If I am to have some number for a
TaxData-enhanced syn file compared to a TaxData-enhanced puf with the same
infirmities as the the syn file (or else we won't be comparing apples to
apples) for my AEI presentation, I have to priorities, and my intuition is
that the back and forth with Dan and the 2-4 hours of my own time doing
this (most of the time spent being sure it is right and addressing problems
when it is wrong) would be better spend doing more important things
pre-AEI-presentation. I have several backup plans that still get useful
information. I may need them.

Post-AEI, once we have funding, we'll have a nice list of things we can do
better in the next synthesis, next file weighting, and next post-synthesis
TaxData enhancement.

Don

**Comment by donboyd5** [comment]
I'll try to do it with Dan's AGI on the syn file, without rerunning it on
PUF, and if it goes without a hitch, that will be good.

**Comment by MattHJensen** [comment]
All makes sense. Based on the diffs, I also think you're fine not using puf_ratios for now and am very happy for you to spend time wherever you think is most efficient.
