### ISSUE TITLE
Seeking quick bit of advice interpreting what tc CLI does

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/Tax-Calculator#2384]
Hi,

Hoping for quick bit of advice/clarification, most likely from @MattHJensen, @martinholmer, or @andersonfrailey.

In all the times I have used tc CLI I have not been running it on good old puf.csv -- I have instead typically been running it on a non-TaxData-enhanced synthetic file stacked with a similarly structured unenhanced puf, and so I have not run into the question I describe below.

In trying to debug some current results, I wanted to compare them to what I would get with the true puf.csv. In doing that, I realize I do not have a 100% perfect understanding of what tc CLI does when working with puf.csv and am hoping someone can clarify.

Let me start with my questions; I can provide more details if needed. My questions are based on my runs with Tax-Calculator 2.6.0 tc CLI using an identical copy of the puf.csv found in the Dropbox IRS_pubuse_2011 directory. A typical command would look something like this, where I am running tc under baseline law:

`C:/ProgramData/Anaconda3/Scripts/tc  D:/tax_data/puf.csv 2013 --dump --outdir D:/tax_data/`

The puf-13-#-#-#-doc.text output file says:

> REFORM DOCUMENTATION
> Baseline Growth-Difference Assumption Values by Year:
> none: using default growth assumptions
> 
> Response Growth-Difference Assumption Values by Year:
> none: using default growth assumptions
> 
> Policy Reform Parameter Values by Year:
> none: using current-law policy parameters

**Here come my questions:**

1. Is the latest released version of puf.csv still in the Dropbox IRS_pubuse_2011 directory? The one I see and can access is dated 5/23/2018 and has 239,002 data records. If not, where should I go to get the latest?

2. If I want the set of weights compatible with the puf.csv I am using (in case I want to apply them manually), where should I go to get them? The weights file [in TaxData](https://github.com/PSLmodels/taxdata/blob/master/puf_stage2/puf_weights.csv.gz)  has 248,591 data records so I think it cannot match the puf.csv that I have.

3. I am trying to be sure I understand the circumstances under which tc CLI applies weights and growth factors for an analysis that involves a tax year later than the data year, and how it does so. I did not see this discussed in the [user guide](https://pslmodels.github.io/Tax-Calculator/uguide.html). I had assumed that it only did this when the input file is named puf.csv but I think that is not correct. I now think that it does this whenever the input file has the variable FLPDYR and this variable is different from the tax year of an analysis. Is this correct?

4. I think that when I run tc CLI it must be finding and using both growth factors and weights, but I am not 100% sure where it is finding them. I have several copies on my system but I am guessing that it finds the weights in the tc package directory (on my system, I think it is finding them at  C:\ProgramData\Anaconda3\pkgs\taxcalc-2.6.0-py37_0\Lib\site-packages\taxcalc\puf_weights.csv.gz). This file has 248,591 data records, the same as the latest on github. I think tc CLI is grabbing growfactors from the same place.

This all makes sense in that  tc CLI looks like it is doing what it should be doing.

However, the weights do not match the number of records I have in puf.csv and my results are obviously wrong; this makes me think there is a newer better puf.csv I should get.

5. One option is for me to just use the puf I have and apply the weights and growfactors I think appropriate for my purpose, manually. Is there a way to ensure that I do that? This is really a repeat of the question above - can I just rename the file and delete FLPDYR and apply my own growfactors and weights? I think so. Is there a way I can have tc CLI apply one but not the other (e.g., apply weights but not growfactors? Or if I have tc CLI do one, will it automatically do the other?

I think that's it. Would much appreciate any answers folks have.

Don

**Comment by donboyd5** [comment]
Hi All,

@hdoupe solved my problem caused by using an outdated puf (thanks!), by pointing me to the correct current one (I made a dropbox mistake).

However, I still have one burning question: What, precisely, determines when and how the tc CLI will extrapolate data using:

1. Extrapolated weights that are included with the taxcalc python installation

2. Growfactors also included with the installation, and 

3. pufratios also included with the installation?

In particular:
a) Is the tc choice to extrapolate based on file name (puf.csv or cps.csv)? (I don't think so)
b) Is the choice based on presence of FLPDYR? (I think so)
c) Number of records in the file? (I don't think so)

While I have been checking values of selected variables and also weights that are included in both the input and output files to see under what circumstances values may change, it would be great to have a precise statement of what triggers extrapolation (and whether all 3 are always done, or just one).

Many thanks.

Don

**Comment by MattHJensen** [comment]
@donboyd5, I am going to test with a few examples later this afternoon or tomorrow, but my current understanding from rereading the [code](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/cli/tc.py#L155) is that the extrapolation will occur if the filename ends with either "puf.csv" or "cps.csv." So `test_puf.csv` would trigger the extrapolation but `puf_test.csv` would not.

**Comment by donboyd5** [comment]
I see. Thank you. It looks from the code like that probably is the rule.
Knowing that is very helpful. I do compare the input file and the output
file by hand with a text editor to see if important variables in both files
(e..g, e00200) have changed but it would be nice to be less paranoid.

**Comment by MattHJensen** [comment]
>  I am going to test with a few examples later this afternoon or tomorrow, but my current understanding from rereading the code is that the extrapolation will occur if the filename ends with either "puf.csv" or "cps.csv." So test_puf.csv would trigger the extrapolation but puf_test.csv would not.

My tests confirmed our understanding that filenames ending with either "puf.csv" or "cps.csv" will trigger the extrapolation and other filenames will not. 

I plan to make two improvements to make everything more clear: 

- [ ] Alert the user to this behavior in the `tc` docs
- [ ] Modify the .text output to indicate when no extrapolation has happened. Currently, these output lead you to believe an extrapolation has occurred, even when it hasn't, by saying that default growth assumptions were used. For example, see the output in `puf_test-20-#-#-#-doc.text`, which is exactly the same as the output in `test_puf-20-#-#-#-doc.text`:

> REFORM DOCUMENTATION
Baseline Growth-Difference Assumption Values by Year:
none: using default growth assumptions
Response Growth-Difference Assumption Values by Year:
none: using default growth assumptions
Policy Reform Parameter Values by Year:
none: using current-law policy parameters

In the meantime, I will note that the user is told when an extrapolation took place in a message, seen below, and this message will not be displayed without the extrapolation taking place. 

![image](https://user-images.githubusercontent.com/8301092/69341043-c6206300-0c36-11ea-9882-31bef2496f69.png)

**Comment by donboyd5** [comment]
That would be great. I think it will reduce the risk of user
misinterpretation considerably. Thanks.
