### ISSUE TITLE
Version is set to 0.0.0 in setup.py and taxcalc/__init__.py

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2386]
See
https://github.com/PSLmodels/Tax-Calculator/blob/4a5b71f7e934df06d698a9a98eba4c5bd60367bf/setup.py#L9
and
https://github.com/PSLmodels/Tax-Calculator/blob/4a5b71f7e934df06d698a9a98eba4c5bd60367bf/taxcalc/__init__.py#L17

This sets the version to 0.0.0 when installing from GitHub:
```
!pip install git+git://github.com/PSLModels/Tax-Calculator.git
```
Which can in turn break packages that rely on `taxcalc` of a certain minimum version (I'm doing this in microdf).

While pip isn't the officially supported way of installing `taxcalc`, it works fine and allows people to use it in non-conda environments, like Google Colab. Could these two places be updated as part of the release cycle?

**Comment by hdoupe** [comment]
@MaxGhenis Package-Builder writes the correct version when Tax-Calculator is published on conda. I'm partial to your thinking that the version should be updated with each release to better support pip installations. That's what I do with ParamTools, and it's just another item on the checklist that needs to be hit like writing release notes.

Does Google Collab not allow conda? Or, are you trying to install a pre-released version of Tax-Calculator from the master branch/another branch?

**Comment by MaxGhenis** [comment]
Colab does not allow conda.

**Comment by jdebacker** [comment]
@MaxGhenis, you can install via conda on Google Colab.  Try:

```
# Install Miniconda
!wget https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh && bash Miniconda3-4.5.4-Linux-x86_64.sh -bfp /usr/local
# Append path to be able to run packages installed with conda
import sys
sys.path.append('/usr/local/lib/python3.6/site-packages')
# Install PSL packages from Anaconda
!yes | conda install -c PSLmodels taxcalc
```

**Comment by MattHJensen** [comment]
@MaxGhenis, thanks for raising this issue, @hdoupe thanks for your feedback, and @jdebacker thanks for the tip on using conda w colab. 

I'm happy to add these to the `RELEASING.md` checklist and include in the next release.

**Comment by jdebacker** [comment]
@hdoupe Any way to have the `setup.py` pull the most recent tag automatically?  I don't know much about how git keeps track of the tags on each branch, etc.

**Comment by MaxGhenis** [comment]
Thanks @jdebacker for sharing how to use taxcalc in Colab via conda! I couldn't figure out how to do this with a more current conda version though, do you know if this is possible? Asked over in #2393.
