### ISSUE TITLE
BokehDeprecationWarning: 'legend' keyword is deprecated

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2389]
The build throws this warning:
>BokehDeprecationWarning: 'legend' keyword is deprecated, use explicit 'legend_label', 'legend_field', or 'legend_group' keywords instead

**Comment by hdoupe** [comment]
@jdebacker Fixed this recently in Cost-of-Capital-Calculator (https://github.com/PSLmodels/Cost-of-Capital-Calculator/pull/289/files). I think the `legend` keyword just needs to be swapped to `legend_label`.

**Comment by MaxGhenis** [comment]
Closing (for some reason the "Resolves #2389" in https://github.com/PSLmodels/Tax-Calculator/pull/2391#issuecomment-565224597 didn't close this).
