### ISSUE TITLE
Using taxcalc in Google Colab with conda

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2393]
[Google Colab (Colaboratory)](https://colab.research.google.com/) is a free web Jupyter environment. One way to use taxcalc in Colab is to install it from GitHub:
```
!pip install git+git://github.com/PSLModels/Tax-Calculator.git
```

In https://github.com/PSLmodels/Tax-Calculator/issues/2386#issuecomment-565087311, @jdebacker also provided a way to install taxcalc with conda:
```
# Install Miniconda
!wget https://repo.continuum.io/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh && bash Miniconda3-4.5.4-Linux-x86_64.sh -bfp /usr/local
# Append path to be able to run packages installed with conda
import sys
sys.path.append('/usr/local/lib/python3.6/site-packages')
# Install PSL packages from Anaconda
!yes | conda install -c PSLmodels taxcalc
```
[Here's a notebook](https://colab.research.google.com/drive/12it6qb0sFBTgCN48Tl3VIr-TLpBvjtZQ#scrollTo=Tv2RjZWgYlw0) showing that in action.

However, this apparently only works with an old version of conda. When either downloading/installing the latest installer file ([notebook](https://colab.research.google.com/drive/1GUAQGyhhXi9sBER8voQ3IehzOrXBaUkj)) or running `conda update conda` before installing taxcalc ([notebook](https://colab.research.google.com/drive/10V59-Z8SbKUlIbOiOjwaSsTwUkOSs422)), taxcalc shows up in `conda list` but not when importing it:
>ModuleNotFoundError: No module named 'taxcalc'

Is there a way to install taxcalc without using an old version of conda? Does this have to do with path?

Mentioned this in [this SO question](https://stackoverflow.com/a/59310896/1840471).

**Comment by hdoupe** [comment]
I tinkered with this but didn't have any luck. Binder may be a friendlier service for this type of thing.

**Comment by jdebacker** [comment]
Hmm,  I'm not having any trouble with this.  See [this Colab notebook](https://colab.research.google.com/drive/1F15hEDZ6uSCaHAc92RHqn41LKBLOpX1d).

I looks like your miniconda is not installing properly, but you are using the same commands as me.

**Comment by jdebacker** [comment]
Only diff I'm seeing is that I do the `conda install` in another cell.  Maybe some conflict if in both?  Like from not completing an install of something?  The conda install does take a while...

**Comment by jdebacker** [comment]
@MaxGhenis I just tried this with the latest miniconda and it seemed allow TC to be installed.  Maybe give it a try and we can resolve this issue.

**Comment by MaxGhenis** [comment]
Works now, both in using the latest miniconda installer ([notebook](https://colab.research.google.com/drive/1GUAQGyhhXi9sBER8voQ3IehzOrXBaUkj)) and when updating ([notebook](https://colab.research.google.com/drive/10V59-Z8SbKUlIbOiOjwaSsTwUkOSs422)). I wonder if it had to do with conda updating Python from 3.6 to 3.7; I had to update this line:
```
sys.path.append('/usr/local/lib/python3.7/site-packages')
```
Thanks @jdebacker, closing.
