### ISSUE TITLE
TaxBrain Issue: Single term for returns/filers in tables

### ISSUE THREAD

**Issue by andersonfrailey** [PSLmodels/Tax-Calculator#2396]
Over in Tax-Brain issue [#105](https://github.com/PSLmodels/Tax-Brain/issues/105), @MaxGhenis suggested the following change to the distribution and differences table headers:

>Minor suggestion to make table headers more consistent: returns or filers are currently denoted as a mix of `Returns` `Filers` `Count` and `Itemizers`. I think a single term would be clearer (my vote would be Filers).
>
> **Distribution table**:
>* Returns
>* Standard Deduction Filers
>* Itemizers (could be e.g. Itemized filers)
>* AMT Filers
>
>**Differences table**:
>* Returns
>* Count with Tax Cut
>* Count with Tax Increase

**Comment by MattHJensen** [comment]
Thanks @MaxGhenis for the suggestion and @andersonfrailey for porting over the issue. 

My instinct is to use 'Returns' to align with IRS SOI [tables](https://www.irs.gov/statistics/soi-tax-stats-individual-statistical-tables-by-size-of-adjusted-gross-income). 

@MaxGhenis, are there overriding reasons you think we ought to use 'Filers'?

**Comment by MaxGhenis** [comment]
>@MaxGhenis, are there overriding reasons you think we ought to use 'Filers'?

Just that "standard deduction returns" sounded a bit odd, but either works and consistency with IRS SOI tables is a good basis.

**Comment by jdebacker** [comment]
Closed via PR #2592.
