### ISSUE TITLE
taxsim27 validation file (taxcalc.sh) not working in Windows 

### ISSUE THREAD

**Issue by ernietedeschi** [PSLmodels/Tax-Calculator#2407]
I'm trying to convert a TAXSIM27 file to one usable by `tc`.

Here's what I'm doing and seeing:

```
$ ./taxcalc.sh c18_taxsim save
./taxcalc.sh: line 57: syntax error: unexpected end of file
```

"unexpected end of file" in bash usually denotes an unpaired parenthesis or the failure to close loops, e.g. "fi" after "if". I did a quick (and bash-ignorant) peruse of the `taxcalc.sh` file however and didn't see any obvious issues. 

The file I'm trying to convert is shared [here](https://drive.google.com/file/d/1t7PbggVKtiPxFQ4xOeggCaSQGIov9jji/view?usp=sharing). It's just an extract of the 2019 CPS ASEC.

**Comment by feenberg** [comment]
Did you try

    bash -x ./taxcalc.sh c18_taxsim save

which should give you a trace of the script showing where things went 
wrong.

dan

**Comment by ernietedeschi** [comment]
> Did you try bash -x ./taxcalc.sh c18_taxsim save which should give you a trace of the script showing where things went wrong. dan

I get exactly the same error message:

```
$ bash -x ./taxcalc.sh c18_taxsim save
./taxcalc.sh: line 57: syntax error: unexpected end of file
```

**Comment by MattHJensen** [comment]
I just ran the same thing on my mac, and here is the traceback from my first try. I will am continuing to investigate. 

Short:

```
    raise ValueError(msg.format('e00200s'))
ValueError: e00200s is not always zero for non-married filing unit
ERROR: 'tc ...' call failed
```

Long: 


```
Traceback (most recent call last):
  File "/Users/matthewjensen/anaconda3/envs/taxcalc-dev/bin/tc", line 11, in <module>
    sys.exit(cli_tc_main())
  File "/Users/matthewjensen/anaconda3/envs/taxcalc-dev/lib/python3.7/site-packages/taxcalc/cli/tc.py", line 160, in cli_tc_main
    exact_calculations=args.exact)
  File "/Users/matthewjensen/anaconda3/envs/taxcalc-dev/lib/python3.7/site-packages/taxcalc/taxcalcio.py", line 335, in init
    exact_calculations=exact_calculations)
  File "/Users/matthewjensen/anaconda3/envs/taxcalc-dev/lib/python3.7/site-packages/taxcalc/records.py", line 167, in __init__
    raise ValueError(msg.format('e00200s'))
ValueError: e00200s is not always zero for non-married filing unit
ERROR: 'tc ...' call failed
```

**Comment by ernietedeschi** [comment]
Thanks @MattHJensen. Back when I had a Mac, I got the same error message but the script actually did still work. Now in Windows it doesn't even get that far.

**Comment by MattHJensen** [comment]
> but the script actually did still work. 

[Here is a dropbox link to c18_taxsim.csv](https://www.dropbox.com/s/7pqy009e35z3g3h/c18_taxsim.csv?dl=0). Does this (or would anything else) help until we can figure out what's going on w Windows?

**Comment by ernietedeschi** [comment]
> > but the script actually did still work.
> 
> [Here is a dropbox link to c18_taxsim.csv](https://www.dropbox.com/s/7pqy009e35z3g3h/c18_taxsim.csv?dl=0). Does this (or would anything else) help until we can figure out what's going on w Windows?

Perfect @MattHJensen. Thank you!

**Comment by MattHJensen** [comment]
I spoke w @Peter-Metz. He said he is going to look into resolving the underlying problem that Windows users can't use this script. I'll leave this issue open for that.

@ernietedeschi, in the meantime, feel free to ping here or email me if you'd like me to convert any other files. Happy to do it anytime.

**Comment by Peter-Metz** [comment]
Hi @ernietedeschi - I'm going to look for a better long-term solution for the taxsim -> taxcalc conversion process, but in the meantime you might be interested in these instructions in the `taxcalc/validation` README:

>Those who want to use these validation tools on Windows will have to do three things: (a) install an AWK interpreter, (b) install a Tcl interpreter, and (c) translate each tests.sh and test.sh bash script into a Windows batch file. The Free Software Foundation provides a free AWK interpreter for Windows (gawk.exe). ActiveState provides a free Tcl interpreter for Windows (tclsh.exe).

Also, feel free to keep sending @MattHJensen the files to convert

**Comment by MattHJensen** [comment]
Resloved by #2408
