### ISSUE TITLE
Above-the-line charitable deduction

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2409]
The CARES Act includes a [$300 above-the-line charitable deduction](https://www.congress.gov/bill/116th-congress/senate-bill/3548/text#toc-id8C6FDC26FDF745B9ABA7BC0B89F6B42F) for tax filers that take the standard deduction. It's for 2020 only.

[JCT estimates](https://www.jct.gov/publications.html?func=startdown&id=5252) that this will reduce revenue by $1.6 billion.

I think this involves a new parameter.

**Comment by jdebacker** [comment]
This provision of the CARES Act was included in the baseline with PR #2556.  The `STD_allow_charity_ded_nonitemizers` parameter existed before that.
