### ISSUE TITLE
Return of local, state and federal tax deductions on passing payroll amount of an individual

### ISSUE THREAD

**Issue by ismailxmuhammad** [PSLmodels/Tax-Calculator#2411]
Suppose I have payroll amount and other personal information like state, age, job, no. of dependents etc. of a single person. How do I pass this data about a single person and it gives me back local, state and fed taxes that would be deducted on the payroll especially when on a weekly payroll amount. Any guidance would be very helpful. Thanks for the great work.

**Comment by feenberg** [comment]
On Mon, 4 May 2020, ismailxmuhammad wrote:

> 
> Suppose I have payroll amount and other personal information like state, age, job, no.
> of dependents etc. of a single person. How do I pass this data about a single person
> and it gives me back local, state and fed taxes that would be deducted on the payroll
> especially when on a weekly payroll amount. Any guidance would be very helpful. Thanks
> for the great work.

You could look at

   http://www.nber.org/taxsim

but it doesn't do local taxes, and you would have to divide annual 
liability by 52 to get an estimate of the weekly withholding. It wouldn't 
be the actual withholding which varies according to how the w-4 is filled 
out and you can't know how it is filled out.

Daniel Feenberg

**Comment by ismailxmuhammad** [comment]
> You could look at http://www.nber.org/taxsim but it doesn't do local taxes, and you would have to divide annual liability by 52 to get an estimate of the weekly withholding. It wouldn't be the actual withholding which varies according to how the w-4 is filled out and you can't know how it is filled out. Daniel Feenberg

Thanks for the prompt response. I checked out http://www.nber.org/taxsim(v32). It has all the parameters but when I submit the form with dummy values to http://data.nber.org/taxsim32/page.cgi **it returns a blank page**. I also went through command line (tc) usage mechanism and especially studied the test.csv calculations and variables. I am almost close to the solution but still unable to find a method that I can call on calculator class object with data passed as parameter and in turn get taxes calculated. I studied the developer's Cookbook for this calculator as well but didn't find what I was looking for. In want to integrate Tax-Calculator with my application and needed if you can make it easier.

**Comment by MattHJensen** [comment]
The advantage of using taxsim is that it has the state tax computations, which Tax-Calculator doesn't. If the state tax computations are not essential, then you could try the [Tax-Cruncher](github.com/pslmodels/tax-cruncher) interface to Tax-Calculator, which is designed for a similar purpose. You will still need to handle with the estimated withholding off-model, following Dan's division by 52 suggestion. 

cc @Peter-Metz who maintains Tax-Cruncher.

**Comment by MattHJensen** [comment]
Also, if you'd rather use Tax-Calculator directly rather than Tax-Cruncher for any reason, the Tax-Cruncher source code might still be helpful.

**Comment by ismailxmuhammad** [comment]
Thanks for the help.  http://www.nber.org/taxsim still returns an empty page upon submission with default values or custom dummy values but I got the answer to my problem anyway. Keep the good work going.

**Comment by MattHJensen** [comment]
@ismailxmuhammad, I'm glad you found a solution to your problem. If you have an opportunity sometime, I'd love to hear more about your project. Best of luck!
