### ISSUE TITLE
Ensure the cookbook is updated in the release process

### ISSUE THREAD

**Issue by MattHJensen** [PSLmodels/Tax-Calculator#2412]
I will handle this during the next release. The cookbook was recently out of date, requiring https://github.com/PSLmodels/Tax-Calculator/pull/2410, so I either missed something in the last release or the release checklist needs to be updated.

**Comment by jdebacker** [comment]
@MattHJensen What's the status of this issue?  Is @MaxGhenis correct that it is moot given how docs are now deployed?

**Comment by MattHJensen** [comment]
Yes, that's right. Thanks @jdebacker and @MaxGhenis. Closing.
