### ISSUE TITLE
Benefits programs liability totals

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Tax-Calculator#2416]
Currently, the default aggregate liabilities tables from Tax-Calculator report payroll and individual income tax liabilities. But Tax-Calculator also allows users to adjust parameters of spending programs such as UBI, Social Security, and unemployment insurance.  

It might be useful to have the default liabilities table also report a line for changes in aggregate amounts of spending so that users can see the costs of adjusting these benefits programs.

**Comment by jdebacker** [comment]
@Peter-Metz @MattHJensen What do you think about providing aggregate amounts of government spending on benefits calculated in Tax-Calculator?  It seems like the output in terms of changes in tax liability is misleading (or at least suffers from omission) when one adjusts benefit programs amounts.

I haven't checked - does TC match aggregates from other sources for these spending programs?

**Comment by Peter-Metz** [comment]
@jdebacker, TC has a calculated variable called `benefit_cost_total` which sums the cost of [these](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/calcfunctions.py#L56:L68)  benefit programs (and doesn't include UBI). In 2020, the weighted total of `benefit_cost_total` is just shy of $1.1 trillion, which seems to line up with other sources from a quick search. Is this what you had in mind? Are there other programs you think should be included in the total?

I can definitely see the benefit of including changes in aggregate spending amounts in the liabilities tables, but I'll let @MattHJensen weigh in on this.

**Comment by jdebacker** [comment]
@Peter-Metz I'm not suggesting adding any more benefits programs at the moment, but rather just reporting outlays for currently modeled spending programs.  But one might want to sum them differently - e.g., reporting a separate line item for Social Security payments (since they come from the SS Trust Fund and not the general fund).

**Comment by jdebacker** [comment]
Moving to the Tax-Brain repo, which I think is more appropriate given that is where these aggregate tables are made.
