### ISSUE TITLE
What was "taxcalc.sh" replaced with?

### ISSUE THREAD

**Issue by Thirdhuman** [PSLmodels/Tax-Calculator#2417]
When preparing tax calc for use with microdata, I previously could use:
`./taxcalc.sh c19_taxsim save`
And a new .csv file would be created.  What is the successor to this command?
This seems to have been replaced when I updated.

**Comment by hdoupe** [comment]
Hi @Thirdhuman, it was replaced with [`taxcalc.py`](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/validation/taxsim27/taxcalc.py) in this PR https://github.com/PSLmodels/Tax-Calculator/pull/2408. You can run it with this command:

```bash
python taxcalc.py LYY_FILENAME [--save] [--help]
```

cc @Peter-Metz

**Comment by jdebacker** [comment]
@hdoupe Thanks for answering this!
