### ISSUE TITLE
Add more function docstrings

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2421]
This would enable Sphinx to generate function documentation. Currently, classes and a few functions have docstrings, but important ones like `calc_all` lack them.

The `pandas` docstring guide looks like a good model: https://pandas.pydata.org/pandas-docs/stable/development/contributing_docstring.html

**Comment by jdebacker** [comment]
Many more function doc strings were added with PR #2558.  There are still a few functions lacking doc strings, but I'm closing this issue and more specific issues can be opened in the future.
