### ISSUE TITLE
Make text fields in policy_current_law.json Markdown-compatible

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2424]
With documentation moving to Jupyterbook (#2420), we'll want to check that text fields in policy_current_law.json are Markdown-compatible. They mostly are, but e.g. I saw this, where we'll want to wrap _CTC_new_refund_limit_payroll_rt in ` ticks so the underlines don't get dropped as italics.

https://github.com/PSLmodels/Tax-Calculator/blob/f3f7d955024b887f0f6714dbbec5343013008d80/taxcalc/policy_current_law.json#L15163

**Comment by jdebacker** [comment]
<img width="800" alt="Screen Shot 2021-05-23 at 10 05 12 PM" src="https://user-images.githubusercontent.com/10715924/119286696-f4f40c80-bc12-11eb-95d2-08733a3f2c90.png">

@MaxGhenis I'm not seeing any problems.  Shall I close this issue?

**Comment by MaxGhenis** [comment]
Yeah I think this is fine.
