### ISSUE TITLE
Remove year from default values of growdiff and consumption parameters in documentation

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2425]
Documentation currently shows this:
![image](https://user-images.githubusercontent.com/6076111/86522477-42a53200-be13-11ea-8c38-91e00b9e3bb2.png)

The year is 2013 for all consumption and growdiff parameters, so it seems like unnecessary detail that could be removed. Unless we anticipate including some consumption or growdiff params that would have different default values by year, it could instead be simplified to e.g. `Default Value: 0`.

**Comment by jdebacker** [comment]
This has been corrected in more recent versions of the documentation.
