### ISSUE TITLE
Drop distutils.core from setup.py

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2428]
I think the below lines can be replaced with `import setuptools` now that `taxcalc` is Python 3+ only. Is this right?

https://github.com/PSLmodels/Tax-Calculator/blob/f3f7d955024b887f0f6714dbbec5343013008d80/setup.py#L1-L5

Based on [Flask documentation](https://flask.palletsprojects.com/en/1.1.x/patterns/distribute):
>If you have Python 2 (>=2.7.9) or Python 3 (>=3.4) installed from python.org, you will already have pip and setuptools on your system.

**Comment by jdebacker** [comment]
Closed via PR #2592.
