### ISSUE TITLE
Support Python 3.8 on conda

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2448]
I imagine this will happen in the next release, but adding here just to track. One consequence of the conda package not yet supporting Python 3.8 is that taxcalc can't be installed with the standard miniconda installer, e.g. [for usage on Colab.](https://colab.research.google.com/drive/1GUAQGyhhXi9sBER8voQ3IehzOrXBaUkj#scrollTo=3p-xyioIIqrr)

**Comment by MaxGhenis** [comment]
This looks to be done now:
![image](https://user-images.githubusercontent.com/6076111/91102177-86e7ce00-e61d-11ea-80c7-510c866b53e7.png)

Filed #2478 as it's still failing in Colab.

**Comment by donboyd5** [comment]
Yes, I installed Anaconda freshly about 2 days ago and was surprised to see
this:

[image: image.png]
