### ISSUE TITLE
Separate UBI parameters for 21-64 and 65+

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2451]
This would be helpful especially for UBI proposals funded by labor income. I've done it separately from `taxdata` files using `microdf`'s [`n65`](https://github.com/MaxGhenis/microdf/blob/f1a976b2451b2dda03735dee2bae8e8c3b3bb2d6/microdf/taxcalc.py#L44) function, but for tools like OG-USA it'd be nice to have in `taxcalc` itself.

**Comment by MattHJensen** [comment]
@MaxGhenis, I am open to this. If we do it, it'd be nice to include before 3.0 as it will break backwards compatibility.

**Comment by MaxGhenis** [comment]
OK, I can work on it next week if that's not too late.

Should we add `n65` to `taxdata` as well? This isn't necessary since `age_head`, `age_spouse` and `elderly_dependents` provide enough information to do the calculation, but making it explicit in the data may be clearer.

**Comment by MattHJensen** [comment]
> OK, I can work on it next week if that's not too late.

I expect that will be fine and much appreciated. 

> Should we add n65 to taxdata as well? This isn't necessary since age_head, age_spouse and elderly_dependents provide enough information to do the calculation, but making it explicit in the data may be clearer.

I'm inclined to only add data columns when absolutely necessary. We already use a lot of memory.
