### ISSUE TITLE
Issue on page /usage/overview.html: (a) link to "suggest edit" gives 404 error (b) change liebility to liability

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/Tax-Calculator#2454]
I tried to suggest an edit on this page but the link for "suggest edit" gives 404 error.

The edit:
On line of 2nd to last bullet under Quick Start, which begins with "itax_clp", "liebility" should be "liability".

**Comment by MattHJensen** [comment]
Thanks a lot @donboyd5. Typo will be fixed with PR #2457, and then I opened a new issue #2456 for figuring out the 404.
