### ISSUE TITLE
Issue on page /recipes/recipe00.html - reformA.json does not appear to have been downloaded to my computer

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/Tax-Calculator#2455]
- Updated Anaconda and updated tc to 2.9.
- Newcomer to python and jupyter, wanted to learn how to use recipes.
- Tried to run recipe00.
- When I got to:

`params = tc.Calculator.read_json_param_objects(reform_filename, None)`

there was an error. I have copied a full screenshot below, but relevant part of the message appears to be the following:

> C:\ProgramData\Anaconda3\lib\site-packages\taxcalc\utils.py in json_to_dict(json_text)
   1555             msg += '{:04d}{}'.format(linenum, line) + '\n'
   1556         msg += bline + '\n'
-> 1557         raise ValueError(msg)
   1558     return ordered_dict

> ValueError: Text below contains invalid JSON:
Expecting value: line 1 column 1 (char 0)
Above location of the first error may be approximate.
The invalid JSON text is between the lines:
XXXX----.----1----.----2----.----3----.----4----.----5----.----6----.----7
0001_static/reformA.json
XXXX----.----1----.----2----.----3----.----4----.----5----.----6----.----7

As far as I can tell, this means it did not find reformA.json. I did a search on my computer and it is not there. I did also check that I can progress through the recipe with a different reform json file I had handy, and I can.

Thus, it appears that recipe00 assumes I have reformA.json in an appropriate place on my computer but the tax-calculator installation does not put it there.

Don

![image](https://user-images.githubusercontent.com/6538392/90008530-7bce8e80-dc6a-11ea-90a9-bb7f87c2b348.png)

**Comment by MattHJensen** [comment]
@donboyd5, thanks for letting us know about this challenge with getting started with the recipes. 

@MaxGhenis, do you think this is related to #2259 and #2263?

@Peter-Metz, have you run into this working with people on Windows before?

**Comment by donboyd5** [comment]
FYI:
- Windows 10 64-bit
- I removed taxcalc and reinstalled, hoping that residue of some prior installation was causing a problem but that does not fix it
- I then downloaded reformA.json and B and C versions and placed them in appropriate directory
- all works well with recipe00 after that but obviously it would be nice to avoid manual download

**Comment by donboyd5** [comment]
I just read #2259 and #2263, @MattHJensen.

After that I changed the relevant line in my version of recipe00 from:

` reform_filename = '_static/reformA.json'`

to:

`reform_filename = 'https://raw.githubusercontent.com/PSLmodels/Tax-Calculator/master/docs/recipes/_static/reformA.json'`

(after learning from #2259 and #2263 that I need to point to the raw version of the json file, not the html version - note that this location is updated from the location given in #2263) and everything worked fine - obviously going directly to the web to read the json file rather than reading it from my hard drive.

My conclusion is that, at least for my Windows machine, updating or installing a fresh copy of taxcalc does not put reformA.json, reformB.json, or reformC.json anywhere on my computer, nor does it create the _static directory.

Either of two fixes work for me: (1) downloading the files manually and putting them in the appropriate directory, or (2) reading the json files in real time directly from the web. As @MaxGhenis noted, it might be convenient for users if the files are incorporated into the taxcalc downloard, or else if instructions are given for how to get the files.

Don

**Comment by MattHJensen** [comment]
@donboyd5, thanks a lot for the update on this issue. I am glad things are working now and am sorry for your earlier trouble. I am going note these troubles over in #2445 and then close this issue.
