### ISSUE TITLE
Issue on page /guide/input_vars.html

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/Tax-Calculator#2458]
The list of variables on the righthand side of the page does not appear to scroll below e02000, at least in my browser (Chrome). Thus, you cannot quickly go to a variable's documentation in the middle of the screen if it is below e02000. It would be nice if we could scroll the full list of variables.

**Comment by MaxGhenis** [comment]
This is a Jupyter-Book limitation. We could file an issue with them, but I'd prefer grouping input and output variables like we group policy and assumption parameters:
![image](https://user-images.githubusercontent.com/6076111/90294307-f0f0be00-de3a-11ea-84ce-6d9e570062d6.png)
![image](https://user-images.githubusercontent.com/6076111/90294322-fd751680-de3a-11ea-968d-48146dd0c520.png)
![image](https://user-images.githubusercontent.com/6076111/90294371-15e53100-de3b-11ea-9acd-5d5007862acb.png)

**Comment by MattHJensen** [comment]
@donboyd5 thanks for opening this issue. @MaxGhenis proposed approach seems like a good solution.

**Comment by donboyd5** [comment]
That sounds like a great idea to me, @MaxGhenis and @MattHJensen . Thanks.

**Comment by MaxGhenis** [comment]
Filed #2488 to categorize variables in the docs, though I think this should stay open as well until it's resolved.
