### ISSUE TITLE
Which puf growfactors.csv and puf_ratios.csv files to use? They differ between Tax-Calculator and taxdata. (puf_weights.csv.gz does not appear to differ)

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/Tax-Calculator#2459]
I apologize because I don't understand how versions of Tax-Calculator and taxdata are defined, and didn't find explanation in the documentation, although I may have missed it.

- [growfactors in Tax-Calculator](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/growfactors.csv) is different from [growfactors in taxdata](https://github.com/PSLmodels/taxdata/blob/master/puf_stage1/growfactors.csv) (e.g., ATXPY differs in 2030)
- [puf_ratios in Tax-Calculator](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/puf_ratios.csv) is different from [puf_ratios in taxdata](https://github.com/PSLmodels/taxdata/blob/master/puf_stage3/puf_ratios.csv) (e.g., bin 0 differs in 2030)
- by contrast, [puf_weights in Tax-Calculator](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/puf_weights.csv.gz) appears to be the same as [puf_weights in taxdata](https://github.com/PSLmodels/taxdata/blob/master/puf_stage2/puf_weights.csv.gz) -- I did not compare methodically, but the first few and last few weights in 2030 are the same.

I would much appreciate it if someone could tell me which set of files is the latest / proper set of files to use. (Also, if there is an intuitive explanation for why grow_factors would differ but puf_weights would be the same, would be great to know. I naively thought the two together are needed to hit a given set of targets and that if one changed the other would, too.)

Many thanks.

**Comment by Peter-Metz** [comment]
Hi @donboyd5. The Tax-Calculator project is a bit behind taxdata in terms of data updates. In particular, `growfactors.csv` and `puf_ratios.csv` have been updated in taxdata to reflect CBO's modified economic projects in light of COVID-19 (you can find the taxdata pull request that updated the files [here](https://github.com/PSLmodels/taxdata/pull/332), thanks to @chusloj). I think `puf_weights` also changed slightly from that update. Before incorporating these changes, Tax-Calculator has to resolve the issues in #2444.  I am hopeful that Tax-Calculator will be up to speed with taxdata soon (this is on my plate!).

In terms of which set of files to use, the taxdata files are the latest, but Tax-Calculator has not tested to make sure that these new files don't cause any unforeseen issues. Hope that helps.

cc @MattHJensen

**Comment by donboyd5** [comment]
Thanks, Peter!

Don
