### ISSUE TITLE
Broken links in releases tab

### ISSUE THREAD

**Issue by andersonfrailey** [PSLmodels/Tax-Calculator#2461]
The links to `RELEASES.md` and `CHANGES.md` in the release tags are broken. Looks like those files were removed from the repo at some point

**Comment by MaxGhenis** [comment]
They're now https://github.com/PSLmodels/Tax-Calculator/blob/master/docs/about/releases.md and https://github.com/PSLmodels/Tax-Calculator/blob/master/docs/about/changes.md

**Comment by MattHJensen** [comment]
Thanks @andersonfrailey and @MaxGhenis. Resolved via edits to the old releases.
