### ISSUE TITLE
Tax-Calculator citations in Jupyter Book documentation and PSLModels.org

### ISSUE THREAD

**Issue by chusloj** [PSLmodels/Tax-Calculator#2470]
This issue continues discussion regarding placing Tax-Calculator citations on PSLModels.org from [PSL-Infrastructure/#186](https://github.com/PSLmodels/PSL-Infrastructure/issues/186).

Summary of discussion so far:
- I suggested an initial workflow [here](https://github.com/PSLmodels/PSL-Infrastructure/issues/186#issuecomment-677872193) where `curl` would be used to fetch a `.bib` file and that `.bib` file would be uploaded to Jupyter Book docs which would take care of auto-formatting the citations. The link to that Jupyter Book page would then be placed as a hyperlink on PSLmodels.org.
- @Peter-Metz points out that a Jupyter Book documentation page containing citations is not necessary for PSL inclusion.
- I suggested that a markdown file could be automatically generated containing formatted citations from the `.bib` file mentioned above and then formatted using [pandoc](https://pandoc.org). **UPDATE**: pandoc can also output the formatted markdown file as an HTML file which we could place directly onto PSLModels.org.

Other thoughts are welcome.

@MattHJensen

**Comment by MattHJensen** [comment]
Thanks @chusloj for thinking through this workflow. The approach you outline makes sense to me. I am looking forward to reviewing #2473!

**Comment by MattHJensen** [comment]
@chusloj one suggestion: I recommend repurposing this issue and #2473 to do the bare minimum that is needed to store the citations in useful format in the Tax-Calculator repository and deploy them to the Tax-Caclulator JB docs site. The next step of making them useful for PSLmodels.org and whatever that entails can be addressed in an additional issue/PR.  Does that make sense to you?

**Comment by chusloj** [comment]
> @chusloj one suggestion: I recommend repurposing this issue and #2473 (or at least #2473, if not this issue) to do the bare minimum that is needed to store the citations in useful format in the Tax-Calculator repository and deploy them to the Tax-Caclulator JB docs site. The next step of making them useful for PSLmodels.org and whatever that entails can be addressed in an additional issue/PR. Does that make sense to you?

@MattHJensen #2473 does exactly as you say: It only creates citations for Tax-Calculator, includes those citations in the Jupyter Book documentation, and creates automation infrastructure to keep the citations updated.

**Comment by chusloj** [comment]
This issue was addressed in #2494 when the citations file was replaced with a manually-formatted `use_cases.md` markdown file. Closing.
