### ISSUE TITLE
Suggested edit on page /about/releases.html

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/Tax-Calculator#2477]
It would not let me suggest an edit without forking so I am opening an issue instead.

Last bullet under New Features -- "or the CBO’s" should be "for the CBO's"...

Great job on this. I am really eager to use it.

**Comment by MattHJensen** [comment]
Thanks @donboyd5! I've addressed this in #2487.

**Comment by donboyd5** [comment]
Thanks!
