### ISSUE TITLE
subprocess.py:1200: FileNotFoundError

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Tax-Calculator#2484]
@andrewjs00, a student at U of SC, is interested in contributing to Tax-Calculator.  To get him setup, he followed the [Contributor Guide](https://pslmodels.github.io/Tax-Calculator/contributing/contributor_guide.html).  When running the suite of tests, he had one failure:

```
C:\Users\andre\Anaconda3\envs\taxcalc-dev\lib\subprocess.py:1200: FileNotFoundError
=========================================================================================== short test summary info ============================================================================================
FAILED tests\test_4package.py::test_for_package_existence - FileNotFoundError: [WinError 2] The system cannot find the file specified
```

This appears to be specific to Windows machines.  I was unable replicate the error on a Mac, but did see others with similar issues where `subprocess` couldn't be located on a Windows machine when working with other packages (see [here](https://stackoverflow.com/questions/47847084/python-filenotfounderror-on-all-subprocess-calls) and [here](https://stackoverflow.com/questions/53619765/python-subprocess-filenotfounderror)).

Has anyone else had this issue on a Windows machine?  If so, what is the a solution?  

It looks like he should be fine to continue working (it only affects the test looking at whether the `taxcalc` package is installed), but I wanted to bring this to the attention of the Tax-Calc community since the contributor guide suggests checking that all tests pass before proceeding.

**Comment by MattHJensen** [comment]
@jdebacker, thanks for opening the issue. Very much looking forward to @andrewjs00 getting up and running. Welcome. 

I am curious if @donboyd5 or @ernietedeschi (both Windows users, I believe) have encountered this issue. I also have a Windows machine in storage that I may be able to get up and running to test this... will report back.

**Comment by jdebacker** [comment]
@donboyd5 @MattHJensen Any of you able to replicate this on a Windows machine?

**Comment by donboyd5** [comment]
Sorry I missed this back in September. I set taxcalc-dev up once with @MattHJensen guiding me on the phone and did not have that issue. I am alternating between two machines now and have not used Windows for this lately. I will try to set up a new taxcalc-dev environment and see what happens but it may take a week or so.

**Comment by duncanhobbs** [comment]
I updated Tax Calculator and set up a new taxcalc-dev environment. I ran the tests and they all passed without this subproccess.py error.

Here is my platform info.

  `platform win32 -- Python 3.8.5, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir: C:\Users\duncan.hobbs\Github\Tax-Calculator, configfile: pytest.ini, testpaths: taxcalc
plugins: forked-1.3.0, pep8-1.0.6, xdist-2.1.0`

**Comment by jdebacker** [comment]
Thank you @duncanhobbs and @donboyd5 for confirming that this was something specific to the original poster's machine.  Closing the issue.
