### ISSUE TITLE
Policy capabilities to analyze Biden tax proposals

### ISSUE THREAD

**Issue by codykallen** [PSLmodels/Tax-Calculator#2485]
The Biden campaign has proposed a handful of changes to the tax code. Some of these may require additional policy parameters to model properly. 

Unfortunately, I have not been able to locate a white paper or other detailed document from the campaign on its tax proposals. The best information I could find comes from TPC's analysis ([Appendix B](https://www.taxpolicycenter.org/sites/default/files/publication/158624/An_Analysis_of_Former_Vice_President_Bidens_Tax_Proposals_1_2.pdf)). 

In particular, I believe we need to add the capability to model the following provisions:
1) Phase out the QBI deduction for income over $400,000. 
2) Replace the deduction for contributions to IRAs and defined contribution pensions with a 26 percent refundable tax credit. 

Obviously, there are other provisions that would require information not available in the PUF to model.

If anyone else has already implemented such changes in other branches, it would be useful to incorporate them into the main version. If not, I'll do those myself.

@MattHJensen @Peter-Metz

**Comment by jdebacker** [comment]
@codykallen You might also look at the [AEI paper](https://www.aei.org/research-products/report/an-analysis-of-joe-bidens-tax-proposals/) on Biden's proposals (by @kpomerleau @rickecon, and me).  @erinmelly helped a great deal with the analysis, including doing some modifications of Tax-Calculator.  I think her lates work might be in [this branch](https://github.com/erinmelly/Tax-Calculator/tree/Biden).  Given the timing to get the paper out (and, I think, some differingviews on how to model some provisions), these changes were never fully incorporated into Tax-Calculator's master branch.

**Comment by kpomerleau** [comment]
@jdebacker and @codykallen, Erin and I had not chatted with anyone regarding incorporating these changes yet. Happy to walk through them and see if any could be used in the base model.

**Comment by codykallen** [comment]
@jdebacker @kpomerleau, Can we set up a call to discuss modeling Biden tax proposals?

**Comment by Peter-Metz** [comment]
@kpomerleau said:

>Erin and I had not chatted with anyone regarding incorporating these changes yet. Happy to walk through them and see if any could be used in the base model.

Let me know how I can be useful here. I think adding parameters/tax logic for Biden's proposals would be valuable and I'd be happy to help prepare the pull request.

Also, @codykallen note #2385 and PSLmodels/taxdata#319 for some additional challenges in modeling the QBI deduction

**Comment by codykallen** [comment]
A list of proposed individual income and payroll tax provisions and how to implement them or not:

1) individual income tax rates revert to their pre-TCJA values for taxable incomes above $400,000
 - Can be implemented by changing the `II_brk*`, `II_rt*`, `PT_brk*` and `PT_rt*` parameters.
 - Questions: Does that $400,000 depend on filing status? If so, is it $800,000 for married joint and widows, or $200,000 for single, married separate and head of household? Is it indexed for inflation?

2) itemized deductions begin to phase out at taxable incomes over $400,000
 - Can be implemented using Pease limitation. Same questions as for point 1.

3) the qualified business deduction begins to phase out at taxable incomes above $400,000
 - May require new policy parameters of `PT_qbid_pthd` and `PT_qbid_prt`.
 - Same questions as for point 1.

4) Cap itemized deductions at 28 percent of value.
 - I believe this can be implemented by setting `ID_BenefitCap_rt` to 0.28.

5) Tax capital gains and dividends at the same rate as ordinary income for taxpayers with over $1 million in income.
 - Can be implemented using `CG_brk3` and `CG_brk4`. 
 - Same questions as for point 1.

6) Tax unrealized capital gains at death.
 - Unless we have imputed unrealized capital gains and whether a taxpayer has died, I don't think we can model this.

7) Increase tax preferences for middle-income taxpayers’ contributions to 401(k) plans and individual retirement
accounts.
 - TPC assumes they replace the deductions with a 26% refundable tax credit. Implementing this would require adding a new tax credit and a credit rate parameter, and using the `ALD_KEOGH_SEP_hc` and `ALD_IRAContributions_hc` haircut parameters.

8) Provide automatic enrollment in IRAs for workers who do not have a pension or 401(k)-type plan.
 - Can't model.

9) Restore the full electric vehicle tax credit, target it to middle-income consumers, and prioritize the purchase of American-made vehicles.
 - Can't model.

10) Create a $5,000 tax credit for family caregivers of people who have certain physical and cognitive needs. 
 - I don't think we have enough information to model this.

11) Extend the earned income tax credit to workers age 65 and older without qualifying children
 - Can implement this using `EITC_MaxEligAge`.

12) Exclude student loan forgiveness from taxable income.
 - Not enough information to model.

13) Reinstate the solar investment tax credit. Reinstate tax credits for residential energy efficiency.
 - Can't model.

14) Apply the 12.4 percent Old-Age, Survivors, and Disability Insurance (OASDI) tax to earnings above $400,000.
 - Standard "donut hole" provision. Can implement using 

15) Provide a tax credit of up to $8,000 for child care.
 - Not enough information to model.

**Comment by kpomerleau** [comment]
@codykallen, Grant (my RA) and I are currently working on all of these (and more) for an update to our July Biden analysis and hoping to release it by October. We have a call each Tuesday and Thursday to discuss progress. If you would like to join to discuss any of this, we'd be happy to have you.

Alternatively, we can set up a broader phone call and include @Peter-Metz to discuss incorporating any changes we made for our July analysis into the base model.

**Comment by jdebacker** [comment]
Many/all of these capabilities have now been included in `taxcalc`.
