### ISSUE TITLE
Taxable income for BOTH Self employment AND W2 income

### ISSUE THREAD

**Issue by jeremybney** [PSLmodels/Tax-Calculator#2496]
I can't seem to figure out how to get a few of my own numbers to add up for a slightly different calculator I'm working on. 

https://turbotax.intuit.com/tax-tools/calculators/taxcaster/ 

If we enter $20,000 in wages and $4,000 in self employment income, why are deductions $13,227 and taxable income $10,773? I know that the deduction for Single is $12,200 (for 2019) but how do we calculate the additional $1,027? This discrepancy gets more exaggerated the more self employment income we add, but I can't figure out the rate of change.

If self employment income is $22,000 and W2 income is $3000 why are deductions $16,004? It was my understanding that deductions for self employment were comprised of taking self employment income x 92.35% x 15.3% and dividing this by 2 (only when self employment income was below $18,200 for Single).

Shouldn't the math just be taxable income = W2 income + self employment income - standard deduction - (self employment x .9235 x .153)?

All calculations assumes that status is 'Single' and that there is 1 dependent younger than 17 (i.e can claim the EITC and CTC).

**Comment by Peter-Metz** [comment]
Hi @jeremybney. Thanks for opening this issue. Would you mind sharing the code and input data you used to generate these numbers?

**Comment by jeremybney** [comment]
Hi Peter - I generated these numbers from the TurboTax link above, but I am looking to calculate these numbers on my own but cannot figure out the underlying math. 

I want me code to match the output of the TurboTax math, but right now it is not aligned:

#w2 income
comp = 1
#self employment income
comp_self = 20000
#depeendents
dependents = 1
#filing status
status = "Single"
#withholdings
withheld = 0

def complete(comp, comp_self, dependents, status, withheld):
    def tax_bracket_calculator(status, comp, withheld):
        if comp > 0:
            if status == 'Single' or status == 'Married Filing Separately':
                standard_deduction_sing = 12200
                
                taxable_income_sing = comp + comp_self - ((comp_self*0.9235*0.153)) - 12200
                #taxable_income_sing = comp + comp_self - (standard_deduction_sing + (comp_self*0.9235*0.153))
                #taxable_income_sing = comp + comp_self - (standard_deduction_sing + (comp_self*0.9235*0.153))
                print("taxable income")
                print(taxable_income_sing)
                #bracket 3 <-- 22% tax rate
                if 39476 <=taxable_income_sing <= 84200:
                    bracket_3 = ((taxable_income_sing - 39475)*.22)+(9700*.10)+((39475-9700)*.12)
                    refund_3 = withheld - bracket_3
                    return(refund_3)

                #bracket 2 <-- 12% tax rate
                if 9701 <= taxable_income_sing <= 39475:
                    bracket_2 = ((taxable_income_sing - 9700)*.12)+(9700*.10)
                    refund_2 = withheld - bracket_2
                    return(refund_2)

                #bracket 1 <-- 10% tax rate
                if taxable_income_sing <= 9700:
                    bracket_1 = (taxable_income_sing)*.10
                    refund_1 = withheld - bracket_1
                    return(refund_1)

            if status == 'Married Filing Jointly':
                standard_deduction_MFJ = 24400
                taxable_income_MFJ = comp + comp_self - standard_deduction_MFJ - (comp_self*.2567)
                #bracket 2 <-- 12% tax rate
                if 19401 <= taxable_income_MFJ <= 78950:
                    bracket_2_MFJ = ((taxable_income_MFJ - 19400)*.12)+(19400*.10)
                    refund_2_MFJ = withheld - bracket_2_MFJ
                    return(refund_2_MFJ)

                #bracket 1 <-- 10% tax rate
                if  taxable_income_MFJ <= 19400:
                    bracket_1_MFJ = (taxable_income_MFJ)*.10
                    refund_1_MFJ = withheld - bracket_1_MFJ
                    return(refund_1_MFJ)

            if status == 'Head of Household':
                standard_deduction_HoH = 18350
                taxable_income_HoH = comp + comp_self - standard_deduction_HoH - (comp_self*.2567)
                #bracket 2 <-- 12% tax rate
                if 13851 <= taxable_income_HoH <= 52850:
                    bracket_2_HOH = ((taxable_income_HoH - 13850)*.12)+(13850*.10)
                    refund_2_HOH = withheld - bracket_2_HOH
                    return(refund_2_HOH)

                #bracket 1 <-- 10% tax rate
                if taxable_income_HoH <= 13850:
                    bracket_1_HOH = (taxable_income_HoH)*.10
                    refund_1_HOH = withheld - bracket_1_HOH
                    return(refund_1_HOH)

    tax_bracket_calculator = tax_bracket_calculator(status, comp, withheld)
    money = int(tax_bracket_calculator) 
    estimated_federal_tax = round(withheld - money)
    print ('estimated_federal_tax')
    print(estimated_federal_tax)

    def self_employed_calculator(status, comp_self, withheld):
        if comp_self>0:
            if status == 'Single' or 'Head of Household' or 'Married Filing Separately':
                adjustment = comp_self*0.9235*0.153
                return(adjustment)
            if status == 'Married Filing Jointly':
                adjustment = comp_self*0.9235*0.153
                taxable_income_SE_MFJ = comp_self - adjustment -12200-(adjustment*.2)
                return(taxable_income_SE_MFJ)
    
    self_employed_calculator = self_employed_calculator(status, comp_self, withheld)
    print ('self employment')
    print(self_employed_calculator)

**Comment by Peter-Metz** [comment]
@jeremybney It looks like turbotax is treating the self-employment income as QBI, and therefore applying the 20% QBI deduction. Hope that helps

**Comment by jeremybney** [comment]
Can you please explain the equation for calculating taxable income for an individual (making less than $40K) who has BOTH self employment and W2 income? 

Shouldn't the math just be taxable income = W2 income + self employment income - standard deduction - (self employment x .9235 x .153)?

**Comment by Peter-Metz** [comment]
Here is my understanding of the three different deductions at play (if self-employment (SE) income is QBI):

1. Standard deduction: $12,200
2. SE deduction: SE income * .9235 * .153 * .5
3. QBI deduction: SE income * .2

So, taxable income would be: wages + SE income - deductions.

The relevant functions in the Tax-Calculator tax logic are [calcfunctions.EI_PayrollTax](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/calcfunctions.py#L92) for the calculation of SE tax and [calcfunctions.TaxInc](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/calcfunctions.py#L790) for the calculation of the QBI deduction. The input variable `k1bx14`, which is included in `e26270`, is an example of SE income that receives the QBI deduction.

**Comment by jdebacker** [comment]
@Peter-Metz Thanks for following up on this issue.  I believe you answered the original question, so I'm closing this.
