### ISSUE TITLE
Investigate why param docs didn't build after 3.0 release

### ISSUE THREAD

**Issue by MattHJensen** [PSLmodels/Tax-Calculator#2499]
Investigate why param docs didn't build after 3.0 release
https://github.com/PSLmodels/Tax-Calculator/pull/2495

**Comment by jdebacker** [comment]
@MattHJensen What is the status of this issue?  Is this true with the Jupyter Books docs and the current GH Action deployment?

**Comment by jdebacker** [comment]
All parameter docs look good to me.  Closing.
