### ISSUE TITLE
Do growfactors for dividends seem too growthy?

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/Tax-Calculator#2503]
Now that I have an approach to defining tax filers (#2501) that seems reasonable, I want to compare 2017 IRS reported statistics for tax filers to values for filers on the puf advanced to 2017 (stages 1 and 2 only). The goal is to reweight the puf where reweighting seems like it would usefully pull the file closer to the IRS. Thus, I am looking for large differences and then trying to decide whether weighting is an issue or whether growfactors are an issue.

In the case of dividends, I have a much greater amount of dividends in the advanced puf, filers only, than in the IRS statistics. It seems like growfactors might be an issue.

Here is a summary of values for ordinary and qualified dividends and how they changed between 2011 and 2017, from [IRS Publication 1304](https://www.irs.gov/statistics/soi-tax-stats-individual-income-tax-returns-publication-1304-complete-report).

![image](https://user-images.githubusercontent.com/6538392/97791185-e2968080-1ba5-11eb-8762-1ec024bee8e7.png)

Ordinary up 45.1%, qualified up 52.7%, in both cases driven primarily by growth in the average rather than growth in the number of returns.

Now, here is a comparison of the 2017 advanced puf to the 2017 IRS statistics:

![image](https://user-images.githubusercontent.com/6538392/97791293-44a3b580-1ba7-11eb-8881-68bf88cdee45.png)

Ordinary is 24.6% greater than the IRS and qualified is 14.7% greater, in each case driven by differences in the average and differences in the number.

If this is a weighting issue, I could reweight with new targets for dividends, but it seems like it might be a growfactor issue.

I calculated the relevant dividends growfactor from 2011 to 2017 by calculating cumulative growth using values for ADIVS, which is used in the function [`extrapolate`](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/records.py). I used values from [this file](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/growfactors.csv). The cumulative growth from 2011 to 2017 is 73.1%.

Thus, if I understand this properly, growfactors are increasing average dividends for both ordinary and qualified dividends by 73.1% even though the known average only increased by 43.0% and 46.5% respectively. We don't know how the number of dividend recipients would change because weighting affects that but I suspect that would drive the number of dividend recipients upward.

I am wondering why the growfactor for dividends has so much growth. Perhaps it is based on National Income and Product Accounts data? Here is a screenshot from the relevant [NIPA](https://apps.bea.gov/iTable/iTable.cfm?reqid=19&step=2) table with information on dividends included in personal income:

![image](https://user-images.githubusercontent.com/6538392/97791462-0d360880-1ba9-11eb-917b-8cbf4dd16c36.png)

If you do the calculation, you'll see that aggregate dividends in personal income are up 70.3%, which is a lot more than the growth in dividends in AGI in the IRS data (either measure). If we didn't have IRS data to inform dividend growfactors, it probably would make a lot of sense to use NIPA data to gain insight into how quickly dividends have grown.  But NIPA dividends are more than three times as large as AGI dividends, and include imputed dividends from pension funds, which are not taxed of course, and probably include a lot of other nontaxed items, so it may not be the best possible proxy for years for which we don't have dividends in AGI.

Anyway, I am wondering whether people knowledgeable about tax-calculator and taxdata think (a) I have analyzed this correctly (if not, I'd appreciate it if you point out where I am wrong), (b) whether the growfactors for dividends have too much growth between 2011 and 2017, and (c) if so whether it might be possible to adjust them in an upcoming iteration of tax-calculator and/or taxdata?

Many thanks for any thoughts you can offer on this.

**Comment by MattHJensen** [comment]
It is probably best for me to defer to the TaxData team for discussion here. (cc @andersonfrailey). 

But I did notice that the source of dividends growth rates in TaxData is identified as CBO in [this file](https://github.com/PSLmodels/taxdata/blob/308a2cfd8435b21a09b711df70adeb38adc2b274/puf_stage1/doc/Stage1_Growth_Rate_Sources.csv). I imagine CBO relies on NIPA. As a general matter, I don't notice SOI tables being used to generate growth rates at all. Perhaps that should be considered for dividends as well as other variables.

**Comment by andersonfrailey** [comment]
The growth factors partially come from the CBO, partially from the SOI. For 2011-2014, they're based on the actual SOI estimates for reported dividends, and then from there on they come from CBO projections. One way we could hopefully line up our projections with the IRS data is by updating the SOI estimates we use to the latest data. We haven't updated them recently because of some issues with the linear programming model being unsolvable with the new data, but now that we've changed up the stage 2 extrapolation it would be worth trying again.

**Comment by donboyd5** [comment]
That sounds great, @andersonfrailey. 

One issue @MattHJensen (also @martinholmer) and I have discussed is which IRS/SOI year should be the terminal year for SOI-based growfactors, and for also for stage 2 targeting. 

While 2018 is now available it may well be inappropriate for some or all variables because of (1) substantial changes in some IRC definitions due to TCJA, and (2) potential substantial behavioral responses to TCJA both in the short term (e.g., postponement of dividends from 2017 into lower-taxed 2018) and in the longer term (e.g., portfolio shifts from other forms of nonwage income into or out of dividends). I am sure short-term behavioral shifts occurred for some variables (e.g., the property tax deduction) although I am not at all sure it is true of dividends. I didn't see much evidence when I looked. There are also (lightweight) philosophical issues to consider - perhaps there are some kinds of behavioral shifts you want to capture in growfactors and some that you do not want to capture.

The safe thing to do in the short term might be to make 2017 the final year of SOI-based growfactors and to use another method for 2018 as a bridge year. The simplest approach to 2018 might be to assume taxable dividends grow like NIPA dividends. That raises two issues, of course: (1) definitionally NIPA dividends (and most NIPA concepts) are different from their tax counterparts -- for example, NIPA personal dividend income includes dividends from pension funds, imputed to individuals, but of course those are not taxed to individuals until many years in the future, and (2) they are measured differently as well (timing, accrual, etc.). For 2018 (and 2019 and 2020) it might be possible to exclude dividends from pension funds because data would be available, but for later years available forecasts probably would not be at that level of detail.

One simple approach to deal with the post-NIPA-data period might be to examine the relationship between SOI-based dividend growth in historical years (for which there were not major changes in definition or incentives) to overall NIPA dividends, econometrically. You probably would capture a long-term trend away from pension fund dividends due to the demise of defined benefit pensions, which might reasonably be expected to continue, leading to a further narrowing of differences between NIPA dividend growth and taxable dividend growth. Or you could just assume NIPA dividend growth rate is a good proxy for taxable dividend growth going forward.

**Comment by donboyd5** [comment]
A follow-up thought that I should have thought of earlier:

Using NIPA data as opposed to SOI data may not easily let  you abstract from IRC definitional changes and TCJA behavioral responses. Many NIPA data elements are deeply grounded in IRS tax data as a primary source. If BEA uses the 2018 SOI data as the primary source for NIPA non-pension personal dividends, then this is all very circular - using NIPA data in an effort to avoid SOI data may lead you right back to SOI data. So it probably makes sense to think through the philosophical questions first - which growfactors should be based on what actually happened (SOI data) and (1) do you want to adjust for definitional changes (probably yes, when (a) the income or deduction component is large, (b) the definitional change was large, and (c) external data are available that might allow an adjustment), (2) do you want to take into account transitory behavioral shifts (acceleration, deceleration, where large and where data allow) - personally, I would say this is a case of let it be - you want to capture what actually happened - but that's just my opinion, and (3) do you want  to take into account longer term behavioral shifts (portfolio adjustment, etc.) - my personal opinion is again, let it be. One kind of definitional change will be particularly hard to deal with - what do you do when it is not so much that the definition of an item changed, but the ability to observe data about it changed - for example, a lower amount of observable medical expense deductions due to fewer itemizers, and other similar kinds of changes? I suspect you've already got a principle to decide what you do about this. In a perfect world I imagine it would be to estimate the unobservable expense and let rules in Tax-Calculator decide the tax value. But it is hard to forecast what you can't observe.

**Comment by andersonfrailey** [comment]
Thanks for your comments, @donboyd5! I think a good first step is to go with your suggestion of updating our growth factors to use IRS data for up to 2017. I'll need to think more about using NIPA data before I can say anything too definite about the idea, but I'm definitely open to it.

**Comment by jdebacker** [comment]
Closing this issue here.  @donboyd5, if still relevant, you may want to move to the TaxData repo.
