### ISSUE TITLE
Is c18300 the tax-calculator variable most comparable to published IRS taxes-paid totals for 2017?

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/Tax-Calculator#2504]
**Seeking advice: Is c18300 the tax-calculator variable most comparable to published IRS taxes-paid totals for 2017?**

I think so, but am hoping someone more knowledgeable than me can confirm or correct. Thanks!

I am comparing various variables in the puf, as advanced to 2017 using stage 1 and stage 2 only, to their counterparts in published IRS summary statistics, for 2017, in preparation for reweighting the 2017 file.  IRS data generally are limited to tax filers and so I compare using only those puf records that appear to be filers, as described in #2501. I want to make sure that I target the appropriate puf variables using corresponding IRS data as targets.

For the state and local taxes itemized deduction, I want to compare and eventually target total taxes paid, before limitation. Here is a partial screenshot from IRS Table 2.1 for 2017:

![image](https://user-images.githubusercontent.com/6538392/97803869-08f60380-1c1a-11eb-955d-2df073135be7.png)

Total taxes paid are in columns BS and BT. They are broken down further into what they call state and local taxes (income and general sales), real estate, personal property taxes, and other taxes (not shown in the screenshot).

At least for now, I want to target total taxes paid amount and number (perhaps later adding subcategories because that could be useful in state targeting).

I believe the PUF variable that corresponds most closely to this concept is "c18300 Sch A: State and local taxes plus real estate taxes deducted (component of pre-limitation c21060 total)" (per [docs](https://pslmodels.github.io/Tax-Calculator/guide/output_vars.html)).

Here is a table that shows 2011-2017 growth in the IRS values, the relevant growfactor (ATXPY was used in [tax-calculator](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/records.py) to grow the components), and a comparison of the 2017 puf to the 2017 IRS values.

![image](https://user-images.githubusercontent.com/6538392/97803769-79e8eb80-1c19-11eb-9263-09edcf16b58e.png)

All in all, it doesn't look too bad. The average value in the IRS data grows 32.9% but the puf growfactor is only 22%, so I am not surprised that the weighted advanced puf comes up 5.4% short of the new average value. I consider this gratifyingly close, given how many things taxdata and tax-calculator do, and how hard it is to try to hit all important targets.

IF I have identified c18300 correctly as the relevant variable for comparison (**please confirm or correct if possible**) then I think my strategy will be:

- do an ad hoc adjustment to growth so that the average value grows by 32.9%, not 22% (I can't simply revise growfactors because the taxes-paid items don't have their own growfactor and I can't change ATXPY as that is used for many other variables and would have unintended side effects); I probably have to adjust growth for related variables e18400 and e18500 also (**comments on this much appreciated**)
- after that, target c18300 when reweighting

**Comment by MattHJensen** [comment]
`c18300` is the closest variable, but when using puf.csv, it doesn't include personal property taxes or other taxes from Sch A. 

Personal property taxes are not available in the original data ([data docs](http://users.nber.org/~taxsim/gdb/gdb11.pdf), pg A-9), and other taxes are dropped in TaxData [here](https://github.com/PSLmodels/taxdata/blob/52c02c5f457145413983762280f8c1552b5ac740/puf_data/finalprep.py#L360). (Other taxes only amounted to ~ $9,000,000 according to the data docs pg 47.)

> I probably have to adjust growth for related variables e18400 and e18500 also (comments on this much appreciated)

Yes, that's right. As a general matter you'll want to apply blowup factors to input variables rather than calculated variables. The calculated variables will be recalculated based on the input variables.
