### ISSUE TITLE
Is c19700 the best puf variable to link to IRS national contributions deduction total? If so, then its growfactor may not be growthy enough.

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/Tax-Calculator#2506]
**Is c19700 the best puf variable to link to IRS national contributions deduction total?**

I want to link the proper puf variable (with puf advanced to 2017 using stages 1 and 2, filers only, as generally discussed in issues #2501 through #2505) to IRS 2017 national totals for the contribution deduction, so that I can reweight the puf to target this variable and its number of nonzero values. (Ultimately I will target for each of 18 income ranges.)

Here is the relevant IRS summary for 2017:

![image](https://user-images.githubusercontent.com/6538392/97816334-8cd3de00-1c62-11eb-9a31-f72d0ad41b27.png)

I want to match against the total, in columns CU and CV.

I believe c19700 is the corresponding puf variable based on the [docs](https://pslmodels.github.io/Tax-Calculator/guide/output_vars.html). 

Relatedly, ATXPY appears to be the corresponding growfactor based on the [code](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/records.py), as it is used to grow e19800 Itemizable charitable giving: cash/check contributions and e20100 Itemizable charitable giving: other than cash/check contributions, both of which appear to be components of c19700.

Here is a table with growth in the IRS values, growth in ATXPY, and a comparison of the IRS 2017 values to the puf 2017 values.

![image](https://user-images.githubusercontent.com/6538392/97816263-0f0fd280-1c62-11eb-8af2-75c715f80310.png)

The average contribution grows by 46% but the growfactor only grows by 22%. Assuming I have in fact identified the correct puf variable to link to the IRS data, the lower growfactor growth may be the reason that the average value in the puf for 2017 is 18.8% below the average value in the IRS data for 2017.

IF I have identified the proper puf variable to link to the IRS data, then my reweighting strategy probably should be:

- First, make an ad hoc adjustment to charitable contributions  c19700, or perhaps both e19800 and e20100, by recalculating growth to reflect growth in the IRS averages. This is a fair amount of extra work, but probably is practical.
- Second, then reweight to hit/approximate targets.

**Thus, my questions are:
Is c19700 in fact the correct puf variable to link to IRS contributions total?
If so, does doing an outside-of-tax-calculator adjustment to e19800 and e20100 seem practical or are there hidden dangers?**

Many thanks.

**Comment by MattHJensen** [comment]
@donboyd5, `c19700` appears to be the right variable for your purposes. I recommend filtering by taxpayers with total itemized deductions (`c04470`) greater than zero, as it may be the case that `c19700` is positive for some taxpayers in the data even though they end up taking the standard deduction. The SOI table is only for itemizers. 

I don't anticipate any problem with establishing unique grow factors (or some other ad-hoc adjustment in 2017 for your purposes) for `e19800` and `e20100`. You will need want to adjust these inputs directly rather than `c19700.` `c19700` will be re-calculated from inputs every time you run the calculator.

**Comment by jdebacker** [comment]
Closing this issue here. @donboyd5, if still relevant, you may want to move to the TaxData repo.
