### ISSUE TITLE
iitax documentation appears to need updating:  Issue on page /guide/output_vars.html

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/Tax-Calculator#2514]
**Summary**
iitax is intended, according to how I read the code, to be all income taxes less refundable credits and less nonrefundable credits. In other words, the bottom line for income taxes (which can be negative).  However, the documentation, as I read it, does not correctly identify the fact that refundable credits are subtracted.

I think a simple fix (if I understand how Tax-Calculator documentation works) would be to edit the "desc" field of the [records_variables json file](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/records_variables.json) (screenshot below) to mention refundable credits.

![image](https://user-images.githubusercontent.com/6538392/101164683-6a3b3900-3603-11eb-8b21-6928a8b7f943.png)

I would offer that up as a PR but (a) I haven't yet bothered to learn how to do a PR, (b) it might be more complicated than I think - other changes might be required - for example, [this file](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/validation/CSV_OUTPUT_VARS.md) (1st screenshot below) appears to need manual updating, but I think [this one](https://raw.githubusercontent.com/PSLmodels/Tax-Calculator/master/docs/guide/output_vars.md) (2nd screenshot below) might (?) be code-generated and might not, and (c) the documentation could use further updating beyond 2016.

![image](https://user-images.githubusercontent.com/6538392/101165241-4c220880-3604-11eb-8f5e-d0b64741b914.png)
![image](https://user-images.githubusercontent.com/6538392/101165086-0f561180-3604-11eb-9fd8-956ed291a6a6.png)

**Details**
The [code for iitax](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/calcfunctions.py) is `iitax = c09200 - refund` where `c09200` is, according to documentation (and code) "Income tax liability (including othertaxes) after non-refundable credits are used, but before refundable credits" and `refund` is "Total refundable income tax credits".  Function for `iitax` and `refund` is:

![image](https://user-images.githubusercontent.com/6538392/101166148-d159ed00-3605-11eb-9945-9309c2b947f4.png)

The relevant function for `c09200` is:

![image](https://user-images.githubusercontent.com/6538392/101162932-00219480-3601-11eb-9c99-46e2955c7121.png)

However, the documentation for iitax says:

![image](https://user-images.githubusercontent.com/6538392/101161872-86d57200-35ff-11eb-9291-0e14a1a4104b.png)

I think this is not correct. It says start with 1040 line 63 and subtract lines 57 and line 62a. Here is a screenshot of the relevant part of the 1040 for the latest year referenced, 2016:

![image](https://user-images.githubusercontent.com/6538392/101163581-cbfaa380-3601-11eb-95e7-0e5c8dc2f47a.png)

Line 63, as I read the form, is total taxes (including the self-employment tax and add-on Medicare tax). Line 57 is self-employment tax and line 62a is the additional Medicare tax from Form 8959. Non-refundable credits are subtracted in arriving at line 56, which is an input to line 63. However - and this is the key - refundable credits are not subtracted in the calculation the documentation gives. They are subtracted in the "Payments" section - for example, line 66a for the EITC and line 67 for the additional child tax credit. Thus, I think the documentation needs to be modified to say this and to be clear that the concept is total income taxes (less SE tax and Medicare) after all credits, including refundable credits.

**Comment by jdebacker** [comment]
Closed via PR #2592.
