### ISSUE TITLE
AGI increases under TCJA in 2018, the excess business loss rule, and possible implications for Tax-Calculator and taxdata

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/Tax-Calculator#2516]
**Summary**

This is related to #2513.

In a project related to the TCJA and New York with @MattHJensen, I have learned that Tax-Calculator causes AGI to increase substantially in puf.csv relative to prior law. I believe it is a result of the TCJA's business loss rule. The increases are especially pronounced among AGI millionaires and negative-AGI returns. 

This raises several issues that might make sense to explore and address:

- The losses available to be capped, embedded in puf.csv, may be too large, which could mean that growfactors are too large, or that stage 2 weighting inadvertently weighted large-loss records too much, or that the economy changed in ways that cannot be easily captured by growfactors and weighting. I suspect the first and third reasons. (I give two ways of looking at this below - a comparison to JCT that suggests they may not be too high, and a comparison to reported Historical Table 2 data, which suggests they may not be too high.)
- On the other hand, the losses available to be capped may be plausible in taxdata, but people may have changed their behavior in ways that avoided or evaded the rule, in which case it might make sense to have a behavioral lever that allows implementing this behavior.
- Limited losses can be carried forward. If they are as large as the data suggest, it implies that maybe taxdata should have a provision to create a pool of unused prior excess business losses.
- The [CARES act retroactively suspended the excess business loss rule](https://www.pkfod.com/insights/changes-to-the-excess-business-loss-provisions-in-the-cares-act/) back to 2018, through 2020, which means people can amend their returns for 2018 and 2019 and get refunds. It would be in effect again for 2021 through 2025. This raises a philosophical question about what to do in Tax-Calculator - undo the rule, or not, for 2018 and 2019, and what to do about 2020? An option to disallow might make sense; in any event it probably needs explicit thought.

**Details**
The first table below shows 2017 law and 2018 law calculated using Tax-Calculator applied to puf.csv advanced to 2018. *(Note: The qbid limit is NOT set to false in TCJA.json.)* AGI under 2018 law is $70.7 billion higher than under 2017 law. We can break it into three components: (1) minor changes to Social Security in AGI, (2) limits on above-the-line adjustments, (3) and the majority of the effect, driven by whatever affects the mysterious ymod1:

![image](https://user-images.githubusercontent.com/6538392/101916747-5ceaf500-3b95-11eb-96c0-42a73907363b.png)

The next table shows that the $70.3 billion increase is predominantly in the highest and lowest AGI ranges. This, presumably, is related to the millionaire increases discussed in #2513. I use ranges used in SOI Historical Table 2 because this is based on work I am doing in relation to that and is convenient:

![image](https://user-images.githubusercontent.com/6538392/101916952-a1769080-3b95-11eb-90fc-6ab2eac9b9eb.png)

This led to a search for (a) large changes between 2017 law and 2018 law in big items that might be embedded in ymod1, and (b) large values for other items even if they did not change, especially for very high and very low agi records. I sorted records by how much AGI changed between the two laws, and then within a record I sorted variables according to whether they were important concepts (AGI is at the top) or whether their values were large. 

Here are a few important variables to pay attention to:

![image](https://user-images.githubusercontent.com/6538392/101918452-61b0a880-3b97-11eb-8953-889d706ac055.png)

Here is information about the record with the biggest AGI change between the two laws:

![image](https://user-images.githubusercontent.com/6538392/101918645-991f5500-3b97-11eb-8fd9-f4767dac9693.png)

It's pretty clear that its large AGI change is related to its large e00900 business loss, even though the loss was the same under the two laws.

The agi change on the second-largest agi-change record is pretty clearly related to its large e02000 rent/royalty... loss.

![image](https://user-images.githubusercontent.com/6538392/101918865-e3083b00-3b97-11eb-96a4-80e898f70826.png)

Same for the third largest change:

![image](https://user-images.githubusercontent.com/6538392/101919111-34182f00-3b98-11eb-9949-b87ce2e112b0.png)

Many additional records showed similar things. This was enough to figure out that large losses were a major cause and the internet filled in the rest - this appears to be the result of TCJA's excess business loss limit as mentioned at the start.

This raises several questions:

First, are the losses we have in the data too large?

JCT estimated the impact of this provision as about a $16 billion increase in FY 2019 after it was up and running. With puf.csv, I estimate it raises iitax by $11.5 billion (counter to my initial expectation, this is less than JCT estimated):

![image](https://user-images.githubusercontent.com/6538392/101921191-b7d31b00-3b9a-11eb-8fbf-8ac20e559f2f.png)

So this seems comforting. But one last bit of information, which is less comforting. The table below shows iitax calculated under 2017 law and TCJA, and also an estimate of actual iitax in 2018 constructed from reported Historical Table 2 data. Here, we have $58 billion more iitax among millionaires than was reported. Of course people's behavior may have changed in ways that caused actual tax to be lower, or we may simply have capped losses too m uch. I suspect the latter.

![image](https://user-images.githubusercontent.com/6538392/101924083-37aeb480-3b9e-11eb-9195-462645cccaf3.png)

**Comment by MattHJensen** [comment]
Hi @donboyd5, thanks a lot for investigating this issue and reporting what you found! 

> The CARES act retroactively suspended the excess business loss rule back to 2018, through 2020, which means people can amend their returns for 2018 and 2019 and get refunds. It would be in effect again for 2021 through 2025. This raises a philosophical question about what to do in Tax-Calculator - undo the rule, or not, for 2018 and 2019, and what to do about 2020? An option to disallow might make sense; in any event it probably needs explicit thought.

To handle this specific part of the issue, my initial reaction is to undo the rule for 2018, 2019, and 2020, justified by Tax-Calculator's general intention to calculate and report liabilities rather than receipts in a given year. We could achieve this by changing the baseline values for the `ALD_BusinessLosses_c` [here](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/policy_current_law.json#L1086). Users who wish alternative behavior could modify baseline parameter values as part of their calculator setup. 

@donboyd5, does this make sense to you? Does anyone else have a view on it?

**Comment by jdebacker** [comment]
This looks like an issue for TaxData.  Closing this issue here. @donboyd5, if still relevant, you may want to move to the TaxData repo.
