### ISSUE TITLE
Recipe on extracting MTRs and ETRs

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2517]
Currently recipes only cover using `Behavioral-Responses` to adjust labor supply directly. It'd be nice to also have an example of extracting MTRs and ETRs, and maybe plotting them like in CS.

**Comment by jdebacker** [comment]
@MaxGhenis I'm happy to add this.  Do you view it as a separate recipe or just and extension of the "Basic Recipe" (recipe00)?

**Comment by jdebacker** [comment]
Closing due to lack of interest.  Recipe 4 also shows how to extract MTRs.
