### ISSUE TITLE
Additional standard deduction for blind and aged

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Tax-Calculator#2520]
The "Additional standard deduction for blind and aged", `STD_Aged` for 2013 for widowed is set to 1,500 [here](STD_Aged).

But the way I read [IRS Publication 501](https://www.irs.gov/pub/irs-prior/p501--2013.pdf), `STD_Aged`= 13,400 (from Table 7) - 12,200 (from Table 6) = 1,200.

My question is: am I doing the calculation of this parameter correctly (in which case we need to change the default value)?

cc @MattHJensen

**Comment by MattHJensen** [comment]
@jdebacker, thanks a lot for finding and reporting this. Your calculation appears correct to me, and it looks like the problem for widowed+aged/blind taxpayers extends to other years than 2013. I am adding a bug label here.

**Comment by jdebacker** [comment]
Addressed in PR #2537.
