### ISSUE TITLE
Update to Python 3.9

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2521]
Python 3.9 was launched on 2020-10-05, conda only has up to 3.8: https://anaconda.org/pslmodels/taxcalc/files

**Comment by MaxGhenis** [comment]
@MattHJensen could this get pushed to conda with taxcalc's next release?

**Comment by MattHJensen** [comment]
> @MattHJensen will the next release be pushed to conda?

Yes, it will be pushed to conda.

**Comment by jdebacker** [comment]
Closed with PR #2522.
