### ISSUE TITLE
Remove or update "Upgrading to Tax-Calculator 2.0" documentation page

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2523]
This is highlighted in the `About` section: https://pslmodels.github.io/Tax-Calculator/about/upgrading.html

taxcalc 2.0 was launched on 2019-04-15, 3.0 was launched 2020-08-24

**Comment by MattHJensen** [comment]
Good catch, @MaxGhenis. This handles specific issues with upgrading from 1.0 to 2.0 that aren't present from 2.0 to 3.0. I'm in favor of removing it.

**Comment by jdebacker** [comment]
Closed via PR #2592.
