### ISSUE TITLE
CDCC_c parameter validators

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Tax-Calculator#2527]
The `CDCC_c` parameter (for the maximum child & dependent care credit per dependent) has a default value of $3,000 and it's indexable.  But the max value is also $3,000, so just accepting the default and indexing the value leads to a parameter validation errors beyond the base year of the model. 

Is there a reason that the maximum acceptable value for this parameter is equal to the default value?

**Comment by Peter-Metz** [comment]
>Is there a reason that the maximum acceptable value for this parameter is equal to the default value?

@jdebacker I believe the reason that the max value for `CDCC_c` is $3,000 is that `e32800` (child care expenses) is capped at $3,000 in the PUF and the CPS (although I think taxdata still extrapolates `e32800`, so there might be values bigger than $3,000 beyond the base year).

>so just accepting the default and indexing the value leads to a parameter validation errors beyond the base year of the model.

I agree that this behavior is not desirable. Short of imputing child care expenses in taxdata, I think it may make sense to switch `indexable` to `false` for `CDCC_c`

cc @MattHJensen

**Comment by MaxGhenis** [comment]
Looks like `taxdata` [imputes](https://github.com/PSLmodels/taxdata/blob/535a4e4c72c6e80dbcd47055ba8a45d76ca897b0/taxdata/cps/impute.py#L153) childcare expenses from the PUF to the CPS, but the CPS has childcare columns that could be used directly (per [documentation](https://www2.census.gov/programs-surveys/cps/techdocs/cpsmar20.pdf)): 
* `SPM_ChildcareXpns`: "SPM unit's child care expenses-not capped"
* `HCHCARE_VAL`: "Annual amount paid for child care by household members"

To the extent that SPM (Supplemental Poverty Measure) units and households don't align with tax units, the expenses could be split across adults and then reaggregated.

**Comment by jdebacker** [comment]
The limit for `CDCC_c` was changed to `9e+99` in PR #2573.
