### ISSUE TITLE
CARES Act changes to tax law

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Tax-Calculator#2543]
It appears that some of the provisions of the [CARES Act](https://files.taxfoundation.org/20200325223111/FINAL-FINAL-CARES-ACT.pdf) are not included in the `policy_current_law.json` or in the logic of the Tax-Calculator.

For example, per the Act, the ceiling for charitable deductions (`ID_Charity_crt_all`) was raised to 100% in 2020.  Also, charitable contributions are an above the line deduction (up to $300) for those who take the standard deductions (which would require modification of the `calcfunctions.AGI()` function).

**Comment by MattHJensen** [comment]
More useful references. 
https://www.jct.gov/publications/2020/jcx-12r-20/
https://www.jct.gov/publications/2020/jcx-24-20/

**Comment by jdebacker** [comment]
@MattHJensen I've started to put more thought on this.  Perhaps the above the line deduction for itemizers with charitable contributions is best handled in the `calcfunctions.StdDed()` function.

**Comment by jdebacker** [comment]
It appears PR #2556 left out the largest tax provision, the relief checks, which were structured as refundable tax credits.  This provision could be added based on the RRC parameters and logic added in PR #2573.

**Comment by jdebacker** [comment]
The recovery rebate credit in the CARES Act provided a refundable income tax credit of $1,200 for single filers and $2,400 for joint filers, with an additional $500 per qualifying child.  

The credits phase out at a rate of 5% at AGI above $150,000 for joint filers, $112,500 for head of household filers., ad $75,000 for others.  The credit is thus zero for joint filers with no children at $198,000 AGI and for a single filers at $99,000 of AGI.

cc @amshoulders

**Comment by jdebacker** [comment]
To model the recovery rebate credit in the CARES Act, we should probably try to build off of the RRC parameters introduced in PR #2573.  

We can use the phaseout start parameter: `"RRC_ps": [75000, 150000, 75000, 112500, 75000]`

Since the phaseout end would depend on the number of qualifying children, we should introduce a phaseout rate, perhaps called `RRC_prt`, which would equal 0.05 and set `RRC_pe` equal to 0.

I'm not sure if we'd want to use the `RRC_c` parameter (and make it conditional on `MARS`) or create a new parameter.  It maybe easier to create a new parameter `RRC_c_unit` for the maximum credit for the filing unit (before taking into account qualifying children).

We would need a new parameter like `RRC_c_kids` for the credit amount for qualifying children.

The logic in `calcfunctions.PersonalTaxCredit()` would become something like:

```
...
# calculate Recovery Rebate Credit from ARPA 2021
    if c00100 < RRC_ps[MARS - 1]:
        recovery_rebate_credit = RRC_c * XTOT
        recovery_rebate_credit = RRC_c_unit[MARS-1] + RRC_c_kids * nu18
    elif c00100 < RRC_pe[MARS - 1] & c00100 > 0:
        prt = ((c00100 - RRC_ps[MARS - 1]) /
               (RRC_pe[MARS - 1] - RRC_ps[MARS - 1]))
        recovery_rebate_credit = RRC_c * XTOT * (1 - prt)
    else:
        recovery_rebate_credit = max(0, recovery_rebate_credit - RRC_prt * (c00100 - RRC_ps[MARS-1]))
...
```

**Comment by jdebacker** [comment]
This was finally finished off with RP #2586.  Thanks @amshoulders!
