### ISSUE TITLE
"Extra additional child tax credit" from Biden plan

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2545]
Biden's child tax credit expansion requires additional parameter(s) in taxcalc. [These tweeted charts](https://twitter.com/MattBruenig/status/1358473009850437633) show how the trapezoid-to-waterslide transformation works, and the thread they're in explains it.

(Semi-tongue-in-cheek suggested name from [Scott Greenberg](https://twitter.com/ScottElliotG/status/1358449971167711235))

![image](https://user-images.githubusercontent.com/6076111/107181090-f9abf200-698e-11eb-8866-c4733a4f84b6.png)
![image](https://user-images.githubusercontent.com/6076111/107181102-fd3f7900-698e-11eb-9ad9-8a118b099d2e.png)

**Comment by MattHJensen** [comment]
Waterfall! Great name.

**Comment by MaxGhenis** [comment]
This will be addressed by #2573
