### ISSUE TITLE
Allow for refundable CTC with phase-out and no phase-in

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2547]
This is the structure of [Romney's Family Security Act](https://www.niskanencenter.org/wp-content/uploads/2021/02/Analysis-of-the-Romney-Child-Allowance_final.pdf), which has no phase-in and phases out at 5% above $200k/$400k.

@thirdhuman

**Comment by MaxGhenis** [comment]
Per @Peter-Metz, this might be achievable by raising the maximum phase-in to infinity.

**Comment by Peter-Metz** [comment]
It occurred to me that this approach probably wouldn't work for filers with no income...

**Comment by MaxGhenis** [comment]
This is now more fully fleshed out in #2571, and will be addressed by #2573.
