### ISSUE TITLE
Update docs URL to tax-calculator.pslmodels.org

### ISSUE THREAD

**Issue by hdoupe** [PSLmodels/Tax-Calculator#2549]
We've discussed using `tax-calculator.pslmodels.org` (or `taxcalc.pslmodels.org`) as the domain name for the Tax-Calculator documentation. I think we should go ahead and do this so that we have an easier to type and remember domain name.

The current URL for the docs is `pslmodels.github.io/Tax-Calculator/`. I feel like this is kind of unwieldy and if I start typing "tax" into my search bar is unlikely to come up.

If we decide to do this, then I'm happy to make the updates on Cloudflare.

Note: the `https://pslmodels.github.io/Tax-Calculator/` url would continue to work.

**Comment by jdebacker** [comment]
Updated URL to https://taxcalc.pslmodels.org  -- thanks Hank!
