### ISSUE TITLE
Release notes for next taxcalc release

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Tax-Calculator#2550]
I think we are due to have a new release of the `taxcalc` package.  Please post updates for the release notes here.  I'll keep a list of unique additions in this comment.

**API Changes**

**New Features**
* Package available for Python 3.9 (#2522 by Max Ghenis)
* Parameters for QBI deduction phaseout (#2508 by Peter Metz)
* Allow interaction with `calcfunctions.py` functions and unit tests without `@jit` decorator (#2515 by Jacob Chuslo)

**Bug Fixes**
* Fix default parameter value for deduction for blind and aged widowed taxpayers -- does not affect results for `puf.csv` or `cps.csv` users.  (#2537 by Jacob Chuslo)
* Include self-employment tax in calculation of partnership-specific marginal tax rates (#2486 by Cody Kallen)
* Fix stacking of an optional capital gains tax bracket (#2500 by Peter Metz)
* Fix bug caused by adjusting the indexed status of a parameter while also adjusting the parameter's value and a related parameter's value. (#2532)

Also, changes to make compatible with latest versions of dependencies.

cc @MattHJensen @MaxGhenis @Peter-Metz @andersonfrailey @chusloj 

edited to include comments from @MattHJensen

**Comment by MattHJensen** [comment]
@jdebacker, thanks a lot for putting this together. A few comments so far: 

The API Changes section has been devoted to breaking changes in the past, so I believe #2515 should be under New Features instead. 

I find it helpful to be a little more descriptive in bug fixes. Many only end up affecting a tiny slice of the user base, and it is nice for someone to know whether it affects them without worriedly clicking through to the PR. So, perhaps:  

- Fix default parameter value  for deduction for blind and aged widowed taxpayers -- does not affect results for puf.csv or cps.csv users. 
- Include self-employment tax in calculation of partnership-specific marginal tax rates 
- Fix stacking of an optional capital gains tax bracket

**Comment by hdoupe** [comment]
@jdebacker thanks for kicking this off:
- Fix bug caused by adjusting the indexed status of a parameter while also adjusting the parameter's value and a related parameter's value. (#2532)

**Comment by jdebacker** [comment]
The above was included in the release notes for 3.1.0.  Closing.
