### ISSUE TITLE
issue with calculation of capital gains, line 33

### ISSUE THREAD

**Issue by nzwiefel** [PSLmodels/Tax-Calculator#2551]
Hi folks, I'm from TPC and working in the synthetic data project on the INSOLE that I think some of you have advised on.

We're using a forked version of TaxCalc to derive some values post synthesis, and I believe I've caught an issue with how TaxCalc calculates CG taxes. I noticed this when trying to match CG totals from the tax calculator to the CG totals I have access to in our source data set for synthesis. 

The issue occurs on line 1015 of calcfunctions.py:

` dwks33 = min(dwks9, e24518)`

The 2013 instructions for schedule d say to insert the minimum of either line 9, or Schedule D, line 19. Schedule D, line 19 in 2013 refers to line 18 of unrecaptured section 1250 gain worksheet, which is actually listed as E24515 in the PUF documentation.

Unless I'm misunderstanding something, I believe that line should become:

` dwks33 = min(dwks9, e24515)`

This change addressed the issues I was having with schedule d liabilities. I didn't see any open issues about this, and I still see the offending code in the master branch. Just wanted to bring this up in case this is actually an issue and not something I'm just confused about.

**Comment by feenberg** [comment]
On Thu, 11 Feb 2021, nzwiefel wrote:

> 
> Hi folks, I'm from TPC and working in the synthetic data
> project on the INSOLE that I think some of you have advised on.
> 
> We're using a forked version of TaxCalc to derive some values
> post synthesis, and I believe I've caught an issue with how
> TaxCalc calculates CG taxes. I noticed this when trying to
> match CG totals from the tax calculator to the CG totals I have
> access to in our source data set for synthesis.
> 
> The issue occurs on line 1015 of calcfunctions.py:
> 
> dwks33 = min(dwks9, e24518)
> 
> The 2013 instructions for schedule d say to insert the minimum
> of either line 9, or Schedule D, line 19. Schedule D, line 19
> in 2013 refers to line 18 of unrecaptured section 1250 gain
> worksheet, which is actually listed as E24515 in the PUF
> documentation.
> 
> Unless I'm misunderstanding something, I believe that line
> should become:
> 
> dwks33 = min(dwks9, e24515)

This line corresponds exactly to the SAS code from which the OSPC Python 
code derives, and which was tested against the confidential data. So I am 
pretty sure you are correct in this change.

Daniel Feenberg

**Comment by jdebacker** [comment]
@nzwiefel Thanks for bringing this issue up! I've opened a PR that I think addresses it: PR #2553

**Comment by MattHJensen** [comment]
Resolved by #2553.
