### ISSUE TITLE
Asymmetric treatment of alimony

### ISSUE THREAD

**Issue by codykallen** [PSLmodels/Tax-Calculator#2552]
Our measure of expanded income includes alimony received but does not subtract alimony paid. Shouldn't expanded income treat these two symmetrically?

**Comment by jdebacker** [comment]
@codykallen I see the double counting issue.  Though one could argue this is a form of consumption, I suppose.

@MaxGhenis has thought a lot about income measures and household well-being.  Any thoughts @MaxGhenis?

**Comment by MaxGhenis** [comment]
Interesting, the [Supplemental Poverty Measure](https://www.census.gov/content/dam/Census/library/publications/2020/demo/p60-272.pdf) counts alimony and child support received as income, and (unlike the Official Poverty Measure) subtracts child support paid from income, but doesn't mention subtracting alimony paid from income. So I think they view it as consumption as Jason said.

**Comment by jdebacker** [comment]
@codykallen I'm going to close this issue for now.  Please feel free to reopen if there's a particular problem that needs to be addressed.  But I find some reassurance that Tax-Calculator is consistent with other sources such as Census (even if their can be disagreement about how to could alimony.

@MaxGhenis Thanks for chiming in here.
