### ISSUE TITLE
Simplify contributor guide with GitHub CLI

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2559]
The [GitHub CLI](https://cli.github.com/) simplifies steps 4-8 in the [contributor guide](http://taxcalc.pslmodels.org/contributing/contributor_guide.html#setup-git), i.e. you could just do:
```
gh repo fork PSLmodels/Tax-Calculator
```
It will ask you if you want to clone it, and you can say yes. This forks, clones, and I think also adds the upstream remote.

I think authenticating through the GitHub CLI also saves credentials (replaces step 3) with less headache. It'd be good to confirm this with a new user.

**Comment by jdebacker** [comment]
@MaxGhenis Thanks for this suggestion.  For new users (and for myself), I still prefer the methods suggested in the guides, even if it does require a few more clicks.
