### ISSUE TITLE
ARPA provisions

### ISSUE THREAD

**Issue by codykallen** [PSLmodels/Tax-Calculator#2571]
The following comments will list the various tax-related (and several other) provisions in the recently enacted American Rescue Plan Act of 2021, as well as how to potentially model them.

Full text: https://www.congress.gov/117/bills/hr1319/BILLS-117hr1319enr.pdf

JCT score: https://www.jct.gov/publications/2021/jcx-14-21/

CBO score: https://www.cbo.gov/publication/57056

TPC distributional results: https://www.taxpolicycenter.org/model-estimates/american-rescue-plan-act-2021-final-version-passed-senate-and-house-march-2021/t21-0

**Comment by codykallen** [comment]
**Recovery Rebate Credit**

These are the $1,400 "stimulus" payments. These are structured as fully refundable tax credits, which apply only in 2021. They are set at $1400 per person in the tax unit (same variable as for the personal exemption), and they phase out per the following:
 - For single or married separate filers, on AGI between $75,000 and $80,000.
 - For heads of household, on AGI between $112,500 and $120,000.
 - For married joint and widowed filers, on AGI between $150,000 and $160,000.

Nonresident aliens and dependent filers are not eligible. (Dependent filers are included in the return claiming them as a dependent.) 

The credit is fully refundable. 

Implementing this requires adding 3 variables: the maximum credit amount, the phase-out threshold, and the phase-out regions ($5000, $7500 and $10000). 

Note that the phase-out process uses a phase-out window, rather than a phase-out rate. This makes it incompatible with the personal refundable credit logic.

**Comment by codykallen** [comment]
**Exclusion of Unemployment Insurance**

The relevant provision: 

> In the case of any taxable year beginning in 2020, if the adjusted gross income of the taxpayer for such taxable year is less than $150,000, the gross income of such taxpayer shall not include so much of the unemployment compensation received by such taxpayer (or, in the case of a joint return, received by each spouse) as does not exceed $10,200.

There is no phase-in or phase-out for this. How this will be implemented seems ambiguous. I believe the implied calculation is that if AGI < $150,000, then only unemployment benefits below $10,200 should be subtracted from pre-QBID taxable income. 

The actual rule would allow up to $10,200 to be subtracted for each spouse for joint filers (although the $150,000 would not change). However, we only have the filing unit's overall UI benefits, not benefits per spouse. Therefore, I propose to ignore this part of the provision.

**Comment by codykallen** [comment]
**Child Tax Credit expansion**

The CTC is made fully refundable. The maximum credit amount is raised to $3,000 per child 6 and over and $3,600 for children under 6. 

The expansion beyond the current $2,000 phases out for modified AGI over $75,000 for single and married separate filers, $112,500 for heads of household, and $150,000 for joint and widowed filers. 

Eligibility is also extended to children 17 years old. 

This is also extended to U.S. possessions. 

Because this expansion phases out at a different income threshold than the existing part of the CTC, implementing this will require new policy parameters. We will also need to add a parameter for whether 17-year-olds are eligible, which would involve using `nu18` instead of `n24`. We would also need to add a parameter for whether the CTC is fully refundable; if it is, the ACTC should get set to zero, and the CTC  logic would be moved from the `NonrefundableCredits` function to the `CTC_new` function. I don't think the `CTC_new` policy parameters are capable of modeling this provision, but could use a second opinion on this.

**Comment by codykallen** [comment]
**Child and Dependent Care Credit expansion**

ARPA made the CDCC fully refundable. It raised the maximum expenses eligible for the credit from $3,000 to $8000 (if caring for two or more people, this limit rose from $6,000 to $16,000). 

Under pre-ARPA law, the credit rate is initially set at 35%, and it phases down to 20%. The phase down reduces the credit rate by 1 percentage point per $2,000 of AGI over $15,000. ARPA raises this initial credit rate to 50%, and this phases down to 20% using the same rate but on income over $125,000. ARPA then has this rate phase down to zero (again, at the same rate) for AGI over $400,000. 

These provisions are also extended to U.S. possessions, but we can ignore this. 

The extension to U.S. possessions is permanent, but the other provisions only apply for 2021.

In Tax-Calculator, the 20% minimum rate and the phase-down rate (1pp per $2000) are hardcoded; these should be policy parameters. Implementing the second phase-down will require a new policy parameter (or maybe 2).

**Comment by codykallen** [comment]
**Extension of pass-through loss limitation**

The TCJA limited deductions of losses from noncorporate business to $250,000 ($500,000 for joint filers). Like the other individual income tax provisions, this was set to expire in 2026. 

ARPA extends this limitation for 2026 and 2027.

**Comment by codykallen** [comment]
**Other individual income tax provisions we lack data to model**

Federal student loan debt forgiven between 2021 and 2025 is excluded from gross income.

Credits for sick leave and family leave for self-employed individuals.

**Comment by codykallen** [comment]
**Business and employer provisions (not modeled)**

- Employer payroll tax credit for premium assistance for COBRA continuation
- Extension and modification of credit for paid sick and family leave
- Extension of employee retention tax credit
- Repeal of worldwide interest allocation rules
- Expansion of 162(m) (million dollar rule)
- Increases the limit for dependent care assistance program from $5k to $10k for 2021.

**Comment by codykallen** [comment]
List of new parameters to add:
- RRC_c, RRC_ps, RRC_pe
- UI_em, UI_pthd, UI_prt
- CTC_include17, CTC_refundable, CTC_c_ARPA, CTC_c_under6_ARPA, CTC_ps_ARPA
- CDCC_refundable, CDCC_frt, CDCC_prt, CDCC_ps2

**Comment by MattHJensen** [comment]
@codykallen, thanks a lot for this overview and the followup PR(s) you are working on today/tomorrow. Everything here make sense to me. I may nitpick parameter naming after seeing everything implemented in a PR, but your suggestions seem like a good place to start. 

I'd also like to flag this issue and its forthcoming matching PR(s) for @grantseiter, @MaxGhenis, @thirdhuman, @ernietedeschi, and @kpomerleau, as they may have been thinking about these aspects of taxcalc over the recent weeks.

**Comment by codykallen** [comment]
To implement the CTC provisions, I think I can just use the `CTC_new` logic with only minor additions. We would need to add two indicator variables: one for whether the regular CTC is fully refundable (which gets around the issue of phasing in when filers have zero income), and one for whether to include 17-year-olds (use `nu18` instead of `n24`). 

With those provisions, the CTC expansion could be implemented by setting `CTC_new_c` to $1000, `CTC_new_c_under6_bonus` to $600, `CTC_new_ps` to their relevant thresholds (see  comment above), `CTC_new_prt` to 0.05, and `CTC_new_refund_limited` to be false. 

Implementing the CTC refundability part would require some additional changes. We would need to prevent it from limiting other nonrefundable credits in the `NonrefundableCredits` function and from being included among them in the `C1040` function, and including it among the refundable credits in the `IITAX` function. Implementing the changes to the CTC function may be trickier, as the law is ambiguous on the interaction between the CTC refundability and the ODC.

**Comment by codykallen** [comment]
Correction to the description of the limitation on pass-through business losses. The extension is only for 2026. The law only resets the expiration date by one year.

**Comment by codykallen** [comment]
Correction to the description of the EITC expansion. The higher investment income limit for claiming the EITC is a permanent change, not a temporary one.

**Comment by codykallen** [comment]
[ARPA revenue comparison.xlsx](https://github.com/PSLmodels/Tax-Calculator/files/6137620/ARPA.revenue.comparison.xlsx)

This excel file provides a comparison of the estimated revenue effects using the changes made in PR #2573 and the json in examples PR [#4](https://github.com/PSLmodels/examples/pull/4). 

For the extension of the noncorporate loss limitation to 2026, Tax-Calculator estimates a revenue increase of $15.2 billion in 2026, whereas JCT estimates increases of $18.7 billion in 2026 and $12.4 billion in 2027. Part of their result appears to be a timing issue, as the limitation was only extended to 2026. JCT also estimates some small revenue losses in the subsequent years. Tax-Calculator does not produce this effect because losses in excess of the limitation may be carried forward, but we don't keep track of these carryforwards. I suspect that their larger overall magnitude relates to current pandemic-related losses that will be carried forward for several years. 

For the UI exemption, Tax-Calculator produces a revenue loss of $1.2 billion in 2020, whereas JCT estimates a loss of $25 in 2021. The timing discrepancy is because the policy provision was enacted in 2021 but applied retroactivity. I believe the larger total amount occurs because of the pandemic; many more people received UI benefits in 2020, and the benefits were much larger because of the additional federal payments. I don't think Tax-Calculator captures these pandemic effects.

The Recovery Rebate Credit totals are reasonably similar, with Tax-Calculator estimating a loss of $387 billion in 2021, and JCT estimating losses of $394 billion in 2021 and $16.9 billion in 2022. 

The CTC results are very different. Tax-Calculator estimates revenue loss of $167.6 billion for 2021, whereas JCT estimates losses of $25.8 billion in 2021 and $79.2 billion in 2022. I'm not sure what the discrepancy is. Using Tax-Calculator, making the CTC fully refundable loses $23 billion, extending to 17-year-olds costs $46 billion, and increasing the credit amounts costs $97.9 billion. I suspect the extension to 17-year-olds is the cause of this discrepancy. If we model these changes without including 17-year-olds, the total revenue loss is $94.9 billion, close to the JCT estimate. @MattHJensen, @martinholmer, is there something odd about the construction of `nu18`? For 2021, Tax-Calculator produces a total number of CTC-eligible children (under pre-ARPA law) of 70.3 million, but a total number of children under 18 of 85.6 million.

For the EITC expansions, Tax-Calculator's results are generally greater than JCT's, with large differences in 2021 and more moderate differences in later years. I think this is just pandemic-related, as JCT probably forecasts unusually low claiming of the EITC this year due to high pandemic-related unemployment. 

For the CDCC expansion, Tax-Calculator estimates a revenue loss of $5.1 billion for 2021, and JCT estimates losses of $2.1 billion in 2021 and $5.8 billion in 2022. The timing discrepancy is likely once again just due to when JCT forecasts the refunds actually being provided. JCT's larger overall estimate is probably due to having better data on expenditures for care of children and dependents. 

Despite discrepancies, the total effects are reasonably close. Tax-Calculator produces total revenue loss from these provisions of $570 billion through 2030, and JCT estimates a total revenue loss from these provisions of $536 billion.

**Comment by kpomerleau** [comment]
Hi @codykallen, when we ran the CTC expansion we got an estimate of ~$101 billion without behavioral effects, which is quite close to the JCT score.

Looking at the code, I believe the difference is in how we coded the CTC for 17-year-old children. We used code similar to that currently used for the ODC: max(0, xtot-nu18-n1820-n21-num). This leaves you with the number of dependents in the tax unit that are currently ineligible for the CTC, but are under 18.

For a sense of scale, this code increases the number of eligible children from 70.1 million to 72.1 million.

**Comment by codykallen** [comment]
@kpomerleau, in that calculation, `max(0, xtot-nu18-n1820-n21-num-n24)`, is one of those minus signs supposed to be a plus? It looks like you're taking the total number of people (or, people eligible for the personal exemption under pre-TCJA law), and subtracting the number of people under 18 (`nu18`), the number of people between 18 and 20 (`n1820`), the number of people  21 and older (`n21`), the number of CTC-eligible children (`n24`), and the filer count (2 for married joint, 1 otherwise).

**Comment by codykallen** [comment]
@kpomerleau, that calculation makes sense to me. I'll implement it in a new commit shortly.

**Comment by kpomerleau** [comment]
I apologize. My first version had an error. The nu18 shouldn't be in there.

But yes, that is the general idea.

**Comment by codykallen** [comment]
Should we also be subtracting num? Shouldn't that already be picked up in one of the other variables?

**Comment by kpomerleau** [comment]
In theory I suppose so, but running it without taking out num gets your an extra 21 million eligible individuals.

**Comment by jdebacker** [comment]
@codykallen These numbers look quite good to me with a fix to the CTC like @kpomerleau is proposing.

One note for comparison, you are comparing CY results (from Tax-Calculator) to FY results (from JCT), so that is some of the discrepancy across adjacent years.

**Comment by codykallen** [comment]
Using the fix suggested by @kpomerleau, the CTC cost is now $100.7 billion, reasonably close to the JCT estimate.

**Comment by codykallen** [comment]
New revenue estimates: 
[ARPA revenue comparison.xlsx](https://github.com/PSLmodels/Tax-Calculator/files/6138332/ARPA.revenue.comparison.xlsx)

Distributional table: 
[ARPA distribution table.xlsx](https://github.com/PSLmodels/Tax-Calculator/files/6138334/ARPA.distribution.table.xlsx)

**Comment by MattHJensen** [comment]
Resolved by #2573. Thanks @codykallen and @kpomerleau!
