### ISSUE TITLE
Include tax provisions from the Consolidated Appropriations Act of 2021 in baseline

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Tax-Calculator#2591]
The `policy_current_law.json` should include the tax provisions from the Consolidated Appropriations Act of 2021.

I believe only two (and maybe just one) provision can be modeled in Tax-Calculator:
1. Additional 2020 recovery rebates for individuals
2. Amendments to recovery rebates under the CARES Act

The JCT Score of these are [here](https://www.jct.gov/publications/2020/jcx-24-20/).

**Comment by jdebacker** [comment]
Thoughts on modeling the additional recovery rebate credits under the Consolidated Appropriations Act of 2021:
1. Use the parameters created in PR #2586, increasing the values of `RRC_c_unit` from 1200 and 2400 to 1800 and 3600 in 2020 and the value of `RRC_c_kids` from 500 to 1100 in 2020.  All income thresholds for phaseouts remain the same.
2. The amendments to the rebates are, I think, mostly outlined in Section 273 (which starts on page 795 of [H.R. 133](https://www.congress.gov/116/bills/hr133/BILLS-116hr133enr.pdf)). 

Re the above, although this Act was passed in CY 2021, has revenue effects in FY 2021, and is based on a filer's 2019 (or 2018 or 2020 income) , I think in Tax-Calculator we want to assign this to tax year 2020 because (1) it's a credit on the taxpayers 2020 return (2) it expands the RRC from the April 2020 Act, which we are assigning  to tax year 2020, (2) parameterizing this as a tax year 2021 value poses conflicts with parameters that are used for the RRCs under both the CARES Act and APRA (such as `RRC_ps`).

Thoughts @MattHJensen @MaxGhenis ?

**Comment by MaxGhenis** [comment]
Assigning to 2020 sounds good to me. Most of the payments were based on 2019 income, but 2020 probably gives a more accurate score, since they could be topped up in 2020, and the income base that these eligibility criteria were based on is probably closer to 2020 than 2019 (i.e. more people probably qualify based on 2020 income than 2019 income).

**Comment by jdebacker** [comment]
Addressed in #2594
