### ISSUE TITLE
Release notes for next taxcalc release

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Tax-Calculator#2597]
This issue will list the updates made since the last Tax-Calculator release:

1. Update the current law baseline to include the CARES Act (PR #2586), the ARPA (PRs #2573 and #2588), and the Consolidated Appropriations Act of 2021 (PR #2593) as well as updates to EITC parameters (PR #2593). This ends a transition period for users to model these changes as reforms to the former baseline. (main contributions from @amshoulders, @codykallen, @MattHJensen, @jdebacker )
2. Add profiling to testing (PRs #2570, #2577, #2587) from @chusloj.
3. Allow for non-taxed UI eligibility, PR #2579 from @MaxGhenis.
4. Additional unit tests for `calcfunctions.py`, PR #2572 from @amshoulders.
5. Updated growfactors and weights for the PUF and CPS data, PR #2599

**Comment by MattHJensen** [comment]
@jdebacker, proposed additional sentence is bolded. 

Update the current law baseline to include the CARES Act (PR #2586), the ARPA (PRs #2573 and #2588), and the Consolidated Appropriations Act of 2021 (PR #2593) as well as updates to EITC parameters (PR #2593). **This ends a transition period for users to model these changes as reforms to the former baseline.** (main contributions from @amshoulders, @codykallen, @MattHJensen, @jdebacker )

**Comment by jdebacker** [comment]
New release is out with PR #2606.
