### ISSUE TITLE
Is STD_allow_charity_ded_nonitemizers necessary?

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2603]
`STD_allow_charity_ded_nonitemizers` seems redundant with `STD_charity_ded_nonitemizers_max > 0`. It's only used here:

https://github.com/PSLmodels/Tax-Calculator/blob/b2ba77eded980ec24c63d08084230225efadb33e/taxcalc/calcfunctions.py#L1160-L1161

**Comment by jdebacker** [comment]
@MaxGhenis I think you are right that the "allow" parameter is redundant.

One could have: `STD_charity_ded_nonitemizers_max = 0` if non-itemizers are not allowed an above the line deduction for their charitable contributions and `STD_charity_ded_nonitemizers_max = 9e99` if they are allowed without limit (and of course any number in between if they are allowed, but with limit).

**Comment by martinholmer** [comment]
@jdebacker said in issue #2603 on June 30, 2021:
> @MaxGhenis I think you are right that the "allow" parameter is redundant.

Yes, it is logically redundant, but keeping it gives a small speed-up in the tax calculations:

https://github.com/PSLmodels/Tax-Calculator/blob/9d513bde1cdfbbe1a513b5101c4b4baf61585f60/taxcalc/calcfunctions.py#L1207-L1211
