### ISSUE TITLE
Documentation notes two different commands to install taxcalc -- there's typo in one

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/Tax-Calculator#2605]
The Tax-Calculator documentation says this:

<img width="1459" alt="Screen Shot 2021-07-18 at 3 52 04 PM" src="https://user-images.githubusercontent.com/12170745/126080711-dade2d03-927d-41c0-9c30-62f1adc00737.png">

Being a new user, I click on the "Getting started" link and read this:

<img width="1743" alt="Screen Shot 2021-07-18 at 3 53 10 PM" src="https://user-images.githubusercontent.com/12170745/126080743-fd16c1ab-6394-47e8-bc9e-894fb475abfb.png">

But when I follow those directions, I get offered an old version of the taxcalc package
as shown here:

<pre>
(py37) work% date
Sun Jul 18 15:57:20 EDT 2021

(py37) work% conda install -c PSLmodels -c conda-forge taxcalc
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/mrh/anaconda3/envs/py37

  added / updated specs:
    - taxcalc

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    aiohttp-3.7.4.post0        |   py37h271585c_0         602 KB  conda-forge
    async-timeout-3.0.1        |          py_1000          11 KB  conda-forge
    multidict-5.1.0            |   py37h271585c_1          60 KB  conda-forge
    taxcalc-3.1.0              |           py37_0        30.3 MB  PSLmodels
    typing-extensions-3.10.0.0 |       hd3eb1b0_0           8 KB
    yarl-1.6.3                 |   py37h271585c_2         131 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        31.1 MB

The following NEW packages will be INSTALLED:

  aiohttp            conda-forge/osx-64::aiohttp-3.7.4.post0-py37h271585c_0
  async-timeout      conda-forge/noarch::async-timeout-3.0.1-py_1000
  bokeh              conda-forge/osx-64::bokeh-2.3.3-py37hf985489_0
  fsspec             conda-forge/noarch::fsspec-2021.7.0-pyhd8ed1ab_0
  jinja2             conda-forge/noarch::jinja2-3.0.1-pyhd8ed1ab_0
  markupsafe         conda-forge/osx-64::markupsafe-2.0.1-py37h271585c_0
  marshmallow        conda-forge/noarch::marshmallow-3.12.2-pyhd8ed1ab_0
  multidict          conda-forge/osx-64::multidict-5.1.0-py37h271585c_1
  paramtools         conda-forge/noarch::paramtools-0.18.1-pyhd8ed1ab_0
  python_abi         conda-forge/osx-64::python_abi-3.7-2_cp37m
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.4.0-pyhd8ed1ab_0
  taxcalc            PSLmodels/osx-64::taxcalc-3.1.0-py37_0
  typing-extensions  pkgs/main/noarch::typing-extensions-3.10.0.0-hd3eb1b0_0
  yarl               conda-forge/osx-64::yarl-1.6.3-py37h271585c_2

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2021.7.5-h~ --> conda-forge::ca-certificates-2021.5.30-h033912b_0
  certifi            pkgs/main::certifi-2021.5.30-py37hecd~ --> conda-forge::certifi-2021.5.30-py37hf985489_0
  openssl              pkgs/main::openssl-1.1.1k-h9ed2024_0 --> conda-forge::openssl-1.1.1k-h0d85af4_0

Proceed ([y]/n)? n

CondaSystemExit: Exiting.
</pre>

Why can't I install the taxcalc 3.2.0 package?
Am I doing something wrong?

**Comment by jdebacker** [comment]
@martinholmer Thanks for your interest in the new `taxcalc` package.  You aren't doing anything wrong -- we've committed the changes and tagged a new release in this repo, but haven't finalized the conda-forge release just yet.  It was probably my mistake to kick that off that release process on a Saturday night.  We should have this available to you via conda-forge on Monday.

**Comment by jdebacker** [comment]
@martinholmer `taxcalc` 3.2.0 is now available via conda-forge.

```
(base) jason.debacker@JDEBACKER ~ % conda search taxcalc --channel conda-forge
Loading channels: done
# Name                       Version           Build  Channel
taxcalc                        3.1.0    pyhd8ed1ab_0  conda-forge
taxcalc                        3.2.0    pyhd8ed1ab_0  conda-forge
```

**Comment by martinholmer** [comment]
Thanks @jdebacker, but when I follow the "Getting started" instructions I do not get offered the 3.2.0 version of the taxcalc package.   Rather I get offered the 3.1.0 version for download. Here are the details:

<pre>
(py37) taxsim32% conda install -c PSLmodels -c conda-forge taxcalc
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/mrh/anaconda3/envs/py37

  added / updated specs:
    - taxcalc

The following NEW packages will be INSTALLED:
  aiohttp            conda-forge/osx-64::aiohttp-3.7.4.post0-py37h271585c_0
  async-timeout      conda-forge/noarch::async-timeout-3.0.1-py_1000
  bokeh              conda-forge/osx-64::bokeh-2.3.3-py37hf985489_0
  fsspec             conda-forge/noarch::fsspec-2021.7.0-pyhd8ed1ab_0
  jinja2             conda-forge/noarch::jinja2-3.0.1-pyhd8ed1ab_0
  markupsafe         conda-forge/osx-64::markupsafe-2.0.1-py37h271585c_0
  marshmallow        conda-forge/noarch::marshmallow-3.12.2-pyhd8ed1ab_0
  multidict          conda-forge/osx-64::multidict-5.1.0-py37h271585c_1
  paramtools         conda-forge/noarch::paramtools-0.18.1-pyhd8ed1ab_0
  python_abi         conda-forge/osx-64::python_abi-3.7-2_cp37m
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.4.0-pyhd8ed1ab_0
  taxcalc            PSLmodels/osx-64::taxcalc-3.1.0-py37_0
  typing-extensions  pkgs/main/noarch::typing-extensions-3.10.0.0-hd3eb1b0_0
  yarl               conda-forge/osx-64::yarl-1.6.3-py37h271585c_2

The following packages will be SUPERSEDED by a higher-priority channel:
  ca-certificates    pkgs/main::ca-certificates-2021.7.5-h~ --> conda-forge::ca-certificates-2021.5.30-h033912b_0
  certifi            pkgs/main::certifi-2021.5.30-py37hecd~ --> conda-forge::certifi-2021.5.30-py37hf985489_0
  openssl              pkgs/main::openssl-1.1.1k-h9ed2024_0 --> conda-forge::openssl-1.1.1k-h0d85af4_0

Proceed ([y]/n)? n

CondaSystemExit: Exiting.
</pre>

**Comment by jdebacker** [comment]
@martinholmer I think this is a conda issue.  It may be trying to use a cached version or you might have some dependency conflict.

You might try `conda install -c conda-forge "taxcalc>=3.2.0"` or try installing in a fresh environment.

**Comment by martinholmer** [comment]
@jdebacker said:
> You might try conda install -c conda-forge "taxcalc>=3.2.0"

I'm just doing what it says to do in the Tax-Calculator documentation.
But you keep dropping out the "-c PSLmodels" part of what's in the documentation.
Are you suggesting the documentation is incorrect about how to get started?

**Comment by jdebacker** [comment]
Ah - yes, typo in the "Getting Started" page -- instructions of the landing page for the docs is correct.  I will update the "Getting Started" page.

**Comment by martinholmer** [comment]
@jdebacker, Thanks for fixing the "Getting started" installation instructions.
Using the corrected instructions worked for me.
