### ISSUE TITLE
Updating tax calculator gives me version 3.0.0 

### ISSUE THREAD

**Issue by JackLandry** [PSLmodels/Tax-Calculator#2611]
After running 
`conda update -c conda-forge taxcalc` 
`conda list taxcalc` 
tells me I have using version 3.0.0. Shouldn't I get 3.2.0? Am I doing something wrong?

**Comment by jdebacker** [comment]
@JackLandry Hmm, I can't replicate this. It could be a conda issue (sometimes it uses a cached version of taxcalc -- 3.0.0 is not even on the conda-forge channel).

Maybe try: `conda install -c conda-forge "taxcalc>=3.2.0"`

Or you can try your commands above in a fresh python environment.

**Comment by JackLandry** [comment]
Fresh python environment semed to work, thanks!
