### ISSUE TITLE
CTC_new_c is not an array parameter?

### ISSUE THREAD

**Issue by JackLandry** [PSLmodels/Tax-Calculator#2612]
I thought I tracked this error down to not updating to 3.2.0, but I fixed that and am still getting it. 

`tc cps_2019_for_taxsim.csv 2021 --reform ctc-new-current-law.json`

`
{
    "errors": {
        "schema": "CTC_new_c is not an array parameter."
    }
`

The json reform file looks like this:
`
{
    "CTC_new_c": {"2021": [1000.00]},
    "CTC_new_c_under6_bonus": {"2021": [600.00]}
}
`

Any tips much appreciated, thanks!

**Comment by jdebacker** [comment]
@JackLandry The CTC parameters you are using are just scalar values, so I think all you need to do is drop the braces. e.g., 

```
{ "CTC_new_c": {"2021": 1000.00}, "CTC_new_c_under6_bonus": {"2021": 600.00} }
```

**Comment by JackLandry** [comment]
Working now, thank you so much for all your help @jdebacker!
