### ISSUE TITLE
Confirm logic for standard deduction with blind spouse

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2620]
taxcalc currently requires that filers are joint to claim an extra standard deduction for aged spouses, but that condition isn't present for blind spouses:

https://github.com/PSLmodels/Tax-Calculator/blob/2ccfcb446d281aa8f733be59f591de931a41ad24/taxcalc/calcfunctions.py#L1150-L1154

[This page](https://www.efile.com/tax-deduction/federal-standard-deduction/) suggests that they're treated equally. Is the taxcalc logic correct, or might the MARS condition be redundant?

cc @nikhilwoodruff re https://github.com/UBICenter/openfisca-us/pull/45#discussion_r702503015

**Comment by jdebacker** [comment]
Per [IRS instructions](https://www.irs.gov/pub/irs-pdf/i1040gi.pdf), those filling married joint returns can claim an extra standard deduction for an age/blind spouse and those filing married single returns can if some other conditions are met (spouse has no income, doesn't file a return, and isn't claimed as a dependent on another return).  

Implicitly the current Tax-Calc code assumes these conditions are married single returns are met for those claiming a blind spouse, but not for those claiming an aged spouse.

There is little/no data to check that these conditions on married single filers are met, but one could think about adding these conditions to the logic if there were data.

**Comment by MaxGhenis** [comment]
This should work:
```python
num_extra_stded = blind_head + blind_spouse + (age_head >= 65) + (age_spouse >= 65)
```

**Comment by martinholmer** [comment]
The code in `calcfunctions.py` seems to correspond to the logic suggested [earlier in this discussion](https://github.com/PSLmodels/Tax-Calculator/issues/2620#issuecomment-1054949196).
