### ISSUE TITLE
ARPA CTC credit amounts with TCJA phase in?

### ISSUE THREAD

**Issue by JackLandry** [PSLmodels/Tax-Calculator#2621]
Is it possible to model the status-quo ARPA child tax credit benefit amounts and phase-outs, while replacing full refundability with the TCJA phase in structure? There are so many CTC parameters I could have my understanding wrong, but I think you can get the TCJA phase-in with the ARPA bonuses for low income households, but you'd have to do a separate run for higher AGI units to get the phase outs? Here is my attempt to write the .json, which gives me an idiosyncratic error... Any help on the current error, as well as if my .json looks correct for what I'm trying to do, would be much appreciated 

.json
```
{
    "ACTC_c": {"2021": 2100.0},
    "ACTC_rt_bonus_under6family": {"2021": 420.0},
    "ACTC_rt": {"2021": 0.15}, 
    "ACTC_Income_thd": {"2021": 2500.0},
    "ACTC_ChildNum": {"2021":  3}, 
    "CTC_c": {"2021": 3000.0},
    "CTC_c_under6_bonus": {"2021": 600.0},
    "CTC_include17": {"2021": true},
    "CTC_refundable": {"2021": false},
    "CTC_ps": {"2021": [200000.0, 400000.0, 200000.0, 200000.0, 400000.0]},
    "CTC_prt": {"2021": 0.05}
}
```

Error:
```
file "/opt/anaconda3/envs/test/bin/tc", line 10, in <module>
    sys.exit(cli_tc_main())
  File "/opt/anaconda3/envs/test/lib/python3.9/site-packages/taxcalc/cli/tc.py", line 156, in cli_tc_main
    tcio.init(input_data=inputfn, tax_year=taxyear,
  File "/opt/anaconda3/envs/test/lib/python3.9/site-packages/taxcalc/taxcalcio.py", line 282, in init
    self.errmsg += pol.parameter_errors
TypeError: can only concatenate str (not "dict") to str
```

**Comment by jdebacker** [comment]
@JackLandry These are great questions. 

The error is you are receiving is because `ACTC_rt_bonus_under6family` is a rate and is bounded by 0 and 1.  If I change 420 to 1, I can run the reform.
