### ISSUE TITLE
Problems with conda install in Windows 10

### ISSUE THREAD

**Issue by rHrtly** [PSLmodels/Tax-Calculator#2623]
Hi all, I received help here before on setting up TaxCalc in a Windows environment so that I could call it with a shell command in Stata. After a hard drive crash, I am trying to get restarted and am having trouble with the installation. I am using a command prompt from the Anaconda3 Navigator, as shown below, which led to several conflicting packages found: [taxcalc-package-conflicts.txt](https://github.com/PSLmodels/Tax-Calculator/files/7197488/taxcalc-package-conflicts.txt). Any advice?

```
(base) C:\Users\rh2843>conda install -c conda-forge taxcalc
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
```

**Comment by jdebacker** [comment]
@rHrtly I'm sorry to hear about the hard drive crash and the trouble getting `taxcalc` installed afterwards.

Your conflicts look like a broader issue with conda and I'm unable to replicate them.  You might want to start by updating conda.  e.g., with:

```
$ conda update conda --all
$ conda update anaconda
```

**Comment by rHrtly** [comment]
Thanks @jdebacker, I thought the issue may well be broader given the incredible list of conflicts, though I am novice enough in this environment to not know quite where to start. I appreciate the guidance, and I will report back on how it goes (I need to get 'write permissions' from an admin).

**Comment by jdebacker** [comment]
Update: I just had a student running Windows 10 with the same issues.  Updating Conda and Anaconda as above solved it.  Hope it works for you too @rHrtly!

**Comment by rHrtly** [comment]
Alright @jdebacker, thanks for helping, and I think I am getting somewhere. Our IT admin ran the conda updates as you suggested, and now I can successfully run `tc --test`. One last issue seems to occur whenever I use the `--dump`  option, I get the following message:

> C:\Users\rh2845\Anaconda3\lib\site-packages\taxcalc\taxcalcio.py:702: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
>   odf[varname] = vardata.round(2)  # rounded to nearest cent
> 

It looks like it is still producing results properly based on the output files (I used test.csv, cps.csv, and my own cps_modified.csv). Perhaps that is innocuous and/or a completely separate issue, and otherwise, it would seem I am back to operational. Thanks again for the help!

**Comment by jdebacker** [comment]
@rHrtly Thanks for following up.  I'm glad you got this working. 

I also appreciate the report on that performance warning.  I've noticed that as well.  It's not an error, but just a notification that  things may be done more efficiently.  I'll open an issue to see if anyone wants to explore this further.
