### ISSUE TITLE
Problems with PUF.csv on TaxCalc 3.2.x

### ISSUE THREAD

**Issue by harjotsodhi** [PSLmodels/Tax-Calculator#2629]
Hello TaxCalc developers,

I'm having some trouble using the PUF.csv (from year 2011*) with TaxCalc version 3.2.1 and 3.2.0. I realize these past two versions depend on updates to TaxData. Prior to testing TaxCalc version 3.2.X, I updated my PUF.csv in accordance with the newest version of TaxData (0.3.X) and added the updated file to the relevant directory. 

Yet, I am not able to pass the provided PUF-related tests. In particular, I fail the following PUF tests:

```console
(taxcalc3.2.1) Harjots-MacBook-Pro:tests harjotsodhi$ pytest test_pufcsv.py
===================================== test session starts ======================================
platform darwin -- Python 3.8.2, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /Users/harjotsodhi/Desktop/Tax-Calculator-3.2.1, inifile: pytest.ini
plugins: mock-3.1.0, harvest-1.10.3, cov-2.8.1
collected 5 items                                                                              

test_pufcsv.py FF...                                                                     [100%]

FAILED test_pufcsv.py::test_agg - ValueError: PUFCSV AGG RESULTS DIFFER FOR FULL-SAMPLE
FAILED test_pufcsv.py::test_mtr - ValueError: PUFCSV MTR RESULTS DIFFER
```

Some visual inspection of `pufcsv_agg_actual.csv` shows that my tax results appear much larger than those in the provided `pufcsv_agg_expect.csv`, yet the weighted returns appear to match, here are a couple of rows:

|     |2017   |2018 |2019 |2020   |2021   |2022   |2023   |2024   |2025   |2026   |
|------------|-------|-----|-----|-------|-------|-------|-------|-------|-------|-------|
|Returns (#m)|190.9  |194.3|197.3|200.1  |202.9  |205.6  |208.4  |211.2  |214    |216.7  |
|AGI ($b)    |25750.5|28601|30123|28893.9|32744.3|33553.1|34092.4|35219.1|36589.9|37722.2|
|Ind Income Tax ($b)|6533.3 |6854 |7218.1|6277   |7286.8 |8048.9 |8203.5 |8518.6 |8890.2 |9629.4 |

Similarly, I manually checked to ensure whether the number of rows in my PUF.csv matched the rows in puf_weights.csv, which they do.

Conversely, when I repeat these tests in a Conda env containing TaxCalc versions 3.0.0 or 3.1.0, using a PUF.csv constructed from the prior version of TaxData (0.1.0), I am able to pass all of the tests. The number of rows in those earlier PUF.csv match the rows in their respective puf_weights.csv files, but do not match the number of rows in the newest version of PUF.csv produced by TaxData (0.3.2).

Any advice about how to handle this would be much appreciated. Thanks!

\* edited from 2013

**Comment by jdebacker** [comment]
@andersonfrailey and @harjotsodhi Is this issue still relevant or has it been resolved?

**Comment by jdebacker** [comment]
Closing this issue. If necessary, something like this can be raised over in the [TaxData project repo](https://github.com/PSLmodels/taxdata).
