### ISSUE TITLE
Parameterize maximum net capital losses 

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2632]
[Capital losses are currently limited](https://www.irs.gov/taxtopics/tc409) as described by the IRS here:
>If your capital losses exceed your capital gains, the amount of the excess loss that you can claim to lower your income is the lesser of $3,000 ($1,500 if married filing separately) or your total net loss shown on line 21 of Schedule D (Form 1040).

This is currently hard-coded as `-3000` in the `ALD_InvInc_ec_base` function:

https://github.com/PSLmodels/Tax-Calculator/blob/cf452aaeb0bf7a5e13c11581963c3fafe86edb16/taxcalc/calcfunctions.py#L432

and the `CapGains` function:

https://github.com/PSLmodels/Tax-Calculator/blob/cf452aaeb0bf7a5e13c11581963c3fafe86edb16/taxcalc/calcfunctions.py#L541

Where
https://github.com/PSLmodels/Tax-Calculator/blob/cf452aaeb0bf7a5e13c11581963c3fafe86edb16/taxcalc/calcfunctions.py#L413-L414

**Comment by jdebacker** [comment]
@MaxGhenis I think this is a duplicate of Issue #2624.  If you agree, would you mind closing this issue (any moving any additional detail you think is necessary over to 2624)?

**Comment by MaxGhenis** [comment]
Oops, yes, I only searched for 3000 :)
