### ISSUE TITLE
Change starting year while using python interface?

### ISSUE THREAD

**Issue by Thirdhuman** [PSLmodels/Tax-Calculator#2636]
I'm working in TaxCalculator using the 2014 PUF.  Having modified TaxData's processes to do so, my first set of weights is "WT2014". As such, I get the following error running TaxCalculator via Python:

```
calc1 = tc.Calculator(policy=pol, records=recs)
KeyError: 'WT2012'
```

I don't run into any error when working in the command-line interface.  I assume that's because I directly specify years beyond 2014. Apart from modifying TaxCalculator, is there anything I can do to get the Python interface to change the starting year?

**Comment by jdebacker** [comment]
cc @andersonfrailey 

May related to Issue #2507

**Comment by Thirdhuman** [comment]
Ignore. I simply had to restart my Jupyter Notebook kernel.
