### ISSUE TITLE
Do we have a sense of where Tax Calculator's 2011 PUF outputs are most likely to be off?

### ISSUE THREAD

**Issue by Thirdhuman** [PSLmodels/Tax-Calculator#2637]
Do Tax-Calculator users/developers have any sense of what the biases are of the 2011 PUF-based outputs likely are? 
For instance, understating/overstating aggregate AGI?  Or areas where the income distribution or anticipated filing behaviors might be off?  

With these sorts of things, I know that methodological consistency and faithfulness to the underlying data can dominate strong hunches about what's actually true. I'm trying to figure out where those are for the 2011 PUF.

For context, I'm asking this because I'm in the process of validating my adaptation of TaxData puf.csv file for the 2014 PUF file, currently by cross-referencing TaxData's puf_agg_exp.csv and TaxBrain's PUF calculations. And so I'm trying to diagnose whether any disparities are likely due to possible calculation/coding errors vs. defensible differences stemming from the dataset.

**Comment by MaxGhenis** [comment]
This might be more of a taxdata question (I don't have access to transfer issues), but @andersonfrailey may be able to speak to the PUF's targeting process and results.

**Comment by Thirdhuman** [comment]
Moved the discussion to TaxData:
https://github.com/PSLmodels/taxdata/issues/410
