### ISSUE TITLE
Legislative reference for AMT bracket

### ISSUE THREAD

**Issue by nikhilwoodruff** [PSLmodels/Tax-Calculator#2638]
I'm just looking through the AMT logic and not having much luck finding a source for the first AMT bracket value. In `current_policy_law.json`, for 2013 [it has the value $179,500](https://github.com/PSLmodels/Tax-Calculator/blob/6ab24023ed1b661a6dfdd4ce60301838c49536b1/taxcalc/policy_current_law.json#L13833). But I'm looking at [26 U.S. Code § 55](https://www.law.cornell.edu/uscode/text/26/55), which sets the threshold at $175,000 in (b)(1)(A) and then describes the inflation adjustment from there:
> (3) Inflation adjustment
(A) In general
In the case of any taxable year beginning in a calendar year after 2012, the amounts described in subparagraph (B) shall each be increased by an amount equal to—
(i) such dollar amount, multiplied by
(ii) the cost-of-living adjustment determined under section 1(f)(3) for the calendar year in which the taxable year begins, determined by substituting “calendar year 2011” for “calendar year 2016” in subparagraph (A)(ii) thereof.
(B) Amounts described
The amounts described in this subparagraph are—
(i) each of the dollar amounts contained in subsection (b)(1)(A),
(ii) each of the dollar amounts contained in subparagraphs (A), (B), and (D) of paragraph (1), and
(iii) each of the dollar amounts in subparagraphs (A) and (B) of paragraph (2).
(C) Rounding
Any increased amount determined under subparagraph (A) shall be rounded to the nearest multiple of $100.

Related to this, I also tried to find the raw values for the CPI measure described in 1(f)(3), C-CPI-U, but couldn't here. Manually (in code) calculating the average change for Sept 2012 - Aug 2013, increasing 2012's value of $175,000 and rounding the increase to the nearest $100 gets me to $177,500, rather than $179,500 (and this difference propagates forward).

Is there something I'm doing obviously wrong here/some published values that would override this?

Edit: I see now that the inflation rates are from the `ACPIU` column in `growfactors.csv`. Is there a source somewhere for the values in this table?

**Comment by MaxGhenis** [comment]
Agree a legislative reference would be helpful. To confirm though, this is the $197,900 in line 7 of [Form 6251](https://www.irs.gov/pub/irs-pdf/f6251.pdf), right?

**Comment by martinholmer** [comment]
@nikhilwoodruff and @MaxGhenis,
I'm not so sure a legislative reference would be that useful.  Tax-Calculator just simulates a filing unit completing an IRS tax form, so what counts is whether or not Tax-Calculator and the annual IRS forms are in agreement.  At the moment, Tax-Calculator knows historical values for parameters on the IRS tax forms through 2019.  The value of the `AMT_brk1` parameter in 2018 is 191,100 and in 2019 is 194,800.  Both those values are exactly the same as the values printed on IRS Form 6251 for those two years.  Plus, the validation tests with the NBER TAXSIM model would have most likely failed if Tax-Calculator has incorrect values for that parameter.
