### ISSUE TITLE
Move license to root of repo

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2639]
[GitHub recognizes licenses](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) as `LICENSE` or `LICENSE.md` in the root of a repo and puts it in the repo sidebar. For example, here's how openfisca-core looks given their [license](https://github.com/openfisca/openfisca-core/blob/master/LICENSE):
![image](https://user-images.githubusercontent.com/6076111/147398970-2ac21539-4260-42b0-b5fd-56bc6f083d5b.png)

The Tax-Calculator license is currently in [docs/about/license.md](https://github.com/PSLmodels/Tax-Calculator/blob/master/docs/about/license.md), so it doesn't show up.

**Comment by martinholmer** [comment]
@MaxGhenis,  Good idea!  Why don't you submit a pull request that fixes the problem you've identified in issue #2639.

**Comment by jdebacker** [comment]
Completed with PR #2706
