### ISSUE TITLE
Adopt an OSI-approved open source license

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/Tax-Calculator#2640]
Tax-Calculator and several other PSL repos use the [CC0 1.0 Universal (CC0 1.0) Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/) as a license. The [Creative Commons wiki](https://wiki.creativecommons.org/wiki/CC0_FAQ) notes (emphasis mine):
>May I apply CC0 to computer software? If so, is there a recommended implementation?
Yes, CC0 is suitable for dedicating your copyright and related rights in computer software to the public domain, to the fullest extent possible under law. Unlike CC licenses, which should not be used for software, CC0 is compatible with many software licenses, including the GPL. **However, CC0 has not been approved by the Open Source Initiative and does not license or otherwise affect any patent rights you may have. You may want to consider using an approved OSI license that does so instead of CC0, such as GPL 3.0 or Apache 2.0.**

GitHub also does not recognize CC0 as a license, and as a result, it doesn't show up as a particular license on the About section in repos that place it in a recognized format (see #2639). For example, [openfisca-core](https://github.com/openfisca/openfisca-core/) shows `AGPL-3.0 License`, but [OG-core](https://github.com/PSLmodels/OG-Core) only shows `View license`:
![image](https://user-images.githubusercontent.com/6076111/147399175-756d22e4-1a58-4a5b-8761-950502d94965.png)

![image](https://user-images.githubusercontent.com/6076111/147399150-d69998bb-221f-4995-b4dc-46a5a6904d53.png)

I'd suggest we switch to an OSI-approved license as listed at https://choosealicense.com/licenses (curated by GitHub).

**Comment by MattHJensen** [comment]
Hi @MaxGhenis, I've given this some thought in the past and decided that the OSI stamp of approval didn't justify changing our license, but it could be I'm out of date. We chose CC0 because it doesn't require an explicit assignment of copyright to an institution or group of contributors. As I understand it, other OSI-approved licenses require that. PSL criteria accomodate the CC0 license.

**Comment by MaxGhenis** [comment]
Thanks for the context @MattHJensen
