### ISSUE TITLE
Elderly and disabled credit values for widow(er)s

### ISSUE THREAD

**Issue by nikhilwoodruff** [PSLmodels/Tax-Calculator#2641]
In the [SchR](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/calcfunctions.py) function, widower filers are currently given no initial amount for the Section 22 income part of the elderly and disabled credit, is this correct? As I understand it, [the law](https://www.law.cornell.edu/uscode/text/26/22) complicates things by not defining the initial amount for the usual filer categories, but instead for:

* Single filers, or joint filers with only one qualified individual
* Joint filers with two qualified individuals
* Married filing separately

That leaves two categories, the head-of-household and widow filers. `SchR` groups the HoH filers with single filers, but seems to disqualify the widow filers.

**Comment by MaxGhenis** [comment]
Table 2 in https://www.irs.gov/publications/p524 indicates that head of household and widow(er) filers are treated as single.

**Comment by martinholmer** [comment]
@nikhilwoodruff and @MaxGhenis,
If you have identified a bug (as discussed in issue #2641), why don't you submit a pull request that fixes the bug?

**Comment by MattHJensen** [comment]
@nikhilwoodruff, thanks for opening this issue, and @MaxGhenis, thanks for your followup. The project welcomes issues unaccompanied by PRs as well as PRs addressing issues from those who didn't open the issues. An issue is a great starting point if a topic might require more discussion or if the person who identifies the issues isn't in a good position (for whatever reason, including bandwidth) to open a PR.

**Comment by jdebacker** [comment]
Per @MaxGhenis' comment, the code in the `SchR` function is correct (albeit, the values should be parameterized rather than hardcoded -- but that can be opened as a separate issue.
