### ISSUE TITLE
CTC multiple non-refundability limitations

### ISSUE THREAD

**Issue by nikhilwoodruff** [PSLmodels/Tax-Calculator#2642]
I'm trying to understand how the CTC (`c07220`) is handled when it is not refundable, and as I understand it:
* `ChildDepTaxCredit` produces `c07220`.
* Which is then immediately used and re-produced by `NonrefundableCredits`.
But to me it seems `c07220`, when non-refundable, is limited in two separate places:
* [In ChildDepTaxCredit](https://github1s.com/pslmodels/tax-calculator/blob/HEAD/taxcalc/calcfunctions.py#L2482-L2488), limited to income tax liability less six tax credits in this order:
  * Residential energy credit
  * Foreign tax credit
  * Child and dependent care credit
  * Education credit
  * Retirement savings
  * Sch R (elderly and disabled) credit
* And then [in NonrefundableCredit](https://github1s.com/pslmodels/tax-calculator/blob/HEAD/taxcalc/calcfunctions.py#L2956-L2969), by income tax liability less a different set and order of credits (the missing two are limited afterwards):
  * Foreign Tax Credit
  * Child and dependent care credit
  * Education credit
  * Retirement savings

Is this correct?

**Comment by martinholmer** [comment]
The question posed in issue #2642 more than two and a half years ago has presambly been answered somewhere other than issue #2642.   Given there has been no discussion of this matter in over two and a half years, I'm closing the issue.
