### ISSUE TITLE
Missing 2020-2022 policy parameter values

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/Tax-Calculator#2647]
Pull request #2633, which was merged into the master branch on 15-Mar-2022, is very expansive, but there seem to be a couple of missing updates to 2020-2022 policy parameter values.

For example, `ALD_BusinessLosses_c` is indexed, but there are no 2020-2022 values for this parameter.

Also, the indexed `PT_qbid_taxinc_thd` parameter has values for 2019 and for 2022, but not for 2020 or 2021 even though these values are known.

In addition, some of the years are out of order.  This is not a problem for a computer reading the JSON file, but does make it harder for a human to read the `policy_current_law.json` file.

@bodiyang @jdebacker @MattHJensen

**Comment by jdebacker** [comment]
Resolved with PR #2652.
