### ISSUE TITLE
Incorrect 2020 UI exemption logic

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/Tax-Calculator#2648]
Since pull request #2573 was merged into the master branch on March 15, 2021, the 2020 UI exemption has reduced taxable income but left AGI unchanged.  Leaving AGI unchanged is not correct as a reading of 2020 Form 1040 and its Schedule 1 makes clear.  The incorrect AGI amount for some people can cause incorrect tax calculations when AGI is used for some purpose (like to phase-out credits).

**Comment by jdebacker** [comment]
Resolved with PR #2675
