### ISSUE TITLE
Incorrect 2020 CG_brk2 policy parameter value

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/Tax-Calculator#2649]
Since pull request #2633 was merged into the master branch on March 15, 2022, the 2020 **headhh** `CG_brk2` value has been incorrect.  Instead of the 466,050 value in the policy_current_law.json file, it should be 469, 050.  This can be confirmed by looking at the 2020 Form 1040 Schedule D Tax Worksheet.

**Comment by jdebacker** [comment]
Resolved with PR #2652.
