### ISSUE TITLE
Incorrect 2020-21 EITC_ps and EITC_ps_MarriedJ policy parameter values

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/Tax-Calculator#2651]
Since pull request #2633 was merged into the master branch on March 15, 2022, several values for the `EITC_ps` and `EITC_ps_MarriedJ` policy parameters in 2020 and 2021 have been incorrect.  Probably the easiest way to confirm this would be to consult the [Tax Policy Center's EITC documentation](https://www.taxpolicycenter.org/statistics/eitc-parameters).

@bodiyang @jdebacker @MattHJensen

**Comment by jdebacker** [comment]
Resolved with PR #2652.
