### ISSUE TITLE
Incorrect EITC amount for two kids in 2022

### ISSUE THREAD

**Issue by JackLandry** [PSLmodels/Tax-Calculator#2663]
The EITC credit amount for two kids (EITC_c) in [current_law.json](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/policy_current_law.json) is incorrect for two kids. It's coded as 6064, but it should be 6164. The IRS reference is [here](https://www.irs.gov/pub/irs-drop/rp-21-45.pdf).

**Comment by jdebacker** [comment]
Resolved with PR #2673
