### ISSUE TITLE
documentation issues

### ISSUE THREAD

**Issue by bodiyang** [PSLmodels/Tax-Calculator#2678]
couple of documentation issues needs to fix

- Broken links
- information update: for example, in [step 11 of contributor guide](https://taxcalc.pslmodels.org/contributing/contributor_guide.html), `conda env update` should be run under directory "Tax-Clculator" instead of "taxcalc", under the same directory with environment.yml file.
- Policy parameters need to be updated to the latest known year 2022. Right now the last year is 2019
- In v-4 branch, FICA tax parameters have been changed to employer / employee side

May need a round of check for all documentation issues

**Comment by martinholmer** [comment]
@bodiyang said in issue #2678:
> Policy parameters need to be updated to the latest known year 2022. Right now the last year is 2019.

Actually the last known year for policy parameters seems to be 2022 (**not** 2019 as you assert above).  And also, the values of indexed policy parameter I believe are now known through 2024, but the known values for 2023 and 2024 have not been added to the `policy_current_law.json` file.

**Comment by martinholmer** [comment]
During March 2023, @bodiyang said in issue #2678:
> documentation issues needs to fix
> * Broken links
> * information update: for example, in [step 11 of contributor guide](https://taxcalc.pslmodels.org/contributing/contributor_guide.html), `conda env update` should be run under directory "Tax-Clculator" instead of "taxcalc", under the same directory with environment.yml file.
> * Policy parameters need to be updated to the latest known year 2022. Right now the last year is 2019
> * In v-4 branch, FICA tax parameters have been changed to employer / employee side

@bodiyang,  Can you identify the "broken links" you mention in the first bullet in a new issue?

The other three bullets seem to be no longer problems.

So, I'm closing this issue.

If you want to identify any remaining "documentation issues", please open a new issue.
