### ISSUE TITLE
ACTC should be 1600 in 2023, not 1500

### ISSUE THREAD

**Issue by JackLandry** [PSLmodels/Tax-Calculator#2690]
The refundable CTC amount (ACTC_c) in [current_law.json](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/policy_current_law.json) is 1500 in 2023 when it should be 1600. IRS reference here [here](https://www.irs.gov/pub/irs-drop/rp-22-38.pdf).

**Comment by jdebacker** [comment]
@JackLandry Thank you for identifying this issue.  It has been fixed in the `master` branch and will be a part of the next TC release.
