### ISSUE TITLE
split payroll tax functions

### ISSUE THREAD

**Issue by bodiyang** [PSLmodels/Tax-Calculator#2692]
Plan to split Tax-Calculator into two parts income tax model and payroll tax model.

The new payroll tax model which I'm developing: [Taxcalc-Payroll](https://github.com/bodiyang/Taxcalc-Payroll)

~ essentially it will just split the payroll tax functions in calcfunctions.py out of the current Tax-Calculator and move them into [the new payroll tax model](https://github.com/bodiyang/Taxcalc-Payroll/blob/master/taxcalcpayroll/calcfunctions.py):  EI_PayrollTax and AdditionalMedicareTax. Other parts of Tax-Calculator remain the same.

Reason of this (which is based on the meeting last time discussing the placement of payroll tax offset function:
To keep Tax-Calculator as an income tax calculator (similar to Turbo tax), Tax-Brain as a revenue & budget estimate model (the upper structure of the family of tax models).

So the structure of tax model family will be like:
* Tax Brain (head of the tax models, where hosts central commands);
* Taxcalc-income (basically the original Tax-Calculator, deleting the payroll tax functions in calcfunctions.py) & Taxcalc-payroll (the newly created payroll tax model: payroll tax calculator + payroll tax offset functions & other payroll tax related functions)
* Tax-Data: data preparation for taxcalc
* Behavior-Response

**Comment by martinholmer** [comment]
The merge of pull request #2753, which produced Tax-Calculator 4.0.0 release, introduced a backwards-incompatible change in payroll tax calculations (by introducing separate employee and employer payroll tax rates), but did not split Tax-Calculator into two different models.
