### ISSUE TITLE
Payroll tax validation

### ISSUE THREAD

**Issue by bodiyang** [PSLmodels/Tax-Calculator#2697]
I'm working on the validation of Tax-Calculator and [Taxsim-35](https://taxsim.nber.org/taxsim35/) and seeing the difference of payroll tax calculation between two models 

I've conducted the manual calculation of many records and think Tax-Calculator is correct. So I want to open this issue to see if there is any suggestion of where the difference come from (if there is any issue from transferring Taxsim input variables to Tax-Calculator variables) @feenberg @jdebacker @MattHJensen 

The record below is an example: the payroll tax value calculated from **Tax-Calculator is $53090**; the value from **Taxsim35 is $39635**

(taxsimid 10):
year	2021 state 0	mstat 2	page 23	sage 28	depx 0	dep13 0	dep17 0	dep18 0	**pwages 198000	swages 34000	psemp 298	ssemp 281**	dividends 10000	intrec 2000	stcg 1000	ltcg -1000	otherprop 20000	nonprop 20000	pensions 23000	gssi 18000	pui 1000	sui 3000	transfers 0	rentpaid 0	proptax 0	otheritem 0	childcare 0	mortgage 0	scorp 103000	**pbusinc 146000	pprofinc 0	sbusinc 170000	sprofinc 0**	idtl 2

Taxsim to Tax-Calculator variables matching:
(1) only the variables in bold text are related to payroll tax calculation
(2) "pwages": "e00200p",
    "swages": "e00200s",
    "psemp": "e00900p",
    "ssemp": "e00900s",
    # 'pbusinc': 'e00900p', # Not perfect match for this in Tax-Calculator -- will add to e00900s below
    # 'pprofinc': # no direct analog in Tax-Calculator
    # 'sbusinc': 'e00900s', # Not perfect match for this in Tax-Calculator -- will add to e00900s below
    # 'sprofinc':# no direct analog in Tax-Calculator

e00200p = pwages
e00200s = swages
e00900p = psemp + pbusinc + pprofinc
e00900s = ssemp + sbusinc + sprofinc

(3) the calculation method can be found at [payroll tax function](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/calcfunctions.py#L102)

note:
The record above is just one example. There are many records showing differences. (not all of testing records, two models calculation are the same in the other records)
The payroll tax diff does not have a trait ( e.g. taxsim values are greater than taxcalc in some records; but also lower than taxcalc in many —- so doesn't look like if one model miss any items) ~  I don’t find there is a correlation between the diff amount and any of the input variables

**Comment by bodiyang** [comment]
another example
(taxsimid 11):
year 2021 state 0 mstat 2 page 24 sage 21 depx 3 dep13 0 dep17 1 dep18 1 pwages 21000 swages 166000 psemp 23 ssemp 219 dividends 0 intrec 17000 stcg -8000 ltcg -6000 otherprop 5000 nonprop 15000 pensions 4000 gssi 16000 pui 7000 sui 3000 transfers 0 rentpaid 0 proptax 0 otheritem 0 childcare 0 mortgage 0 scorp 39000 pbusinc 27000 pprofinc 0 sbusinc 83000 sprofinc 0 idtl 2

Taxsim payroll tax: $41637
Tax-Calculator payroll tax: $32130

**Comment by feenberg** [comment]
I am working on an update to taxsim. If you visit

    http://taxsim.nber.org/split

you can try it out. There are changes to the FICA calculation. I added a 
printout of a decomposition of the the FICA tax into components. Please 
give it a try. It looks like I get 17707 and 4215 for the OASDI components 
(taxpayer and spouse) and 5742 and 985 for the health insurance 
components. If you tell me what you get, I will track down the reason and 
fix it here if necessary.We made some decisions at the beginning that make 
it harder than necessary to do this calculation, so I am not surprised if 
there is a problem, but I'd like to focus on the problem component rather 
than go through all the calculations.

I am very grateful for your checking up on me!

Dan

**Comment by feenberg** [comment]
Can you make examples with only one source of income? That would show 
where the difference was.

Daniel Feenberg

**Comment by bodiyang** [comment]
Thanks Daniel, 
Very helpful to see the decomposition of FICA tax. I'll have a try through the updated link and let you know for new findings.

For the sources of income ~ The way I'm conducting the validation is to check the records, in 3 sets, with different income sources: _a_ set only with wage & salary income, _b_ set with more sources of income (from 11 pwages ~to  24 sui and then from 31 scorp ~ to 35 sprofinc; the two examples I shared are from b set) , _c_ set with most sources of income (with all Taxsim income variables but no 25 transfers & 26 rentpaid)

_a_ set, the set with only 11 pwages and 12 swages, shows no difference between Taxsim and Tax-Calculator
_b_ set and _c_ set all show differences 

Bodi Yang

**Comment by bodiyang** [comment]
@feenberg I've tried to run some records through the [updated taxsim split link](http://taxsim.nber.org/split/), and the result looks good.

One point to be noticed is that the updated taxsim calculated the FICA tax but not SECA tax. So the current comparison is only FICA tax, not payroll tax as a whole.

For the two example records the updated result of FICA tax is:
taxsimid 9 record: Tax-Calculator $26083; updated Taxsim $26090
taxsimid 10 record: Tax-Calculator $31120; updated Taxsim $31163

**Comment by martinholmer** [comment]
@bodiyang, it has been almost a year since you opened issue #2697 and there has been no recent discussion.   What is the status of this issue?   Can it be closed?   Or do you have a simple case in which TAXSIM35 and Tax-Calculator generate different payroll tax amounts?

**Comment by bodiyang** [comment]
> @bodiyang, it has been almost a year since you opened issue #2697 and there has been no recent discussion. What is the status of this issue? Can it be closed? Or do you have a simple case in which TAXSIM35 and Tax-Calculator generate different payroll tax amounts?

This issue can be closed. Tax-Calc have been tested to produce correct payroll tax calculation.
