### ISSUE TITLE
other dependent credit missing from iitax 

### ISSUE THREAD

**Issue by bodiyang** [PSLmodels/Tax-Calculator#2701]
Other dependent credit (odc) is missed from iitax calculation. As in [iitax calculation in Tax-Calculator](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/calcfunctions.py#L3316), child tax credit and additional child tax credit are included in the refund calculation, while other dependent credit is not.

This can be seen from the validation between Tax-Calculator and Taxsim 35

case record:
taxsimid 30  year 2021. state 0. mstat 2	 page 65	sage 72	depx  3  dep13  1	dep17  1	 dep18  1	pwages 21,000	swages 1,000

iitax calculated by Tax-Calculator is $ -12734.3; by Taxsim is - $13414.3

My manual calculation from the 2021 form 1040is -13414.3

Tax-Calculator iitax function with the intermediate variable values:
iitax	$12734;   c00100 $31000;      c04800	$3200;    taxbc  $320;    non_refundable_child_odep_credit	 $4000 ;  c11070 $0;	eitc $2734;	c62100  $31000;	amt_liability $0;	 iitax_before_credits_ex_AMT $320;	recovery_rebate_credit $7000;	c09200 $0;	odc	$1000;  c07220  $2000;	ctc_new  $1000

Tax-Calculator calculation:
refund = eitc ($2,734) + c11070 ($0) + c07220($2,000) + recovery_rebate_credit ($7,000) + ctc_new ($1,000) = $12,734
iitax = c09200 ($ 0) - refund($ 12,734) = $-12,734

It is supposed to be, taking consideration of odc:
refund = eitc ($2,734) + c11070 ($0) + c07220($2,000) + recovery_rebate_credit ($7,000) + ctc_new ($1,000) **+ odc ($1,000)** = $13,734 ~ match with line 33 of form 1040**

note: income tax liability calculated by taxsim should be 320 - 13734 = **- 13414  ~ match with line 36 of form 1040**

**Comment by bodiyang** [comment]
![IMG_4945](https://github.com/PSLmodels/Tax-Calculator/assets/60398181/70de067b-3e49-4f34-969f-10cf1a15d87a)

**Comment by bodiyang** [comment]
![IMG_4945](https://github.com/PSLmodels/Tax-Calculator/assets/60398181/7dc5f915-40c6-450b-9863-e8b716f2092c)

**Comment by bodiyang** [comment]
![IMG_4945](https://github.com/PSLmodels/Tax-Calculator/assets/60398181/409e6cd6-407c-4b23-9021-fcc2f1f07107)

**Comment by bodiyang** [comment]
[IMG_4945.jpg.zip](https://github.com/PSLmodels/Tax-Calculator/files/13193373/IMG_4945.jpg.zip)

**Comment by bodiyang** [comment]
[line 3313 in calcfunctions.py](https://github.com/PSLmodels/Tax-Calculator/blob/master/taxcalc/calcfunctions.py#L3313) should be changed to ctc_refund = c07220 + odc

**Comment by bodiyang** [comment]
@jdebacker @MattHJensen I can open a PR on this if agree on this issue

**Comment by jdebacker** [comment]
@bodiyang I agree that there is an issue for the ODC in 2021 law, when it was a refundable credit.

To correct Tax-Calculator, I suggest that you create an `ODC_refundable` parameter (akin to the `CTC_refundable` parameter and with similar logic). The current law policy JSON file will set the default to this to false in all years except 2021.  

The `calcfunctions.py` logic will be updated to include this boolean parameter in a  way similar to how the refundable CTC is modeled, ultimately ending an `odc_refund` amount included in the `refund` calculation in `calcfunctions.IITAX`.

**Comment by bodiyang** [comment]
This issue will be solved in [PR 2704](https://github.com/PSLmodels/Tax-Calculator/pull/2704/files)

**Comment by jdebacker** [comment]
Resolved via PR #2704
