### ISSUE TITLE
Create new 3.5.0 release

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/Tax-Calculator#2716]
@jdebacker,  There have been a few enhancements over the past few days (in #2713 and #2714) that deserve a new release.   Can you please do that?    Thanks.

**Comment by martinholmer** [comment]
Thanks, @jdebacker, for the speedy response!

**Comment by jdebacker** [comment]
@martinholmer And new release now [available on PyPI](https://pypi.org/project/taxcalc/).
