### ISSUE TITLE
Codecov token still missing

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/Tax-Calculator#2736]
PR #2735 is failing because there is no Codecov token.
I thought this was fixed, @jdebacker.

<img width="1244" alt="Screenshot 2024-04-15 at 2 43 17 PM" src="https://github.com/PSLmodels/Tax-Calculator/assets/12170745/91ab38d2-c6d8-41db-a337-13d54219493d">

**Comment by jdebacker** [comment]
Token is still there.  Seems to be one of the idiosyncratic failures I've experienced in the past.  I reran the job and it complete and successfully upload (and it already had on another test).  I started all jobs again in PR #2735.
