### ISSUE TITLE
TCJA extension reform

### ISSUE THREAD

**Issue by bodiyang** [PSLmodels/Tax-Calculator#2748]
@martinholmer @jdebacker 

Issue found from newly added ext.json reform file, related to [PR 2734
](https://github.com/PSLmodels/Tax-Calculator/pull/2734)

CBO has published a new document, [estimation of the revenue change from TCJA extension reform](https://www.cbo.gov/system/files/2024-05/60114-Budgetary-Outcomes.pdf)

Please see table 2 (in page 5)
![Screenshot 2024-05-10 at 3 35 57 PM](https://github.com/PSLmodels/Tax-Calculator/assets/60398181/7f2f19ca-bd17-42f1-ba67-75958b5907c7)

I have tried to run the simulation of TCJA extension reform in Tax-Calculator (by using ext.json file) and compare the result with CBO estimation. There are differences noticed.

This attached screenshot is the result from Tax-Calculator 
![Screenshot 2024-05-14 at 9 24 05 AM](https://github.com/PSLmodels/Tax-Calculator/assets/60398181/9ec35c72-c63e-4e52-84df-ded1227e4670)

Revenue change from TCJA extension (ext.json reform) for 2025 - 2033 calculated by Tax-Calculator (by PUF) is around 200-250 billion per year, while CBO estimation is around 350-450 billion per year.

**Comment by bodiyang** [comment]
This CBO breakdown analysis would be helpful: [the supplemental data](https://www.cbo.gov/publication/60114#data)

**Comment by jdebacker** [comment]
Page 4 of the [CBO document on the budget under alternative assumptions](https://www.cbo.gov/system/files/2023-05/59154-Budgetary-Outcomes.pdf), says:

> According to JCT’s estimates, if the expiring individual income tax provisions of the 2017 tax act were extended, deficits would be larger than those in CBO’s baseline, on net, by $2.5 trillion over the 2024–2033 period, excluding debt-service costs (see Table 2). Most of the effects would occur after 2026. Debt-service costs would add $278 billion to those deficits.

Using Tax-Calculator, I find the revenue effect from 2024-2033 to be $2.0 trillion.  This is about 20% less than the JCT estimate, but I don't know how off model items and/or behavior may impact these numbers. 

It appears CBOs much larger cost estimate include the significant increase in net interests costs that would result with extending the TCJA cuts.  Those are not accounted for in Tax-Calculator, which just focuses on direct impacts on tax revenues.

**Comment by bodiyang** [comment]
@jdebacker 

I just another check. Actually, the net interest outlays / Debt-service costs (May 2023 report & May 2024 report) is separately calculated, apart from the revenue change.

Please see the two rows here in May 2024 report
![Screenshot 2024-05-10 at 3 35 57 PM](https://github.com/PSLmodels/Tax-Calculator/assets/60398181/0e827142-7ce2-4412-af83-74382123396d)

The the calculation of revenue change for the year **2024-2033** 
Tax-Calc: $2.0 trillion
CBO May 2024 report: $ 2.8 trillion
CBO May 2023 report: $ 2.5 trillion

~~ trying to track where this difference come

**Comment by bodiyang** [comment]
@martinholmer thanks Martin 
1. The result is based on puf.csv data
2. Revenue is just the income tax revenue

**Comment by bodiyang** [comment]
I have completed a simulation of the reforms on each single parameter change, in reference to [this CBO spreadsheet](https://www.cbo.gov/publication/60114#data)

Please check this excel as a reference
[TCJA_item_ext.xlsx](https://github.com/PSLmodels/Tax-Calculator/files/15337168/TCJA_item_ext.xlsx)

Looking at the result, these reforms are close to CBO's estimation:
Individual income rates & brackets, Standard Deduction, CTC, Itemized Deduction 

While, the following reforms are far away from CBO's estimation:
Business Income Deduction, AMT, personal exemption

**Comment by bodiyang** [comment]
> I have completed some simulations of the reforms on each single parameter change, in reference to [this CBO spreadsheet](https://www.cbo.gov/publication/60114#data)
> 
> Please check this excel as a reference [TCJA_item_ext.xlsx](https://github.com/PSLmodels/Tax-Calculator/files/15337168/TCJA_item_ext.xlsx)
> 
> Looking at the result, these reforms are close to CBO's estimation: Individual income rates & brackets, Standard Deduction, CTC, Itemized Deduction
> 
> While, the following reforms are far away from CBO's estimation: Business Income Deduction, AMT, personal exemption

Please ignore this comment, this is the wrong simulation
