### ISSUE TITLE
Phase-out Standard Deduction

### ISSUE THREAD

**Issue by RobZim41** [PSLmodels/Tax-Calculator#2754]
Hey all,

I'm toying around with a reform that would phase-out the standard deduction above a given threshold.

I tried modifying Recipe 6 to overwrite `recs.standard` based on my parameters for thresholds and phase-out rates, but it had no effect on `iitax`. Upon digging deeper, I assume that instead I need to call an entirely new `StdDed` function. Is that right? And if so what's the best way of going about that?

**Comment by jdebacker** [comment]
@RobZim41 Thanks for this good question.

I can see a couple options. One, as you noted, is to write a custom `Calculator` class object with a new `StdDed` function.

But if you want to phase out the standard deduction past a certain threshold, can you get this through modifying the standard brackets and rates (e.g., one bracket starts at the phase out start and you increase the marginal tax rate on that bracket to reflect the standard deduction phase out rate)?

Or, you might use the `II_credit` set of parameters to reflect the standard deduction phase out (though perhaps the fact that the phase our rate for this parameter doesn't vary by filing status is a problem in mirroring a phase out of the standard deduction).

**Comment by martinholmer** [comment]
@RobZim41,  It was more than four months ago that you opened Tax-Calculator issue #2754.

@jdebacker responded in two days with a suggestion about how to simulate the reform you were interested in.

We have not heard from you in four months.   Do you have anything to report on this issue?
Do you have any further questions?

If we don't hear from you in the next week, I'll close issue #2754.

**Comment by martinholmer** [comment]
Seems as if issue #2754 has been resolved.
