### ISSUE TITLE
Remove TAXSIM-27 validation?

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Tax-Calculator#2761]
Now that we have the TAXSIM-35 validation testing years 2017-2021, can we remove the TAXSIM-27 validation (which covers 2017-2018)?

TAXSIM-35 has bug fixes relative to TAXSIM-27 and the interface is much clumsier to use for validation.  Because of this, I don't see a reason stop keep the TAXSIM-27 validation files around. 

Am I missing a reason to do so?

cc @martinholmer @MattHJensen

**Comment by martinholmer** [comment]
Seems sensible to remove the obsolete TAXSIM-27 tests.
