### ISSUE TITLE
tc cli apparently will not process years after 2034

### ISSUE THREAD

**Issue by donboyd5** [PSLmodels/Tax-Calculator#2776]
@martinholmer FYI -- I wrote a short bash script to run the tc cli using the tmd files for multiple years so that I can do some analysis of the outyears. I am using Tax-Calculator 4.2.0 (see tc --version at end of screenshot). I call the tc cli as follows, where YEAR is a 4-digit year:

`tc tmd.csv $YEAR --exact --tables --dump --dvars dumpvars`

The screenshot shows the selected years I wanted to run tc on, and the output shows that I was able to process 2021, 2023, 2026, and 2030, but that I cannot run tc on 2035 and later. Would it be possible to modify Tax-Calculator so that I can use the tc cli on years after 2034?

![image](https://github.com/user-attachments/assets/37cdcb38-4a18-4196-908e-961d92677a38)

**Comment by martinholmer** [comment]
The [release notes on Tax-Calculator 4.2.0](https://github.com/PSLmodels/Tax-Calculator/blob/master/docs/about/releases.md#release-history) point to [PR #2755](https://github.com/PSLmodels/Tax-Calculator/pull/2755), which explains the situation.
