### ISSUE TITLE
Correct CARES charity deduction for nonitemizers

### ISSUE THREAD

**Issue by martinholmer** [PSLmodels/Tax-Calculator#2780]
CARES introduced temporary provisions regarding charitable deductions for 2020 that were extended to 2021 according to this [IRS document](https://www.irs.gov/newsroom/expanded-tax-benefits-help-individuals-and-businesses-give-to-charity-during-2021-deductions-up-to-600-available-for-cash-donations-by-non-itemizers).  The provisions raised the cap,  on deductible charity contributions that are expressed as a fraction of AGI, and allowed nonitemizers to claim cash charitable deductions subject to a modest dollar cap (as part of their standard deduction).

The 4.2.0 version of Tax-Calculator implements these provisions in an incomplete fashion: the AGI percent limit is not applied for nonitemizers and these provisions are not extended to 2021.

Also, there is confusion about the AGI-fraction caps on itemized charitable donation deductions as can be seen by consulting IRS Publication 526 for different years.   The main correction that needs to be made is that the TCJA-era 60% of AGI cap (which CARES raised to 100% in 2020 and 2021, and which reverts to 50% in 2026) applies to cash donations, not to all donations.

**Comment by jdebacker** [comment]
Resolved with PR #2781
