### ISSUE TITLE
The domestic production deduction repeal in TCJA should be permanent

### ISSUE THREAD

**Issue by towashington** [PSLmodels/Tax-Calculator#2798]
Reference: https://bipartisanpolicy.org/explainer/the-2025-tax-debate-business-deductions-in-tcja/

implications:

1. In `policy_current_law.json`, `ALD_DomesticProduction_hc` should be set to 1 starting from 2018. [LINK](https://github.com/PSLmodels/Tax-Calculator/blob/e6566f80e10643edbdd5d05affdcfa2bc9ce4194/taxcalc/policy_current_law.json#L923)

2. In `ext.json`, line 58 should be gone. [LINK](https://github.com/PSLmodels/Tax-Calculator/blob/e6566f80e10643edbdd5d05affdcfa2bc9ce4194/taxcalc/reforms/ext.json#L58)

**Comment by martinholmer** [comment]
@towashington, thank you for the bug report in Tax-Calculator issue #2798.
Would you like to review the fix in PR #2807 (which is a draft because it is waiting for the merge of PR #2806)?

**Comment by towashington** [comment]
The fix in PR #2798 looks good to me. Thanks, @martinholmer!
