### ISSUE TITLE
Add `pyproject.toml` file

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Tax-Calculator#2803]
One now receives deprecation warnings when building `taxcalc` from source with `pip install -e .`. 

To avoid this warning, a `pyproject.toml` should be added to the root directory of the project.  See [here](https://github.com/pypa/pip/issues/11457) for more discussion.

**Comment by martinholmer** [comment]
As of Tax-Calculator 4.3.3, "make package" no longer generates deprecation warnings.

It still may be desirable to replace the `setup.py` file with a `pyproject.toml` files as suggested in issue #2803.

**Comment by martinholmer** [comment]
Issue #2803 was resolved by the merge of PR #2840.
