### ISSUE TITLE
CTC amounts for 2021 in policy_current_law.json need correction

### ISSUE THREAD

**Issue by towashington** [PSLmodels/Tax-Calculator#2821]
Note: This issue seems related to issue #2621, though not exactly the same.

Description: The ARPA lifted the CTC amounts for (and only for ) 2021. See details [here](https://www.irs.gov/credits-deductions/2021-child-tax-credit-and-advance-child-tax-credit-payments-topic-c-calculation-of-the-2021-child-tax-credit), but:
1. For tax year 2021, the CTC increased from $2,000 per qualifying child to $3,600 for children ages 5 and under at the end of 2021, and $3,000 for children ages 6 through 17 at the end of 2021, but
2. The $500 nonrefundable Credit for Other Dependents amount has not changed.

Accordingly, the 2021 value of param `CTC_c` in `policy_current_law.json` should be corrected.

**Comment by martinholmer** [comment]
@towashington,  Can you provide a simple test case for which Tax-Calculator gets the wrong amounts in 2021 for the following variables?
```
ctc_total
ctc_nonrefundable
ctc_refundable
```

**Comment by martinholmer** [comment]
@towashington,  Are you aware of the fact that Tax-Calculator has several `CTC_new_` policy parameters that came into play for 2021 only?

**Comment by martinholmer** [comment]
@towashington,  What is the status of your Tax-Calculator issue #2821 wrt the 2021 CTC?

Any test cases that show Tax-Calculator producing the wrong 2021 amount for `ctc_total`, 
`ctc_nonrefundable`, or `ctc_refundable` would be greatly appreciated.

Given that its been a week without any discussion in issue #2821, I'm going to close it.

Please open a new issue if you find a test case in which Tax-Calculator produces an incorrect 2021 amount for any of those three `ctc_` variables.
