### ISSUE TITLE
wage distribution - sensitivity analysis

### ISSUE THREAD

**Issue by MattHJensen** [PSLmodels/Tax-Calculator#400]
One of the assumptions in the data extrapolation routine that stands out is “what will the wage distribution be in the future.” As John has pointed out, it is very difficult to predict this distribution over a ten-year horizon. Currently we assume that the distribution of wages and salaries is the same throughout the budget year as it was in 2013. 

It would be nice to know how sensitive our model’s revenue estimate (and those of other similar models) is to the future wage distribution. Depending on the answer; we may want to add the ability to vary the wage distribution as a feature of the Tax-Calculator API and of TaxBrain. 

@feenberg has suggested that the historical variation in the wage distributions could serve as a range for such a sensitivity analysis. For instance, we could show how our 2015 revenue estimate would change if the wage distribution in 2015 matched the wage distribution from each year for the last couple of decades — we would keep everything else, including aggregate wages, constant.

@amy-xu has suggested that we might implement this via generating new different stage II targets of wage and salary by real AGI. We can get these historical targets from SOI historical wage distribution by AGI class tables (Table 1.4). This is an expensive way to do things though, because it would require re-running the extrapolation routine in the taxdata repository. 

A couple of questions:
1. Are there other interesting experiments besides: “How sensitive is the 2015 revenue estimate to the wage and salary distribution within the range of the last couple of decades?”  
2. Are there other ways to accomplish this, other than by using stage 2 targets of wage and salary by AGI class?

**Comment by feenberg** [comment]
On Thu, 15 Oct 2015, Matt Jensen wrote:

> 
> One of the assumptions in the data extrapolation routine that stands out is “what will
> the wage distribution be in the future.” As John has pointed out, it is very difficult
> to predict this distribution over a ten-year horizon. Currently we assume that the
> distribution of wages and salaries is the same throughout the budget year as it was in
> 2013.
> 
> It would be nice to know how sensitive our model’s revenue estimate (and those of
> other similar models) is to the future wage distribution. Depending on the answer; we
> may want to add the ability to vary the wage distribution as a feature of the
> Tax-Calculator API and of TaxBrain.

Just the wage distribution? Capital gains varies a lot from year to year 
and extrapolations of revenue from good years are therefore particularly 
optimistic. Also, it is odd to vary wages but not deductions.

> 
> @feenberg has suggested that the historical variation in the wage distributions could
> serve as a range for such a sensitivity analysis. For instance, we could show how our
> 2015 revenue estimate would change if the wage distribution in 2015 matched the wage
> distribution from each year for the last couple of decades — we would keep everything
> else, including aggregate wages, constant.
> 
> @amy-xu has suggested that we might implement this via generating new different stage
> II targets of wage and salary by real AGI. We can get these historical targets from
> SOI historical wage distribution by AGI class tables (Table 1.4). This is an expensive
> way to do things though, because it would require re-running the extrapolation routine
> in tax data.

If expense is an issue, why not reweight the aggregates according to the 
proportion of taxpayers in each AGI class for various years past years. 
That would be computationally light.

dan

**Comment by MattHJensen** [comment]
This ought to be a helpful table for comparing against TPC. Note that their growth rates are substantially higher for the upper income groups. 

http://taxpolicycenter.org/numbers/displayatab.cfm?DocID=3948

**Comment by martinholmer** [comment]
Matt said:
> This ought to be a helpful table for comparing against TPC. Note that their growth rates are substantially higher for the upper income groups.
> http://taxpolicycenter.org/numbers/displayatab.cfm?DocID=3948

This is an interesting issue.  You might be interested in knowing that there is a similar discussion in social security policy circles.  SSA Office of the Chief Actuary (OCACT) projects over the coming 75 years little or no increase in the degree of earnings inequality, while Congressional Budget Office (CBO) assumes a continuation in past increases in earnings inequality.  The result is that CBO projects a much bigger 75-year social security deficit than does OCACT.  This is because the benefit formula parameters are indexed by average wage growth (including all wages) while payroll tax revenues are collected in the CBO projection on a shrinking share of aggregate wages (as more and more of aggregate wages fall above the maximum taxable earnings level).

cc @MattHJensen @feenberg

**Comment by Amy-Xu** [comment]
Maybe we can generate another set of weights and factors using these distributions as targets. That would be interesting.

**Comment by MattHJensen** [comment]
I am removing the help wanted label as @andersonfrailey has expressed a desire to work on this issue.

**Comment by martinholmer** [comment]
@MattHJensen said on 2016-Feb-04:
> This [link] ought to be a helpful table for comparing against TPC.
> Note that their growth rates are substantially higher for the upper income groups.
>
> http://taxpolicycenter.org/numbers/displayatab.cfm?DocID=3948 .

Matt, can you supply the name of the TPC paper (or new link) as the link above is broken?

**Comment by martinholmer** [comment]
@MaxGhenis,  Thanks very much for finding the TPC documents @MattHJensen had linked to years ago.

**Comment by jdebacker** [comment]
Closing this issue. If there is continued interest in it, the TaxData repository would probably be the best place to discuss.
